"""CLI application scaffold template.

Author: Georgios-Chrysovalantis Chatzivantsidis
"""

from __future__ import annotations

CLI_ENTRY = '''\
"""Command-line interface entry point — production-ready scaffold."""
import argparse
import logging
import os
import sys
from typing import NoReturn


# ── Structured logging ──────────────────────────────────────────────
logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO"),
    format="%(asctime)s [%(name)s] %(levelname)s %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
logger = logging.getLogger("cli")


def setup_parser() -> argparse.ArgumentParser:
    """Build argument parser — separate from main for testability."""
    parser = argparse.ArgumentParser(description="My CLI App")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    parser.add_argument(
        "--config", "-c",
        default=os.getenv("APP_CONFIG", ""),
        help="Path to config file (default: $APP_CONFIG)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """Entry point. Returns exit code (0 = success, non-zero = error)."""
    parser = setup_parser()
    args = parser.parse_args(argv)

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)
        logger.debug("Verbose mode enabled")

    try:
        logger.info("Starting CLI application")
        # ── Your application logic here ──────────────────────────
        print("Hello from CLI!")
        logger.info("CLI completed successfully")
        return 0
    except Exception:
        logger.exception("Fatal error in CLI")
        return 1


if __name__ == "__main__":
    sys.exit(main())
'''

FILES: dict[str, str] = {
    "cli.py": CLI_ENTRY,
    "src/__init__.py": "",
    "tests/__init__.py": "",
    "tests/test_cli.py": (
        "import sys\n"
        "from cli import main\n\n\n"
        "def test_cli_runs() -> None:\n"
        '    result = main(["--help"])\n'
        "    # --help returns 0 on success (argparse exits before main returns)\n"
        "    assert result == 0\n"
    ),
    "pyproject.toml": (
        "[project]\n"
        'name = "my-cli"\n'
        'version = "0.1.0"\n'
        'requires-python = ">=3.11"\n'
        "dependencies = []\n\n"
        "[project.optional-dependencies]\n"
        "dev = [\n"
        '    "pytest>=8.0",\n'
        '    "pytest-cov>=5.0",\n'
        '    "ruff>=0.4",\n'
        '    "mypy>=1.8",\n'
        "]\n\n"
        "[project.scripts]\n"
        'my-cli = "cli:main"\n\n'
        "[build-system]\n"
        'requires = ["setuptools>=68"]\n'
        'build-backend = "setuptools.build_meta"\n'
    ),
    ".gitignore": "__pycache__/\n*.py[cod]\n.env\nvenv/\n.venv/\ndist/\nbuild/\n*.egg-info/\n",
    "README.md": r"""# ⌨️ Python CLI Application

**Project Type:** CLI Tool (Python)
**Platform:** Windows, macOS, Linux

---

## ⚡ Quick Start (Windows)

### Prerequisites
- [Python 3.11+](https://python.org/downloads/)

### 1. Create Virtual Environment (Recommended)
```powershell
# Open PowerShell in project folder
python -m venv venv

# Activate virtual environment
venv\Scripts\activate
```

### 2. Install Package
```powershell
pip install -e .
```

### 3. Run CLI
```powershell
# Direct execution
python cli.py

# Or after installation
my-cli

# With verbose output
my-cli --verbose
```

---

## 📦 Run Tests

```powershell
# Make sure venv is activated
venv\Scripts\activate

# Run tests
pytest

# Run with coverage
pytest --cov=src
```

---

## 🛠️ Development

| Command | Description |
|---------|-------------|
| `python cli.py` | Run CLI directly |
| `python cli.py --verbose` | Run with verbose output |
| `pytest` | Run unit tests |
| `pip install -e .` | Install in editable mode |

---

## 📁 Project Structure

```
├── cli.py              # CLI entry point
├── src/                # Source package
├── tests/              # Unit tests
├── venv/               # Virtual environment
├── pyproject.toml      # Package config
└── README.md           # This file
```

---

**Generated by Multi-LLM Orchestrator** — *This IS a Python project. Requires Python 3.11+*
""",
    ".env.example": "# Environment variables\n",
}
