"""CLI application scaffold template.

Author: Georgios-Chrysovalantis Chatzivantsidis
"""
from __future__ import annotations

CLI_ENTRY = '''\
"""Command-line interface entry point."""
import argparse
import sys


def main() -> None:
    parser = argparse.ArgumentParser(description="My CLI App")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    args = parser.parse_args()
    print("Hello from CLI!")
    if args.verbose:
        print("Verbose mode enabled")


if __name__ == "__main__":
    main()
'''

FILES: dict[str, str] = {
    "cli.py": CLI_ENTRY,
    "src/__init__.py": "",
    "tests/__init__.py": "",
    "tests/test_cli.py": (
        'import subprocess\nimport sys\n\n\n'
        'def test_cli_runs():\n'
        '    result = subprocess.run(\n'
        '        [sys.executable, "cli.py"],\n'
        '        capture_output=True, text=True\n'
        '    )\n'
        '    assert result.returncode == 0\n'
    ),
    "pyproject.toml": (
        '[project]\n'
        'name = "my-cli"\n'
        'version = "0.1.0"\n'
        'requires-python = ">=3.11"\n'
        'dependencies = []\n\n'
        '[project.scripts]\n'
        'my-cli = "cli:main"\n\n'
        '[build-system]\n'
        'requires = ["setuptools>=68"]\n'
        'build-backend = "setuptools.build_meta"\n'
    ),
    ".gitignore": "__pycache__/\n*.py[cod]\n.env\nvenv/\n.venv/\ndist/\nbuild/\n*.egg-info/\n",
    "README.md": r"""# ⌨️ Python CLI Application

**Project Type:** CLI Tool (Python)
**Platform:** Windows, macOS, Linux

---

## ⚡ Quick Start (Windows)

### Prerequisites
- [Python 3.11+](https://python.org/downloads/)

### 1. Create Virtual Environment (Recommended)
```powershell
# Open PowerShell in project folder
python -m venv venv

# Activate virtual environment
venv\Scripts\activate
```

### 2. Install Package
```powershell
pip install -e .
```

### 3. Run CLI
```powershell
# Direct execution
python cli.py

# Or after installation
my-cli

# With verbose output
my-cli --verbose
```

---

## 📦 Run Tests

```powershell
# Make sure venv is activated
venv\Scripts\activate

# Run tests
pytest

# Run with coverage
pytest --cov=src
```

---

## 🛠️ Development

| Command | Description |
|---------|-------------|
| `python cli.py` | Run CLI directly |
| `python cli.py --verbose` | Run with verbose output |
| `pytest` | Run unit tests |
| `pip install -e .` | Install in editable mode |

---

## 📁 Project Structure

```
├── cli.py              # CLI entry point
├── src/                # Source package
├── tests/              # Unit tests
├── venv/               # Virtual environment
├── pyproject.toml      # Package config
└── README.md           # This file
```

---

**Generated by Multi-LLM Orchestrator** — *This IS a Python project. Requires Python 3.11+*
""",
    ".env.example": "# Environment variables\n",
}
