"""FastAPI application scaffold template.

Author: Georgios-Chrysovalantis Chatzivantsidis
"""

from __future__ import annotations

FASTAPI_MAIN = """\
from fastapi import FastAPI

app = FastAPI(title="My FastAPI App")


@app.get("/health")
async def health() -> dict:
    return {"status": "ok"}


@app.get("/")
async def root() -> dict:
    return {"message": "Hello, World!"}
"""

FASTAPI_REQUIREMENTS = """\
fastapi>=0.110.0
uvicorn[standard]>=0.27.0
"""

FILES: dict[str, str] = {
    "src/__init__.py": "",
    "src/main.py": FASTAPI_MAIN,
    "tests/__init__.py": "",
    "tests/test_main.py": (
        "import pytest\n"
        "from fastapi.testclient import TestClient\n"
        "from src.main import app\n\n\n"
        "client = TestClient(app)\n\n\n"
        "def test_health():\n"
        '    response = client.get("/health")\n'
        "    assert response.status_code == 200\n"
    ),
    "pyproject.toml": (
        "[project]\n"
        'name = "my-app"\n'
        'version = "0.1.0"\n'
        'requires-python = ">=3.11"\n'
        "dependencies = [\n"
        '    "fastapi>=0.110.0",\n'
        '    "uvicorn[standard]>=0.27.0",\n'
        "]\n\n"
        "[build-system]\n"
        'requires = ["setuptools>=68"]\n'
        'build-backend = "setuptools.build_meta"\n'
    ),
    ".gitignore": "__pycache__/\n*.py[cod]\n.env\nvenv/\n.venv/\ndist/\nbuild/\n*.egg-info/\n",
    "README.md": r"""# 🚀 FastAPI Backend Application

**Project Type:** Backend (Python + FastAPI)
**Platform:** Windows, macOS, Linux

---

## ⚡ Quick Start (Windows)

### Prerequisites
- [Python 3.11+](https://python.org/downloads/)
- pip (included with Python)

### 1. Create Virtual Environment
```powershell
# Open PowerShell in project folder
python -m venv venv

# Activate virtual environment
venv\Scripts\activate
```

### 2. Install Dependencies
```powershell
pip install -e .
# OR
pip install fastapi uvicorn
```

### 3. Start Development Server
```powershell
uvicorn src.main:app --reload
```

### 4. Test the API
Open browser: [http://localhost:8000](http://localhost:8000)

Interactive docs: [http://localhost:8000/docs](http://localhost:8000/docs)

---

## 📦 Run Tests

```powershell
# Make sure venv is activated
venv\Scripts\activate

# Run tests
pytest

# Run with coverage
pytest --cov=src
```

---

## 🛠️ Available Commands

| Command | Description |
|---------|-------------|
| `uvicorn src.main:app --reload` | Start dev server with auto-reload |
| `uvicorn src.main:app --host 0.0.0.0 --port 8000` | Start on all interfaces |
| `pytest` | Run unit tests |
| `pytest --cov=src` | Run tests with coverage |

---

## 📁 Project Structure

```
├── src/
│   ├── __init__.py
│   └── main.py         # FastAPI application
├── tests/
│   ├── __init__.py
│   └── test_main.py    # Unit tests
├── venv/               # Virtual environment
├── pyproject.toml      # Dependencies
└── README.md           # This file
```

---

**Generated by Multi-LLM Orchestrator** — *This IS a Python project. Requires Python 3.11+*
""",
    ".env.example": "# Environment variables\nPORT=8000\n",
}
