"""Generic/fallback scaffold template — used for unknown app types.

Author: Georgios-Chrysovalantis Chatzivantsidis
"""

from __future__ import annotations

FILES: dict[str, str] = {
    "main.py": (
        '"""Main entry point — production-ready scaffold."""\n'
        "import logging\n"
        "import os\n"
        "import sys\n"
        "from typing import Any\n\n\n"
        "# ── Structured logging ──────────────────────────────────────────\n"
        "logging.basicConfig(\n"
        '    level=os.getenv("LOG_LEVEL", "INFO"),\n'
        '    format="%(asctime)s [%(name)s] %(levelname)s %(message)s",\n'
        '    datefmt="%Y-%m-%dT%H:%M:%S",\n'
        ")\n"
        'logger = logging.getLogger("app")\n\n\n'
        "def main() -> int:\n"
        '    """Entry point. Returns exit code (0 = success)."""\n'
        "    try:\n"
        '        logger.info("Application starting")\n'
        '        print("Hello, World!")\n'
        '        logger.info("Application completed successfully")\n'
        "        return 0\n"
        "    except Exception:\n"
        '        logger.exception("Fatal error")\n'
        "        return 1\n\n\n"
        'if __name__ == "__main__":\n'
        "    sys.exit(main())\n"
    ),
    "src/__init__.py": "",
    "tests/__init__.py": "",
    "tests/test_main.py": (
        "from main import main\n\n\n"
        "def test_main_runs() -> None:\n"
        "    result = main()\n"
        "    assert result == 0\n\n\n"
        "def test_main_returns_nonzero_on_error() -> None:\n"
        "    # Test that the function returns an int exit code\n"
        "    assert isinstance(main(), int)\n"
    ),
    "pyproject.toml": (
        "[project]\n"
        'name = "my-app"\n'
        'version = "0.1.0"\n'
        'requires-python = ">=3.11"\n'
        "dependencies = []\n\n"
        "[project.optional-dependencies]\n"
        "dev = [\n"
        '    "pytest>=8.0",\n'
        '    "pytest-cov>=5.0",\n'
        '    "ruff>=0.4",\n'
        '    "mypy>=1.8",\n'
        "]\n\n"
        "[build-system]\n"
        'requires = ["setuptools>=68"]\n'
        'build-backend = "setuptools.build_meta"\n'
    ),
    ".gitignore": "__pycache__/\n*.py[cod]\n.env\nvenv/\n.venv/\ndist/\nbuild/\n*.egg-info/\n",
    "README.md": r"""# 🐍 Python Application

**Project Type:** Python Application
**Platform:** Windows, macOS, Linux

---

## ⚡ Quick Start (Windows)

### Prerequisites
- [Python 3.11+](https://python.org/downloads/)

### 1. Create Virtual Environment
```powershell
python -m venv venv
venv\Scripts\activate
```

### 2. Install Dependencies
```powershell
pip install -e .
```

### 3. Run Application
```powershell
python main.py
```

---

## 📦 Run Tests
```powershell
venv\Scripts\activate
pytest
```

---

**Generated by Multi-LLM Orchestrator** — *This IS a Python project.*
""",
    ".env.example": (
        "# ── Application settings ──────────────────\n"
        "LOG_LEVEL=INFO\n"
        "ENVIRONMENT=development\n"
    ),
}
