"""Vanilla HTML/CSS/JS scaffold template.

Provides a minimal frontend scaffold with:
- index.html entry point
- CSS and JS files
- A responsive layout
"""

from __future__ import annotations

FILES: dict[str, str] = {
    "index.html": """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My App</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div id="app">
        <h1>Hello, World!</h1>
    </div>
    <script src="app.js"></script>
</body>
</html>
""",
    "styles.css": """* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    background: #f5f5f5;
}

#app {
    text-align: center;
}

h1 {
    color: #333;
}
""",
    "app.js": """// App entry point
console.log('App initialized');
""",
    ".gitignore": """node_modules/
dist/
.env
*.log
""",
    "README.md": """# 🌐 Vanilla HTML/CSS/JS Frontend

**Project Type:** Frontend (HTML5 + CSS3 + JavaScript)
**Platform:** Windows, macOS, Linux

---

## ⚡ Quick Start (Windows)

### Option 1: Direct Open
Simply double-click `index.html` to open in your default browser.

### Option 2: Local Server (Recommended)
```powershell
# Using Python (if installed)
python -m http.server 8000

# Using Node.js npx
npx serve .

# Using VS Code Live Server extension
# Right-click index.html → "Open with Live Server"
```

Then open: [http://localhost:8000](http://localhost:8000)

---

## 📦 Build for Production (Optional)

If you add a build step later:

```powershell
# Install dependencies
npm install

# Build (if using Vite or similar)
npm run build
```

---

## 📁 Project Structure

```
├── index.html      # Main HTML file
├── styles.css      # CSS styles
├── app.js          # JavaScript code
└── README.md       # This file
```

---

## 🌐 Browser Support

- Chrome/Edge 90+
- Firefox 90+
- Safari 15+

---

**Generated by Multi-LLM Orchestrator** — *Not a Python project. This is a vanilla HTML/CSS/JS frontend.*
""",
}
