"""React + Vite + TypeScript + Tailwind CSS scaffold template.

Provides a minimal but functional React SPA with:
- Vite build tooling
- TypeScript
- Tailwind CSS
- A clean App component ready to be filled by the orchestrator
"""
from __future__ import annotations

FILES: dict[str, str] = {
    "package.json": """{
  "name": "my-react-app",
  "version": "0.1.0",
  "private": True,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview",
    "test": "vitest run --passWithNoTests"
  },
  "dependencies": {
    "react": "^18.3.0",
    "react-dom": "^18.3.0"
  },
  "devDependencies": {
    "typescript": "^5.4.0",
    "@types/react": "^18.3.0",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.0",
    "vite": "^5.2.0",
    "tailwindcss": "^3.4.0",
    "postcss": "^8.4.0",
    "autoprefixer": "^10.4.0",
    "vitest": "^1.6.0",
    "@testing-library/react": "^15.0.0",
    "@testing-library/jest-dom": "^6.0.0"
  }
}
""",
    "tsconfig.json": """{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": True,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": True,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": True,
    "resolveJsonModule": True,
    "isolatedModules": True,
    "noEmit": True,
    "jsx": "react-jsx",
    "strict": True,
    "noUnusedLocals": True,
    "noUnusedParameters": True,
    "noFallthroughCasesInSwitch": True
  },
  "include": ["src"],
  "references": [{"path": "./tsconfig.node.json"}]
}
""",
    "tsconfig.node.json": """{
  "compilerOptions": {
    "composite": True,
    "skipLibCheck": True,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "allowSyntheticDefaultImports": True
  },
  "include": ["vite.config.ts"]
}
""",
    "vite.config.ts": """import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
""",
    "tailwind.config.ts": """import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;
""",
    "postcss.config.js": """export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
""",
    "index.html": """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My React App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
""",
    "src/index.css": """@tailwind base;
@tailwind components;
@tailwind utilities;
""",
    "src/main.tsx": """import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
""",
    "src/App.tsx": """export default function App() {
  return (
    <div className="flex min-h-screen items-center justify-center">
      <h1 className="text-4xl font-bold">Hello, World!</h1>
    </div>
  );
}
""",
    ".gitignore": """# Logs
logs
*.log

# Dependencies
node_modules
dist
dist-ssr
*.local

# Editor
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
""",
    "README.md": """# ⚛️ React + Vite Frontend Application

**Project Type:** Frontend (React + TypeScript + Tailwind)
**Platform:** Windows, macOS, Linux

---

## ⚡ Quick Start (Windows)

### Prerequisites
- [Node.js 18+](https://nodejs.org/) (LTS recommended)
- npm (included with Node.js)

### 1. Install Dependencies
```powershell
# Open PowerShell or CMD in project folder
npm install
```

### 2. Start Development Server
```powershell
npm run dev
```

### 3. Open in Browser
Navigate to: [http://localhost:5173](http://localhost:5173)

---

## 📦 Build for Production

```powershell
# Create optimized build in dist/
npm run build

# Preview production build locally
npm run preview
```

---

## 🛠️ Available Scripts

| Command | Description |
|---------|-------------|
| `npm run dev` | Start dev server with hot reload (port 5173) |
| `npm run build` | Build optimized production bundle |
| `npm run preview` | Preview production build locally |
| `npm test` | Run tests with Vitest |

---

## 📁 Project Structure

```
├── src/              # React source code
│   ├── components/   # React components
│   ├── App.tsx       # Main App component
│   └── main.tsx      # Entry point
├── public/           # Static assets
├── dist/             # Production build output
├── index.html        # HTML template
└── package.json      # Dependencies
```

---

**Generated by Multi-LLM Orchestrator** — *Not a Python project. This is a Node.js/React application.*
""",
}
