#!/usr/bin/env python3
"""Fix all emojis in dashboard_mission_control.py"""
import re

filepath = "orchestrator/dashboard_mission_control.py"

with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

# Emoji to ASCII mapping
emoji_map = {
    "✅": "[OK]",
    "⚠️": "[WARN]",
    "❌": "[ERR]",
    "🚀": "[START]",
    "📁": "[DIR]",
    "📂": "[OUT]",
    "🎯": "[TARGET]",
    "💓": "[BEAT]",
    "🛑": "[STOP]",
    "✨": "[*]",
    "🔴": "[OFF]",
    "🟢": "[ON]",
    "🔧": "[FIX]",
    "📄": "[FILE]",
    "💡": "[IDEA]",
    "📊": "[DATA]",
    "💻": "[CODE]",
    "⚙️": "[CFG]",
    "📡": "[NET]",
    "🌐": "[WEB]",
    "🤖": "[BOT]",
    "🔍": "[FIND]",
    "📝": "[EDIT]",
    "🎉": "[DONE]",
    "🏆": "[WIN]",
    "📈": "[UP]",
    "🔥": "[HOT]",
    "💰": "[$]",
    "⏱️": "[TIME]",
    "⏹️": "[HALT]",
    "🎮": "[GAME]",
    "🐛": "[BUG]",
    "🧹": "[CLEAN]",
    "📋": "[LIST]",
    "🏗️": "[BUILD]",
    "🎨": "[ART]",
    "🔌": "[PLUG]",
    "⚡": "[FAST]",
    "🔄": "[SYNC]",
    "✔️": "[OK]",
    "☑️": "[OK]",
    "🔒": "[LOCK]",
    "🗑️": "[TRASH]",
    "📤": "[UPLOAD]",
    "💎": "[GEM]",
    "🎁": "[GIFT]",
    "🎊": "[CELEB]",
    "🎈": "[BALLOON]",
    "💥": "[BOOM]",
    "💫": "[SPARKLE]",
    "💬": "[CHAT]",
    "💭": "[THINK]",
    "💤": "[SLEEP]",
    "💢": "[ANGER]",
    "💣": "[BOMB]",
    "💥": "[EXPLODE]",
    "💦": "[SWEAT]",
    "💨": "[DASH]",
    "💫": "[DIZZY]",
    "💬": "[SPEECH]",
    "💭": "[THOUGHT]",
    "💡": "[BULB]",
    "💯": "[100]",
    "💰": "[MONEY]",
    "💱": "[CURRENCY]",
    "💲": "[$$]",
    "💳": "[CARD]",
    "💴": "[YEN]",
    "💵": "[DOLLAR]",
    "💶": "[EURO]",
    "💷": "[POUND]",
    "💸": "[FLYING$]",
    "💹": "[CHART]",
    "💺": "[SEAT]",
    "💻": "[LAPTOP]",
    "💼": "[BRIEFCASE]",
    "💽": "[DISK]",
    "💾": "[FLOPPY]",
    "💿": "[CD]",
    "📀": "[DVD]",
    "📁": "[FOLDER]",
    "📂": "[OPEN]",
    "📃": "[PAGE]",
    "📄": "[DOC]",
    "📅": "[CALENDAR]",
    "📆": "[CAL]",
    "📇": "[CARD]",
    "📈": "[UP]",
    "📉": "[DOWN]",
    "📊": "[BAR]",
    "📋": "[CLIP]",
    "📌": "[PIN]",
    "📍": "[ROUND]",
    "📎": "[PAPERCLIP]",
    "📏": "[RULER]",
    "📐": "[TRIANGLE]",
    "📑": "[BOOKMARK]",
    "📒": "[LEDGER]",
    "📓": "[NOTEBOOK]",
    "📔": "[COVER]",
    "📕": "[BOOK]",
    "📖": "[OPENBK]",
    "📗": "[GREEN]",
    "📘": "[BLUE]",
    "📙": "[ORANGE]",
    "📚": "[BOOKS]",
    "📛": "[BADGE]",
    "📜": "[SCROLL]",
    "📝": "[MEMO]",
    "📞": "[PHONE]",
    "📟": "[PAGER]",
    "📠": "[FAX]",
    "📡": "[SAT]",
    "📢": "[LOUD]",
    "📣": "[MEGA]",
    "📤": "[OUTBOX]",
    "📥": "[INBOX]",
    "📦": "[PKG]",
    "📧": "[EMAIL]",
    "📨": "[IN]",
    "📩": "[ENV]",
    "📪": "[CLOSED]",
    "📫": "[MAIL]",
    "📬": "[OPEN]",
    "📭": "[EMPTY]",
    "📮": "[POST]",
    "📯": "[HORN]",
    "📰": "[NEWS]",
    "📱": "[MOBILE]",
    "📲": "[CALL]",
    "📳": "[VIBRATE]",
    "📴": "[OFF]",
    "📵": "[NO]",
    "📶": "[BARS]",
    "📷": "[CAM]",
    "📸": "[FLASH]",
    "📹": "[VIDEO]",
    "📺": "[TV]",
    "📻": "[RADIO]",
    "📼": "[TAPE]",
    "📽️": "[FILM]",
    "📿": "[BEADS]",
    "🔀": "[SHUFFLE]",
    "🔁": "[REPEAT]",
    "🔂": "[ONCE]",
    "🔃": "[CLOCK]",
    "🔄": "[CYCLE]",
    "🔅": "[DIM]",
    "🔆": "[BRIGHT]",
    "🔇": "[MUTE]",
    "🔈": "[LOW]",
    "🔉": "[MID]",
    "🔊": "[HIGH]",
    "🔋": "[BAT]",
    "🔌": "[PLUG]",
    "🔍": "[LEFT]",
    "🔎": "[RIGHT]",
    "🔏": "[LOCK]",
    "🔐": "[OPEN]",
    "🔑": "[KEY]",
    "🔒": "[LOCK]",
    "🔓": "[UNLOCK]",
    "🔔": "[BELL]",
    "🔕": "[NOBELL]",
    "🔖": "[TAG]",
    "🔗": "[LINK]",
    "🔘": "[RADIO]",
    "🔙": "[BACK]",
    "🔚": "[END]",
    "🔛": "[ON]",
    "🔜": "[SOON]",
    "🔝": "[TOP]",
    "🔞": "[18]",
    "🔟": "[10]",
    "🔠": "[ABC]",
    "🔡": "[abc]",
    "🔢": "[123]",
    "🔣": "[SYM]",
    "🔤": "[ALPHA]",
    "🔥": "[FIRE]",
    "🔦": "[FLASH]",
    "🔧": "[WRENCH]",
    "🔨": "[HAMMER]",
    "🔩": "[NUT]",
    "🔪": "[KNIFE]",
    "🔫": "[GUN]",
    "🔬": "[MICRO]",
    "🔭": "[TELE]",
    "🔮": "[BALL]",
    "🔯": "[STAR]",
    "🔰": "[BEGIN]",
    "🔱": "[TRIDENT]",
    "🔲": "[BLACK]",
    "🔳": "[WHITE]",
    "🔴": "[RED]",
    "🔵": "[BLUE]",
    "🔶": "[ORANGE]",
    "🔷": "[DIAMOND]",
    "🔸": "[SMALL]",
    "🔹": "[SBLUE]",
    "🔺": "[UP]",
    "🔻": "[DOWN]",
    "🔼": "[UP]",
    "🔽": "[DOWN]",
    "🕉️": "[OM]",
    "🕊️": "[DOVE]",
    "🕋": "[KABA]",
    "🕌": "[MOSQUE]",
    "🕍": "[SYNAGOGUE]",
    "🕎": "[MENORAH]",
    "🕐": "[1]",
    "🕑": "[2]",
    "🕒": "[3]",
    "🕓": "[4]",
    "🕔": "[5]",
    "🕕": "[6]",
    "🕖": "[7]",
    "🕗": "[8]",
    "🕘": "[9]",
    "🕙": "[10]",
    "🕚": "[11]",
    "🕛": "[12]",
    "🕜": "[130]",
    "🕝": "[230]",
    "🕞": "[330]",
    "🕟": "[430]",
    "🕠": "[530]",
    "🕡": "[630]",
    "🕢": "[730]",
    "🕣": "[830]",
    "🕤": "[930]",
    "🕥": "[1030]",
    "🕦": "[1130]",
    "🕧": "[1230]",
    "🕯️": "[CANDLE]",
    "🕰️": "[MANTLE]",
    "🕳️": "[HOLE]",
    "🕴️": "[SUIT]",
    "🕵️": "[SPY]",
    "🕶️": "[SHADES]",
    "🕷️": "[SPIDER]",
    "🕸️": "[WEB]",
    "🕹️": "[JOY]",
    "🕺": "[DANCE]",
    "🖇️": "[LINKS]",
    "🖊️": "[PEN]",
    "🖋️": "[Fountain]",
    "🖌️": "[PAINT]",
    "🖍️": "[CRAYON]",
    "🖐️": "[HAND]",
    "🖕": "[MIDDLE]",
    "🖖": "[VULCAN]",
    "🖤": "[BLACK]",
    "🖥️": "[DESK]",
    "🖨️": "[PRINT]",
    "🖱️": "[MOUSE]",
    "🖲️": "[TRACK]",
    "🖼️": "[FRAME]",
    "🗂️": "[DIVIDE]",
    "🗃️": "[BOX]",
    "🗄️": "[CAB]",
    "🗑️": "[WASTE]",
    "🗒️": "[NOTE]",
    "🗓️": "[SPIRAL]",
    "🗜️": "[CLAMP]",
    "🗝️": "[OLD]",
    "🗞️": "[ROLL]",
    "🗡️": "[DAGGER]",
    "🗣️": "[SHOUT]",
    "🗨️": "[LEFT]",
    "🗯️": "[RIGHT]",
    "🗳️": "[BALLOT]",
    "🗺️": "[MAP]",
    "🗻": "[MOUNT]",
    "🗼": "[TOWER]",
    "🗽": "[LIBERTY]",
    "🗾": "[JP]",
    "🗿": "[MOAI]",
}

# Replace all emojis
for emoji, replacement in emoji_map.items():
    content = content.replace(emoji, replacement)

# Also try to catch any remaining emojis using a broader regex
# This will replace any remaining non-ASCII characters in string literals
import unicodedata

def replace_remaining_emojis(text):
    result = []
    for char in text:
        if ord(char) > 127 and not char.isalpha() and not char.isdigit():
            # Check if it's an emoji
            try:
                name = unicodedata.name(char)
                if 'EMOJI' in name or 'EMOTICON' in name or 'SYMBOL' in name:
                    result.append(f'[emoji]')
                else:
                    result.append(char)
            except:
                result.append(f'[?]')
        else:
            result.append(char)
    return ''.join(result)

content = replace_remaining_emojis(content)

with open(filepath, "w", encoding="utf-8") as f:
    f.write(content)

print("Fixed all emojis in dashboard_mission_control.py")
print("Please restart the server")
