"""
Macrostructure Catalog — 21 named page shapes.
==============================================
Author: Georgios-Chrysovalantis Chatzivantsidis

Each macrostructure is a complete fingerprint: heading placement, body composition,
divider language, button voice, image treatment, reveal pattern.

Source: Hallmark design skill (references/macrostructures.md)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal


@dataclass(frozen=True)
class Macrostructure:
    """A named whole-page shape — structural fingerprint."""

    name: str
    slug: str
    heading: Literal[
        "left-margin",
        "hanging",
        "centered",
        "bottom",
        "overlap",
        "sticky",
        "numbered",
        "inline",
    ]
    body: Literal[
        "single",
        "two-asym",
        "multi-justify",
        "marginalia",
        "three-equal",
        "full-bleed",
        "asymmetric",
    ]
    divider: Literal[
        "hairline",
        "ornament",
        "negative",
        "bleed-color",
        "double-rule",
    ]
    button: Literal[
        "outlined",
        "unstyled",
        "oversized",
        "typographic",
        "form-cta",
    ]
    image: Literal[
        "full-bleed",
        "tight-crop",
        "inline",
        "margin",
        "none",
    ]
    reveal: Literal[
        "fade-up",
        "horizontal",
        "type-unmask",
        "number-tick",
        "typewriter",
        "none",
    ]
    nav_default: str
    footer_default: str
    domains: list[str] = field(default_factory=list)
    saas_sections: list[str] | None = None
    description: str = ""


# ═══════════════════════════════════════════════════════════════════════════════
# The 21 macrostructures — index
# ═══════════════════════════════════════════════════════════════════════════════

MACROSTRUCTURES: dict[str, Macrostructure] = {
    "bento_grid": Macrostructure(
        name="Bento Grid",
        slug="bento_grid",
        heading="centered",
        body="asymmetric",
        divider="negative",
        button="outlined",
        image="tight-crop",
        reveal="fade-up",
        nav_default="N5",
        footer_default="Ft1",
        domains=["saas", "platform", "infra", "product"],
        saas_sections=["hero", "social_proof", "features", "testimonials", "pricing", "faq", "cta", "footer"],
        description="Modular blocks of varying sizes laid out as an irregular grid.",
    ),
    "long_document": Macrostructure(
        name="Long Document",
        slug="long_document",
        heading="inline",
        body="single",
        divider="hairline",
        button="unstyled",
        image="inline",
        reveal="none",
        nav_default="N1a",
        footer_default="Ft6",
        domains=["editorial", "blog", "docs", "personal"],
        description="Reads like a memo, a letter, or a journal entry. No marketing structure.",
    ),
    "marquee_hero": Macrostructure(
        name="Marquee Hero",
        slug="marquee_hero",
        heading="centered",
        body="single",
        divider="negative",
        button="typographic",
        image="none",
        reveal="fade-up",
        nav_default="N5",
        footer_default="Ft5",
        domains=["saas", "launch", "event", "brand"],
        description="The hero IS the page above the fold. A single bold statement fills the viewport.",
    ),
    "stat_led": Macrostructure(
        name="Stat-Led",
        slug="stat_led",
        heading="numbered",
        body="asymmetric",
        divider="hairline",
        button="oversized",
        image="none",
        reveal="number-tick",
        nav_default="N5",
        footer_default="Ft2",
        domains=["saas", "fintech", "platform", "analytics"],
        saas_sections=["hero", "social_proof", "features", "testimonials", "pricing", "faq", "cta", "footer"],
        description="The hero is a giant number — a metric, a count, a percentage.",
    ),
    "workbench": Macrostructure(
        name="Workbench",
        slug="workbench",
        heading="hanging",
        body="two-asym",
        divider="hairline",
        button="outlined",
        image="tight-crop",
        reveal="fade-up",
        nav_default="N1b",
        footer_default="Ft1",
        domains=["saas", "dev-tool", "docs", "product"],
        saas_sections=["hero", "features", "testimonials", "pricing", "faq", "cta", "footer"],
        description="Product screenshots in frames are the primary content. Guided tour of the app.",
    ),
    "conversational_faq": Macrostructure(
        name="Conversational FAQ",
        slug="conversational_faq",
        heading="hanging",
        body="single",
        divider="negative",
        button="outlined",
        image="none",
        reveal="none",
        nav_default="N1b",
        footer_default="Ft7",
        domains=["saas", "support", "docs"],
        description="Bold questions, brief answers. Reads like an honest interview with the product.",
    ),
    "manifesto": Macrostructure(
        name="Manifesto",
        slug="manifesto",
        heading="overlap",
        body="full-bleed",
        divider="bleed-color",
        button="oversized",
        image="full-bleed",
        reveal="horizontal",
        nav_default="N7",
        footer_default="Ft5",
        domains=["brand", "agency", "cause", "campaign"],
        description="Polemical large type. Declaration energy. Political-poster aesthetic.",
    ),
    "photographic": Macrostructure(
        name="Photographic",
        slug="photographic",
        heading="overlap",
        body="full-bleed",
        divider="negative",
        button="unstyled",
        image="full-bleed",
        reveal="none",
        nav_default="N9",
        footer_default="Ft1",
        domains=["fashion", "food", "travel", "portfolio", "luxury"],
        description="A single huge image dominates each fold. Text is small annotation, not headline.",
    ),
    "quote_led": Macrostructure(
        name="Quote-Led",
        slug="quote_led",
        heading="centered",
        body="single",
        divider="negative",
        button="typographic",
        image="none",
        reveal="fade-up",
        nav_default="N5",
        footer_default="Ft5",
        domains=["saas", "agency", "consulting", "personal"],
        description="The hero is a pull-quote with attribution. Leads with social proof.",
    ),
    "specimen": Macrostructure(
        name="Specimen",
        slug="specimen",
        heading="left-margin",
        body="asymmetric",
        divider="hairline",
        button="typographic",
        image="none",
        reveal="fade-up",
        nav_default="N5",
        footer_default="Ft2",
        domains=["editorial", "foundry", "magazine", "type"],
        description="Numbered left-margin labels, huge serif display, asymmetric spans, typographic-only CTA.",
    ),
    "catalogue": Macrostructure(
        name="Catalogue",
        slug="catalogue",
        heading="hanging",
        body="three-equal",
        divider="hairline",
        button="outlined",
        image="tight-crop",
        reveal="none",
        nav_default="N3",
        footer_default="Ft3",
        domains=["commerce", "product", "shop", "store"],
        description="Uniform grid of variations of the same thing — typefaces, palettes, product SKUs.",
    ),
    "letter": Macrostructure(
        name="Letter",
        slug="letter",
        heading="inline",
        body="single",
        divider="negative",
        button="unstyled",
        image="none",
        reveal="none",
        nav_default="N1a",
        footer_default="Ft6",
        domains=["personal", "about-me", "founder", "indie"],
        description="First-person, written, intimate. Opens with a greeting. No buttons in the fold.",
    ),
    "index_first": Macrostructure(
        name="Index-First",
        slug="index_first",
        heading="inline",
        body="three-equal",
        divider="hairline",
        button="typographic",
        image="none",
        reveal="none",
        nav_default="N4",
        footer_default="Ft3",
        domains=["personal", "portfolio", "linktree", "directory"],
        description="The page IS a list of links. No hero image, no narrative flow. Pure navigation as design.",
    ),
    "narrative_workflow": Macrostructure(
        name="Narrative Workflow",
        slug="narrative_workflow",
        heading="numbered",
        body="asymmetric",
        divider="hairline",
        button="outlined",
        image="tight-crop",
        reveal="number-tick",
        nav_default="N1b",
        footer_default="Ft1",
        domains=["saas", "onboarding", "recipe", "learning", "process"],
        description="Numbered stages tell the story of how the user uses the product over time.",
    ),
    "split_studio": Macrostructure(
        name="Split Studio",
        slug="split_studio",
        heading="hanging",
        body="two-asym",
        divider="negative",
        button="outlined",
        image="tight-crop",
        reveal="horizontal",
        nav_default="N9",
        footer_default="Ft1",
        domains=["agency", "studio", "portfolio", "creative"],
        description="Diptych. Every major content block divides the screen — text on one side, proof on the other.",
    ),
    "feature_stack": Macrostructure(
        name="Feature Stack",
        slug="feature_stack",
        heading="sticky",
        body="two-asym",
        divider="hairline",
        button="outlined",
        image="tight-crop",
        reveal="fade-up",
        nav_default="N1b",
        footer_default="Ft1",
        domains=["saas", "product", "dev-tool"],
        description="Sticky left pane + scroll-synced right pane (screenshots cycling). Cinematic pacing.",
    ),
    "type_specimen": Macrostructure(
        name="Type Specimen",
        slug="type_specimen",
        heading="centered",
        body="asymmetric",
        divider="hairline",
        button="typographic",
        image="none",
        reveal="type-unmask",
        nav_default="N6",
        footer_default="Ft4",
        domains=["editorial", "foundry", "design-system"],
        description="The typeface IS the design. Foundry homepage where a custom typeface is the brand's proof.",
    ),
    "portfolio_grid": Macrostructure(
        name="Portfolio Grid",
        slug="portfolio_grid",
        heading="hanging",
        body="asymmetric",
        divider="hairline",
        button="outlined",
        image="tight-crop",
        reveal="fade-up",
        nav_default="N3",
        footer_default="Ft1",
        domains=["agency", "studio", "designer", "photographer"],
        description="Filterable cards of projects. Studio or designer homepages where the work is the product.",
    ),
    "map_diagram": Macrostructure(
        name="Map / Diagram",
        slug="map_diagram",
        heading="overlap",
        body="asymmetric",
        divider="bleed-color",
        button="outlined",
        image="full-bleed",
        reveal="horizontal",
        nav_default="N1b",
        footer_default="Ft3",
        domains=["infra", "platform", "network", "system"],
        description="A single large spatial diagram organises the page — flowchart, floor plan, network graph.",
    ),
    "ecosystem_index": Macrostructure(
        name="Ecosystem Index",
        slug="ecosystem_index",
        heading="hanging",
        body="three-equal",
        divider="negative",
        button="outlined",
        image="tight-crop",
        reveal="fade-up",
        nav_default="N11",
        footer_default="Ft3",
        domains=["platform", "community", "marketplace", "directory"],
        description="Multiple discovery surfaces — featured / latest / by category / by people.",
    ),
    "component_playground": Macrostructure(
        name="Component Playground",
        slug="component_playground",
        heading="sticky",
        body="three-equal",
        divider="hairline",
        button="outlined",
        image="none",
        reveal="fade-up",
        nav_default="N13",
        footer_default="Ft3",
        domains=["docs", "design-system", "library", "open-source"],
        description="Interactive code-and-preview blocks are the page's primary content.",
    ),
}

# Quick-lookup alias
ALL_MACROSTRUCTURE_SLUGS: list[str] = list(MACROSTRUCTURES.keys())
