"""
Theme Catalog — 20 named themes + custom branch.
================================================
Author: Georgios-Chrysovalantis Chatzivantsidis

Each theme is a complete design system: OKLCH palette, font stack, signature moves,
motion direction, macrostructure affinities/rejections, voice fixtures, anti-patterns.

Source: Hallmark design skill (references/themes/*.md)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from orchestrator.models import Genre


@dataclass(frozen=True)
class Theme:
    """A named design theme — complete visual system."""

    name: str
    slug: str
    genre: Genre
    paper_oklch: str
    ink_oklch: str
    accent_oklch: str
    accent_ink_oklch: str
    font_display: str
    font_body: str
    font_mono: str
    signature_moves: list[str] = field(default_factory=list)
    motion_stance: Literal["motion-on", "motion-cut"] = "motion-cut"
    macrostructure_loves: list[str] = field(default_factory=list)
    macrostructure_rejects: list[str] = field(default_factory=list)
    voice_fixtures: list[str] = field(default_factory=list)
    anti_patterns: list[str] = field(default_factory=list)
    description: str = ""


# ═══════════════════════════════════════════════════════════════════════════════
# The 20 catalog themes
# ═══════════════════════════════════════════════════════════════════════════════

THEMES: dict[str, Theme] = {
    "cobalt": Theme(
        name="Cobalt",
        slug="cobalt",
        genre=Genre.MODERN_MINIMAL,
        paper_oklch="oklch(98.5% 0.004 250)",
        ink_oklch="oklch(24% 0.02 258)",
        accent_oklch="oklch(58% 0.20 256)",
        accent_ink_oklch="oklch(98% 0.005 250)",
        font_display="Space Grotesk",
        font_body="Inter",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Cool engineered paper, never #fff",
            "Hairlines do the work — no boxed cards, no drop-shadows",
            "One cobalt signal, used sparingly (<5% viewport)",
            "Code is the hero — dark graphite card with syntax tokens",
            "Bordered nav + working ⌘K palette",
            "Tight technical radii — 6px buttons, 10px code cards",
            "Mono labels — eyebrows, meta, status in JetBrains Mono UPPERCASE",
            "One dark graphite band per page — light→dark→light rhythm",
        ],
        motion_stance="motion-cut",
        macrostructure_loves=["workbench", "saas_api", "dev_tool", "docs_home", "marquee"],
        macrostructure_rejects=["letter", "manifesto", "photographic", "long_document"],
        voice_fixtures=[
            "Declarative, technical, specific. Name the X concretely.",
            "No hype adjectives: seamless, robust, cutting-edge, leverage, synergy.",
        ],
        anti_patterns=[
            "No orange accent",
            "No warm paper",
            "No pure #fff / #000",
            "No pill / gradient CTAs",
            "No centred-everything hero",
            "No three-equal-icon-tile feature grid",
            "No glassmorphism, no gradient text, no aurora/mesh blob",
        ],
        description="Modern-minimal, dev-tool register. Cool cobalt-on-light, code as hero.",
    ),
    "hum": Theme(
        name="Hum",
        slug="hum",
        genre=Genre.PLAYFUL,
        paper_oklch="oklch(97% 0.012 95)",
        ink_oklch="oklch(20% 0.012 250)",
        accent_oklch="oklch(86% 0.18 95)",
        accent_ink_oklch="oklch(20% 0.012 250)",
        font_display="Plus Jakarta Sans",
        font_body="Plus Jakarta Sans",
        font_mono="JetBrains Mono",
        signature_moves=[
            "The button system — three variations, the press is the feedback",
            "Multi-accent section bands — pear, cyan, coral each own surfaces",
            "Color-shift card grid — tint deepens on hover, card lifts 4px",
            "Streak / counter tick-up — big rounded numerals count on view-enter",
            "Character moment — one small reacting mark (CSS-only, no Lottie)",
            "Big rounded everything — 20px cards, 999px pills, 12px inputs",
            "Star-burst micro-celebration on success — coral-red, 420ms",
        ],
        motion_stance="motion-on",
        macrostructure_loves=["marquee_hero", "bento_grid", "workbench", "stat_led", "catalogue", "narrative_workflow"],
        macrostructure_rejects=["long_document", "manifesto", "quote_led", "type_specimen", "photographic"],
        voice_fixtures=[
            "Playful, vibrant, alive. The room is warm and someone smart is smiling.",
        ],
        anti_patterns=[
            "No serif anywhere",
            "No gradient between accents",
            "No square corners",
            "No generic spinners — use skeletal loaders",
        ],
        description="Playful, vibrant, alive. Cream paper, multi-accent, rounded sans, generous motion.",
    ),
    "lumen": Theme(
        name="Lumen",
        slug="lumen",
        genre=Genre.ATMOSPHERIC,
        paper_oklch="oklch(18% 0.02 260)",
        ink_oklch="oklch(92% 0.01 260)",
        accent_oklch="oklch(70% 0.15 85)",
        accent_ink_oklch="oklch(18% 0.02 260)",
        font_display="Instrument Serif",
        font_body="Inter",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Dark apparatus page — emit/refract focal artefact",
            "Instrument Serif display + Inter body",
            "Brass accent on dark canvas",
            "Subtle radial blooms — up to 20% canvas, fixed-attached, no animation",
        ],
        motion_stance="motion-cut",
        macrostructure_loves=["marquee_hero", "workbench", "specimen", "quote_led"],
        macrostructure_rejects=["bento_grid", "catalogue", "component_playground"],
        voice_fixtures=["Quiet confidence. The page whispers instead of shouting."],
        anti_patterns=["No bright backgrounds", "No saturated gradients on text"],
        description="Atmospheric dark theme. Apparatus aesthetic — emit, refract, glow.",
    ),
    "coral": Theme(
        name="Coral",
        slug="coral",
        genre=Genre.MODERN_MINIMAL,
        paper_oklch="oklch(96% 0.01 30)",
        ink_oklch="oklch(22% 0.02 30)",
        accent_oklch="oklch(65% 0.20 30)",
        accent_ink_oklch="oklch(96% 0.01 30)",
        font_display="Geist",
        font_body="Geist",
        font_mono="Geist Mono",
        signature_moves=[
            "Warm-grey paper + warm coral accent + Geist",
            "Soft pill buttons — full radius, gentle",
            "Quiet title/lede hero — understated confidence",
        ],
        motion_stance="motion-cut",
        macrostructure_loves=["bento_grid", "marquee_hero", "workbench", "saas_api"],
        macrostructure_rejects=["manifesto", "terminal", "letter"],
        voice_fixtures=["Warm, approachable, human."],
        anti_patterns=["No cool greys", "No sharp corners"],
        description="Warm modern-minimal. Warm-grey paper, coral accent, Geist typography.",
    ),
    "midnight": Theme(
        name="Midnight",
        slug="midnight",
        genre=Genre.ATMOSPHERIC,
        paper_oklch="oklch(15% 0.02 250)",
        ink_oklch="oklch(88% 0.01 250)",
        accent_oklch="oklch(60% 0.15 270)",
        accent_ink_oklch="oklch(15% 0.02 250)",
        font_display="Newsreader",
        font_body="Inter",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Dark canvas near hue 250 — dusky indigo",
            "Newsreader display + Inter body",
            "Typewriter reveal — character by character",
            "Numbered display headings — procedural, sequenced",
        ],
        motion_stance="motion-on",
        macrostructure_loves=["long_document", "specimen", "manifesto", "index_first"],
        macrostructure_rejects=["bento_grid", "workbench", "photographic"],
        voice_fixtures=["Nocturnal, literary, precise."],
        anti_patterns=["No bright accents", "No bounce animations"],
        description="Dark atmospheric. Dusky indigo, Newsreader, typewriter reveals.",
    ),
    "brutal": Theme(
        name="Brutal",
        slug="brutal",
        genre=Genre.PLAYFUL,
        paper_oklch="oklch(95% 0.005 100)",
        ink_oklch="oklch(15% 0.01 100)",
        accent_oklch="oklch(55% 0.20 25)",
        accent_ink_oklch="oklch(95% 0.005 100)",
        font_display="Space Grotesk",
        font_body="Space Grotesk",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Raw borders — 2px solid, no blur, no shadow",
            "Asymmetric layout — intentional imbalance",
            "High contrast — ink on paper, no middle greys",
            "Oversized solid CTAs — big blocks of accent",
        ],
        motion_stance="motion-cut",
        macrostructure_loves=["manifesto", "bento_grid", "photographic", "stat_led"],
        macrostructure_rejects=["letter", "conversational_faq", "component_playground"],
        voice_fixtures=["Direct, uncompromising, loud."],
        anti_patterns=["No rounded corners", "No gradients", "No shadows"],
        description="Swiss brutalist. Raw borders, asymmetric, high contrast, no decoration.",
    ),
    "editorial": Theme(
        name="Editorial",
        slug="editorial",
        genre=Genre.EDITORIAL,
        paper_oklch="oklch(97% 0.005 50)",
        ink_oklch="oklch(20% 0.02 50)",
        accent_oklch="oklch(55% 0.15 25)",
        accent_ink_oklch="oklch(97% 0.005 50)",
        font_display="Playfair Display",
        font_body="Source Serif 4",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Serif display + serif body — editorial voice",
            "Hanging headings — float in negative space above section",
            "Hairline rules — 0.5px, inset or full-bleed",
            "Tightly cropped images — deliberate, sized to grid",
        ],
        motion_stance="motion-cut",
        macrostructure_loves=["specimen", "long_document", "type_specimen", "portfolio_grid"],
        macrostructure_rejects=["bento_grid", "workbench", "component_playground"],
        voice_fixtures=["Literary, measured, authoritative."],
        anti_patterns=["No sans-serif as display", "No centred-everything"],
        description="Editorial / magazine. Serif typography, hanging headings, hairlines.",
    ),
    "terminal": Theme(
        name="Terminal",
        slug="terminal",
        genre=Genre.TERMINAL,
        paper_oklch="oklch(15% 0.01 145)",
        ink_oklch="oklch(80% 0.05 145)",
        accent_oklch="oklch(70% 0.15 145)",
        accent_ink_oklch="oklch(15% 0.01 145)",
        font_display="JetBrains Mono",
        font_body="JetBrains Mono",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Monospace everything — display, body, labels",
            "CLI prompt nav — > studio --catalog --voice --get▮",
            "Typewriter reveal — honest about the medium",
            "Green-on-black or amber-on-black — terminal palette",
        ],
        motion_stance="motion-on",
        macrostructure_loves=["workbench", "component_playground", "long_document", "index_first"],
        macrostructure_rejects=["photographic", "quote_led", "letter"],
        voice_fixtures=["Technical, direct, unadorned."],
        anti_patterns=[
            "No sans-serif fonts",
            "No decorative graphics without semantic anchor",
            "No scanlines or detached cursors as decoration",
        ],
        description="Terminal / CLI aesthetic. Monospace, green-on-black, CLI prompts.",
    ),
    "aurora": Theme(
        name="Aurora",
        slug="aurora",
        genre=Genre.ATMOSPHERIC,
        paper_oklch="oklch(12% 0.02 200)",
        ink_oklch="oklch(90% 0.01 200)",
        accent_oklch="oklch(70% 0.18 200)",
        accent_ink_oklch="oklch(12% 0.02 200)",
        font_display="Sentient",
        font_body="Sentient",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Dark cyan canvas — atmospheric blooms",
            "Sentient serif body — elegant, flowing",
            "Radial gradient backgrounds — subtle, fixed",
            "Floating pill nav — blur backdrop sells the mood",
        ],
        motion_stance="motion-on",
        macrostructure_loves=["marquee_hero", "quote_led", "photographic", "manifesto"],
        macrostructure_rejects=["bento_grid", "workbench", "catalogue"],
        voice_fixtures=["Ethereal, contemplative, vast."],
        anti_patterns=["No bright backgrounds", "No hard edges"],
        description="Dark atmospheric with cyan blooms. Sentient serif, radial gradients.",
    ),
    "garden": Theme(
        name="Garden",
        slug="garden",
        genre=Genre.EDITORIAL,
        paper_oklch="oklch(96% 0.02 120)",
        ink_oklch="oklch(22% 0.02 120)",
        accent_oklch="oklch(60% 0.20 140)",
        accent_ink_oklch="oklch(96% 0.02 120)",
        font_display="Cormorant Garamond",
        font_body="Source Serif 4",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Warm green-tinted paper — nature palette",
            "Serif display + serif body — classic editorial",
            "Marginalia layout — sidenotes in generous outer margin",
            "Ornament dividers — fleuron, centered dot",
        ],
        motion_stance="motion-cut",
        macrostructure_loves=["long_document", "letter", "portfolio_grid", "catalogue"],
        macrostructure_rejects=["terminal", "manifesto", "workbench"],
        voice_fixtures=["Organic, cultivated, timeless."],
        anti_patterns=["No sans-serif as display", "No geometric shapes"],
        description="Editorial nature theme. Green-tinted paper, serif, marginalia, ornaments.",
    ),
    "newsprint": Theme(
        name="Newsprint",
        slug="newsprint",
        genre=Genre.EDITORIAL,
        paper_oklch="oklch(94% 0.01 80)",
        ink_oklch="oklch(18% 0.02 80)",
        accent_oklch="oklch(55% 0.15 30)",
        accent_ink_oklch="oklch(94% 0.01 80)",
        font_display="Newsreader",
        font_body="Newsreader",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Multi-column justified body — newspaper rhythm",
            "Bottom-aligned headings — masthead-below pattern",
            "Double-rule dividers — top + bottom line tight together",
            "Newspaper masthead nav — large centred wordmark",
        ],
        motion_stance="motion-cut",
        macrostructure_loves=["long_document", "index_first", "specimen", "catalogue"],
        macrostructure_rejects=["bento_grid", "workbench", "feature_stack"],
        voice_fixtures=["Journalistic, urgent, credible."],
        anti_patterns=["No sans-serif", "No single-column body"],
        description="Newspaper editorial. Multi-column justified, Newsreader, masthead nav.",
    ),
    "atelier": Theme(
        name="Atelier",
        slug="atelier",
        genre=Genre.EDITORIAL,
        paper_oklch="oklch(95% 0.01 60)",
        ink_oklch="oklch(20% 0.02 60)",
        accent_oklch="oklch(55% 0.15 40)",
        accent_ink_oklch="oklch(95% 0.01 60)",
        font_display="Playfair Display",
        font_body="Inter",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Studio / atelier aesthetic — craft, process, making",
            "Serif display + sans body — contrast of tradition and modern",
            "Tightly cropped images — still-life compositions",
            "Typographic-only CTAs — no boxes, just words",
        ],
        motion_stance="motion-cut",
        macrostructure_loves=["portfolio_grid", "split_studio", "specimen", "type_specimen"],
        macrostructure_rejects=["terminal", "bento_grid", "component_playground"],
        voice_fixtures=["Artisanal, deliberate, process-forward."],
        anti_patterns=["No generic stock photography", "No bright neons"],
        description="Studio / atelier. Craft aesthetic, serif+sans, still-life imagery.",
    ),
    "carnival": Theme(
        name="Carnival",
        slug="carnival",
        genre=Genre.PLAYFUL,
        paper_oklch="oklch(96% 0.03 60)",
        ink_oklch="oklch(18% 0.03 60)",
        accent_oklch="oklch(65% 0.25 45)",
        accent_ink_oklch="oklch(96% 0.03 60)",
        font_display="Anton",
        font_body="Inter",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Bold, loud, energetic — circus / festival energy",
            "Condensed display (Anton) + clean sans body",
            "Bright warm accent — orange, red, yellow",
            "Diagonal compositions —打破 symmetry deliberately",
        ],
        motion_stance="motion-on",
        macrostructure_loves=["manifesto", "stat_led", "marquee_hero", "photographic"],
        macrostructure_rejects=["long_document", "letter", "conversational_faq"],
        voice_fixtures=["Bold, celebratory, impossible to ignore."],
        anti_patterns=["No muted colours", "No small type"],
        description="Playful festival energy. Bold condensed display, bright warm accents.",
    ),
    "bloom": Theme(
        name="Bloom",
        slug="bloom",
        genre=Genre.ATMOSPHERIC,
        paper_oklch="oklch(96% 0.02 30)",
        ink_oklch="oklch(22% 0.02 30)",
        accent_oklch="oklch(60% 0.18 25)",
        accent_ink_oklch="oklch(96% 0.02 30)",
        font_display="Instrument Serif",
        font_body="Inter",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Warm-light atmospheric — terracotta, peach, blush",
            "Instrument Serif display + Inter body",
            "Soft radial blooms — warm-toned, fixed-attached",
            "Floating pill nav — gentle, contemporary",
        ],
        motion_stance="motion-cut",
        macrostructure_loves=["marquee_hero", "quote_led", "photographic", "letter"],
        macrostructure_rejects=["terminal", "workbench", "component_playground"],
        voice_fixtures=["Warm, inviting, blooming."],
        anti_patterns=["No cool greys", "No sharp edges"],
        description="Warm atmospheric. Terracotta blooms, Instrument Serif, floating nav.",
    ),
    "sport": Theme(
        name="Sport",
        slug="sport",
        genre=Genre.PLAYFUL,
        paper_oklch="oklch(15% 0.02 250)",
        ink_oklch="oklch(92% 0.01 250)",
        accent_oklch="oklch(70% 0.20 30)",
        accent_ink_oklch="oklch(15% 0.02 250)",
        font_display="Anton",
        font_body="Inter",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Dark athletic energy — bold, dynamic, high contrast",
            "Condensed display (Anton) + clean sans body",
            "Oversized solid CTAs — statement buttons",
            "Horizontal sweep reveals — directional momentum",
        ],
        motion_stance="motion-on",
        macrostructure_loves=["manifesto", "stat_led", "marquee_hero", "photographic"],
        macrostructure_rejects=["letter", "conversational_faq", "long_document"],
        voice_fixtures=["Aggressive, confident, unstoppable."],
        anti_patterns=["No thin weights", "No pastel colours"],
        description="Dark athletic. Anton display, high contrast, bold motion.",
    ),
    "studio": Theme(
        name="Studio",
        slug="studio",
        genre=Genre.EDITORIAL,
        paper_oklch="oklch(95% 0.01 250)",
        ink_oklch="oklch(20% 0.02 250)",
        accent_oklch="oklch(55% 0.15 270)",
        accent_ink_oklch="oklch(95% 0.01 250)",
        font_display="Space Grotesk",
        font_body="Inter",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Design studio aesthetic — refined, intentional",
            "Space Grotesk display + Inter body",
            "Asymmetric spans — intentional imbalance",
            "Typographic-only CTAs — elegant restraint",
        ],
        motion_stance="motion-cut",
        macrostructure_loves=["portfolio_grid", "split_studio", "specimen", "index_first"],
        macrostructure_rejects=["terminal", "bento_grid", "component_playground"],
        voice_fixtures=["Refined, intentional, gallery-quality."],
        anti_patterns=["No generic templates", "No clutter"],
        description="Design studio. Refined, asymmetric, Space Grotesk, typographic CTAs.",
    ),
    "riso": Theme(
        name="Riso",
        slug="riso",
        genre=Genre.PLAYFUL,
        paper_oklch="oklch(95% 0.03 80)",
        ink_oklch="oklch(20% 0.03 80)",
        accent_oklch="oklch(70% 0.25 120)",
        accent_ink_oklch="oklch(95% 0.03 80)",
        font_display="Space Grotesk",
        font_body="Inter",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Risograph print aesthetic — misregistration, layering, texture",
            "Space Grotesk display + Inter body",
            "Bright neon accent on warm paper — riso ink colours",
            "Brutal slab nav — heavy, full-width, 2px border",
        ],
        motion_stance="motion-cut",
        macrostructure_loves=["manifesto", "bento_grid", "photographic", "stat_led"],
        macrostructure_rejects=["letter", "conversational_faq", "long_document"],
        voice_fixtures=["DIY, underground, textured."],
        anti_patterns=["No smooth gradients", "No corporate polish"],
        description="Risograph print aesthetic. Misregistration, neon accents, brutal nav.",
    ),
    "almanac": Theme(
        name="Almanac",
        slug="almanac",
        genre=Genre.EDITORIAL,
        paper_oklch="oklch(94% 0.02 90)",
        ink_oklch="oklch(18% 0.02 90)",
        accent_oklch="oklch(55% 0.15 90)",
        accent_ink_oklch="oklch(94% 0.02 90)",
        font_display="Newsreader",
        font_body="Newsreader",
        font_mono="JetBrains Mono",
        signature_moves=[
            "Reference / almanac aesthetic — data-dense, scholarly",
            "Newsreader throughout — serif display + serif body",
            "Tabular numerics — font-variant-numeric: tabular-nums",
            "Sticky pinned section heads — orientation aid",
        ],
        motion_stance="motion-cut",
        macrostructure_loves=["catalogue", "long_document", "index_first", "component_playground"],
        macrostructure_rejects=["photographic", "quote_led", "marquee_hero"],
        voice_fixtures=["Scholarly, precise, reference-grade."],
        anti_patterns=["No sans-serif", "No proportional numerics"],
        description="Scholarly almanac. Newsreader, tabular nums, sticky heads, data-dense.",
    ),
}
