"""
Testing Templates Generator — Prototype + Factory Pattern
==========================================================
Author: Georgios-Chrysovalantis Chatzivantsidis

Testing template generation using Prototype Pattern for cloning test templates
and Factory Pattern for different test types.

Paradigm: OOP with Functional utilities
Patterns: Prototype, Factory Method, Builder, Template Method

Usage:
    from orchestrator.testing_templates import TestTemplateFactory

    factory = TestTemplateFactory()
    unit_test = factory.create_unit_test("MyComponent", framework="jest")
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict
from enum import Enum
import copy

# ═══════════════════════════════════════════════════════════════════
# IMMUTABLE DATA CLASSES
# ═══════════════════════════════════════════════════════════════════


class TestFramework(str, Enum):
    """Test framework enumeration."""

    JEST = "jest"
    VITEST = "vitest"
    PYTEST = "pytest"
    UNITTEST = "unittest"
    MOCHA = "mocha"
    JASMINE = "jasmine"


class TestType(str, Enum):
    """Test type enumeration."""

    UNIT = "unit"
    INTEGRATION = "integration"
    E2E = "e2e"
    COMPONENT = "component"
    SNAPSHOT = "snapshot"


@dataclass(frozen=True)
class TestConfig:
    """
    Immutable test configuration.

    Attributes:
        framework: Test framework
        test_type: Type of test
        coverage_threshold: Minimum coverage percentage
        timeout: Test timeout in ms
        retries: Number of retries
        parallel: Run tests in parallel
    """

    framework: TestFramework = TestFramework.JEST
    test_type: TestType = TestType.UNIT
    coverage_threshold: float = 80.0
    timeout: int = 5000
    retries: int = 0
    parallel: bool = True


@dataclass
class TestTemplate:
    """
    Test template prototype.

    Attributes:
        name: Test name
        framework: Test framework
        test_type: Test type
        template: Test template string
        imports: Required imports
        dependencies: Test dependencies
    """

    name: str
    framework: TestFramework
    test_type: TestType
    template: str
    imports: List[str] = field(default_factory=list)
    dependencies: List[str] = field(default_factory=list)

    def clone(self) -> "TestTemplate":
        """Clone template (Prototype pattern)."""
        return copy.deepcopy(self)

    def customize(self, **kwargs) -> "TestTemplate":
        """Customize cloned template."""
        cloned = self.clone()
        for key, value in kwargs.items():
            if hasattr(cloned, key):
                setattr(cloned, key, value)
        return cloned


# ═══════════════════════════════════════════════════════════════════
# PROTOTYPE PATTERN — TEST TEMPLATE PROTOTYPES
# ═══════════════════════════════════════════════════════════════════


class TestTemplatePrototype(ABC):
    """
    Abstract base for test template prototypes.

    Subclasses implement specific test template types.
    """

    @abstractmethod
    def create_template(self, name: str, config: TestConfig) -> TestTemplate:
        """
        Create test template.

        Args:
            name: Test name
            config: Test configuration

        Returns:
            TestTemplate
        """
        pass


class JestUnitTestPrototype(TestTemplatePrototype):
    """
    Jest unit test template prototype.
    """

    def create_template(self, name: str, config: TestConfig) -> TestTemplate:
        """Create Jest unit test template."""
        template = f"""/**
 * Tests for {name}
 * @generated by AI Orchestrator
 */

import {{ describe, it, expect }} from '@jest/globals';

describe('{name}', () => {{
  describe('constructor', () => {{
    it('should create an instance', () => {{
      // TODO: Implement test
      expect(true).toBe(true);
    }});
  }});

  describe('basic functionality', () => {{
    it('should work as expected', () => {{
      // TODO: Implement test
      expect(true).toBe(true);
    }});
  }});
}});
"""

        return TestTemplate(
            name=name,
            framework=TestFramework.JEST,
            test_type=TestType.UNIT,
            template=template,
            imports=["@jest/globals"],
            dependencies=["jest", "@testing-library/jest-dom"],
        )


class VitestUnitTestPrototype(TestTemplatePrototype):
    """
    Vitest unit test template prototype.
    """

    def create_template(self, name: str, config: TestConfig) -> TestTemplate:
        """Create Vitest unit test template."""
        template = f"""/**
 * Tests for {name}
 * @generated by AI Orchestrator
 */

import {{ describe, it, expect }} from 'vitest';

describe('{name}', () => {{
  describe('constructor', () => {{
    it('should create an instance', () => {{
      // TODO: Implement test
      expect(true).toBe(true);
    }});
  }});

  describe('basic functionality', () => {{
    it('should work as expected', () => {{
      // TODO: Implement test
      expect(true).toBe(true);
    }});
  }});
}});
"""

        return TestTemplate(
            name=name,
            framework=TestFramework.VITEST,
            test_type=TestType.UNIT,
            template=template,
            imports=["vitest"],
            dependencies=["vitest"],
        )


class PytestUnitTestPrototype(TestTemplatePrototype):
    """
    Pytest unit test template prototype.
    """

    def create_template(self, name: str, config: TestConfig) -> TestTemplate:
        """Create Pytest unit test template."""
        template = f'''"""
Tests for {name}
Generated by AI Orchestrator
"""

import pytest


class Test{name.replace("_", "")}:
    """Test suite for {name}."""

    def test_constructor(self):
        """Test that instance is created."""
        # TODO: Implement test
        assert True

    def test_basic_functionality(self):
        """Test basic functionality."""
        # TODO: Implement test
        assert True
'''

        return TestTemplate(
            name=name,
            framework=TestFramework.PYTEST,
            test_type=TestType.UNIT,
            template=template,
            imports=["pytest"],
            dependencies=["pytest", "pytest-cov", "pytest-mock"],
        )


class ReactComponentTestPrototype(TestTemplatePrototype):
    """
    React component test template prototype.
    """

    def create_template(self, name: str, config: TestConfig) -> TestTemplate:
        """Create React component test template."""
        template = f"""/**
 * Tests for {name} component
 * @generated by AI Orchestrator
 */

import {{ render, screen, fireEvent }} from '@testing-library/react';
import {name} from '../{name}';

describe('{name}', () => {{
  describe('rendering', () => {{
    it('should render correctly', () => {{
      render(<{name} />);
      expect(screen.getByText('{name}')).toBeInTheDocument();
    }});

    it('should handle props', () => {{
      render(<{name} title="Test Title" />);
      expect(screen.getByText('Test Title')).toBeInTheDocument();
    }});
  }});

  describe('interactions', () => {{
    it('should handle click events', () => {{
      const handleClick = jest.fn();
      render(<{name} onClick={{handleClick}} />);
      
      fireEvent.click(screen.getByRole('button'));
      expect(handleClick).toHaveBeenCalledTimes(1);
    }});
  }});
}});
"""

        return TestTemplate(
            name=name,
            framework=TestFramework.JEST,
            test_type=TestType.COMPONENT,
            template=template,
            imports=["@testing-library/react", "@testing-library/jest-dom"],
            dependencies=["@testing-library/react", "@testing-library/jest-dom", "jest"],
        )


class E2ETestPrototype(TestTemplatePrototype):
    """
    E2E test template prototype (Playwright).
    """

    def create_template(self, name: str, config: TestConfig) -> TestTemplate:
        """Create E2E test template."""
        template = f"""/**
 * E2E Tests for {name}
 * @generated by AI Orchestrator
 */

import {{ test, expect }} from '@playwright/test';

test.describe('{name} E2E Tests', () => {{
  test.beforeEach(async ({{ page }}) => {{
    // Navigate to page before each test
    await page.goto('/');
  }});

  test('should load page successfully', async ({{ page }}) => {{
    await expect(page).toHaveTitle(/.*/);
  }});

  test('should display main content', async ({{ page }}) => {{
    await expect(page.locator('main')).toBeVisible();
  }});

  test('should be responsive on mobile', async ({{ page }}) => {{
    await page.setViewportSize({{ width: 375, height: 667 }});
    await expect(page.locator('main')).toBeVisible();
  }});
}});
"""

        return TestTemplate(
            name=name,
            framework=TestFramework.JEST,
            test_type=TestType.E2E,
            template=template,
            imports=["@playwright/test"],
            dependencies=["@playwright/test"],
        )


class SnapshotTestPrototype(TestTemplatePrototype):
    """
    Snapshot test template prototype.
    """

    def create_template(self, name: str, config: TestConfig) -> TestTemplate:
        """Create snapshot test template."""
        template = f"""/**
 * Snapshot Tests for {name}
 * @generated by AI Orchestrator
 */

import {{ render }} from '@testing-library/react';
import {name} from '../{name}';

describe('{name} Snapshot Tests', () => {{
  it('should match snapshot', () => {{
    const {{ container }} = render(<{name} />);
    expect(container).toMatchSnapshot();
  }});

  it('should match snapshot with props', () => {{
    const {{ container }} = render(<{name} title="Test" />);
    expect(container).toMatchSnapshot();
  }});
}});
"""

        return TestTemplate(
            name=name,
            framework=TestFramework.JEST,
            test_type=TestType.SNAPSHOT,
            template=template,
            imports=["@testing-library/react"],
            dependencies=["@testing-library/react", "jest"],
        )


# ═══════════════════════════════════════════════════════════════════
# FACTORY PATTERN — TEST TEMPLATE FACTORY
# ═══════════════════════════════════════════════════════════════════


class TestTemplateFactory:
    """
    Factory Method for test templates.

    Usage:
        factory = TestTemplateFactory()
        unit_test = factory.create_unit_test("MyComponent")
        component_test = factory.create_component_test("MyComponent")
    """

    def __init__(self):
        """Initialize factory with prototypes."""
        self._prototypes: Dict[str, TestTemplatePrototype] = {
            "jest_unit": JestUnitTestPrototype(),
            "vitest_unit": VitestUnitTestPrototype(),
            "pytest_unit": PytestUnitTestPrototype(),
            "react_component": ReactComponentTestPrototype(),
            "e2e": E2ETestPrototype(),
            "snapshot": SnapshotTestPrototype(),
        }

    def create_unit_test(
        self,
        name: str,
        framework: str = "jest",
        config: TestConfig = None,
    ) -> TestTemplate:
        """
        Create unit test template.

        Args:
            name: Component/function name
            framework: Test framework
            config: Test configuration

        Returns:
            TestTemplate
        """
        key = f"{framework}_unit"
        prototype = self._prototypes.get(key, self._prototypes["jest_unit"])

        if config is None:
            config = TestConfig(framework=TestFramework(framework))

        return prototype.create_template(name, config)

    def create_component_test(
        self,
        name: str,
        framework: str = "jest",
        config: TestConfig = None,
    ) -> TestTemplate:
        """
        Create component test template.

        Args:
            name: Component name
            framework: Test framework
            config: Test configuration

        Returns:
            TestTemplate
        """
        if framework == "jest":
            prototype = self._prototypes["react_component"]
        else:
            prototype = self._prototypes["jest_unit"]

        if config is None:
            config = TestConfig(test_type=TestType.COMPONENT)

        return prototype.create_template(name, config)

    def create_e2e_test(
        self,
        name: str,
        config: TestConfig = None,
    ) -> TestTemplate:
        """
        Create E2E test template.

        Args:
            name: Page/feature name
            config: Test configuration

        Returns:
            TestTemplate
        """
        prototype = self._prototypes["e2e"]

        if config is None:
            config = TestConfig(test_type=TestType.E2E)

        return prototype.create_template(name, config)

    def create_snapshot_test(
        self,
        name: str,
        config: TestConfig = None,
    ) -> TestTemplate:
        """
        Create snapshot test template.

        Args:
            name: Component name
            config: Test configuration

        Returns:
            TestTemplate
        """
        prototype = self._prototypes["snapshot"]

        if config is None:
            config = TestConfig(test_type=TestType.SNAPSHOT)

        return prototype.create_template(name, config)

    def create_custom_test(
        self,
        prototype_key: str,
        name: str,
        config: TestConfig = None,
    ) -> TestTemplate:
        """
        Create custom test from prototype key.

        Args:
            prototype_key: Prototype registry key
            name: Test name
            config: Test configuration

        Returns:
            TestTemplate
        """
        prototype = self._prototypes.get(prototype_key)

        if not prototype:
            raise ValueError(f"Unknown prototype: {prototype_key}")

        if config is None:
            config = TestConfig()

        return prototype.create_template(name, config)

    def register_prototype(
        self,
        key: str,
        prototype: TestTemplatePrototype,
    ) -> None:
        """
        Register custom prototype.

        Args:
            key: Prototype key
            prototype: Prototype instance
        """
        self._prototypes[key] = prototype


# ═══════════════════════════════════════════════════════════════════
# TEST CONFIGURATION GENERATOR
# ═══════════════════════════════════════════════════════════════════


class TestConfigGenerator:
    """
    Generator for test configuration files.
    """

    @staticmethod
    def generate_jest_config(coverage_threshold: float = 80.0) -> str:
        """Generate Jest configuration."""
        return f"""/**
 * Jest Configuration
 * @generated by AI Orchestrator
 */

module.exports = {{
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.+(ts|tsx|js)', '**/?(*.)+(spec|test).+(ts|tsx|js)'],
  transform: {{
    '^.+\\\\.(ts|tsx)$': 'ts-jest',
  }},
  collectCoverageFrom: [
    'src/**/*.(ts|tsx)',
    '!src/**/*.d.ts',
    '!src/**/*.stories.tsx',
  ],
  coverageThreshold: {{
    global: {{
      branches: {coverage_threshold},
      functions: {coverage_threshold},
      lines: {coverage_threshold},
      statements: {coverage_threshold},
    }},
  }},
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
  moduleNameMapper: {{
    '^@/(.*)$': '<rootDir>/src/$1',
  }},
}};
"""

    @staticmethod
    def generate_vitest_config(coverage_threshold: float = 80.0) -> str:
        """Generate Vitest configuration."""
        return f"""/**
 * Vitest Configuration
 * @generated by AI Orchestrator
 */

import {{ defineConfig }} from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({{
  plugins: [react()],
  test: {{
    globals: true,
    environment: 'jsdom',
    setupFiles: './src/setupTests.ts',
    coverage: {{
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      threshold: {{
        lines: {coverage_threshold},
        functions: {coverage_threshold},
        branches: {coverage_threshold},
        statements: {coverage_threshold},
      }},
    }},
  }},
}});
"""

    @staticmethod
    def generate_pytest_config(coverage_threshold: float = 80.0) -> str:
        """Generate Pytest configuration."""
        return f'''"""
Pytest Configuration
Generated by AI Orchestrator
"""

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-v",
    "--cov=src",
    "--cov-report=term-missing",
    "--cov-report=html",
    f"--cov-fail-under={coverage_threshold}",
    "--strict-markers",
    "--strict-config",
    "--tb=short",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "e2e: marks tests as end-to-end tests",
]
'''

    @staticmethod
    def generate_playwright_config() -> str:
        """Generate Playwright configuration."""
        return """/**
 * Playwright Configuration
 * @generated by AI Orchestrator
 */

import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
    },
    {
      name: 'Mobile Safari',
      use: { ...devices['iPhone 12'] },
    },
  ],
  webServer: {
    command: 'npm run dev',
    url: 'http://localhost:3000',
    reuseExistingServer: !process.env.CI,
  },
});
"""


# ═══════════════════════════════════════════════════════════════════
# CONVENIENCE FUNCTIONS
# ═══════════════════════════════════════════════════════════════════


def create_unit_test(
    name: str,
    framework: str = "jest",
    coverage_threshold: float = 80.0,
) -> TestTemplate:
    """
    Create unit test template.

    Args:
        name: Component/function name
        framework: Test framework
        coverage_threshold: Coverage threshold

    Returns:
        TestTemplate
    """
    factory = TestTemplateFactory()
    return factory.create_unit_test(name, framework)


def create_component_test(
    name: str,
    framework: str = "jest",
) -> TestTemplate:
    """
    Create component test template.

    Args:
        name: Component name
        framework: Test framework

    Returns:
        TestTemplate
    """
    factory = TestTemplateFactory()
    return factory.create_component_test(name, framework)


def create_e2e_test(name: str) -> TestTemplate:
    """
    Create E2E test template.

    Args:
        name: Page/feature name

    Returns:
        TestTemplate
    """
    factory = TestTemplateFactory()
    return factory.create_e2e_test(name)


def generate_jest_config(coverage_threshold: float = 80.0) -> str:
    """Generate Jest configuration."""
    return TestConfigGenerator.generate_jest_config(coverage_threshold)


def generate_vitest_config(coverage_threshold: float = 80.0) -> str:
    """Generate Vitest configuration."""
    return TestConfigGenerator.generate_vitest_config(coverage_threshold)


def generate_pytest_config(coverage_threshold: float = 80.0) -> str:
    """Generate Pytest configuration."""
    return TestConfigGenerator.generate_pytest_config(coverage_threshold)


def generate_playwright_config() -> str:
    """Generate Playwright configuration."""
    return TestConfigGenerator.generate_playwright_config()
