"""
Error Handling Generator — Strategy + Template Method Pattern
==============================================================
Author: Georgios-Chrysovalantis Chatzivantsidis

Error handling code generation using Strategy Pattern for different languages
and Template Method for error handling patterns.

Paradigm: OOP with Functional utilities
Patterns: Strategy, Template Method, Factory Method, Builder

Usage:
    from orchestrator.error_handling import ErrorHandlerGenerator

    generator = ErrorHandlerGenerator("typescript")
    error_handler = generator.generate_error_handler()
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List
from enum import Enum

# ═══════════════════════════════════════════════════════════════════
# IMMUTABLE DATA CLASSES
# ═══════════════════════════════════════════════════════════════════


class ErrorLevel(str, Enum):
    """Error severity level."""

    DEBUG = "debug"
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"
    FATAL = "fatal"


class ErrorType(str, Enum):
    """Error type enumeration."""

    VALIDATION = "validation"
    AUTHENTICATION = "authentication"
    AUTHORIZATION = "authorization"
    NOT_FOUND = "not_found"
    INTERNAL = "internal"
    TIMEOUT = "timeout"
    RATE_LIMIT = "rate_limit"
    NETWORK = "network"
    DATABASE = "database"


@dataclass(frozen=True)
class ErrorConfig:
    """
    Immutable error handling configuration.

    Attributes:
        language: Programming language
        include_stack_trace: Include stack traces
        include_error_codes: Include error codes
        custom_error_classes: Generate custom error classes
        retry_logic: Include retry logic
        circuit_breaker: Include circuit breaker
        fallback_handler: Include fallback handlers
    """

    language: str = "typescript"
    include_stack_trace: bool = True
    include_error_codes: bool = True
    custom_error_classes: bool = True
    retry_logic: bool = False
    circuit_breaker: bool = False
    fallback_handler: bool = False


@dataclass(frozen=True)
class ErrorHandler:
    """
    Immutable error handler result.

    Attributes:
        code: Generated error handler code
        language: Programming language
        error_types: List of error types
        includes_retry: Includes retry logic
        includes_circuit_breaker: Includes circuit breaker
    """

    code: str
    language: str
    error_types: List[ErrorType] = field(default_factory=list)
    includes_retry: bool = False
    includes_circuit_breaker: bool = False


# ═══════════════════════════════════════════════════════════════════
# STRATEGY PATTERN — ERROR HANDLER STRATEGIES
# ═══════════════════════════════════════════════════════════════════


class ErrorHandlerStrategy(ABC):
    """
    Strategy Pattern for error handler generation.

    Subclasses implement error handlers for different languages.
    """

    @abstractmethod
    def generate(self, config: ErrorConfig) -> ErrorHandler:
        """
        Generate error handler.

        Args:
            config: Error configuration

        Returns:
            ErrorHandler
        """
        pass

    @abstractmethod
    def get_language(self) -> str:
        """Get language name."""
        pass


class TypeScriptErrorHandlerStrategy(ErrorHandlerStrategy):
    """
    TypeScript error handler strategy.
    """

    def generate(self, config: ErrorConfig) -> ErrorHandler:
        """Generate TypeScript error handler."""
        code = """/**
 * Error Handler
 * Generated by AI Orchestrator
 */

// ═══════════════════════════════════════════════════════════════
// Custom Error Classes
// ═══════════════════════════════════════════════════════════════

export enum ErrorCode {
  VALIDATION = "VALIDATION_ERROR",
  AUTHENTICATION = "AUTHENTICATION_ERROR",
  AUTHORIZATION = "AUTHORIZATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL = "INTERNAL_ERROR",
  TIMEOUT = "TIMEOUT_ERROR",
  RATE_LIMIT = "RATE_LIMIT_ERROR",
  NETWORK = "NETWORK_ERROR",
  DATABASE = "DATABASE_ERROR",
}

export enum ErrorLevel {
  DEBUG = "debug",
  INFO = "info",
  WARNING = "warning",
  ERROR = "error",
  CRITICAL = "critical",
  FATAL = "fatal",
}

export interface ErrorMetadata {
  timestamp: string;
  path?: string;
  method?: string;
  userId?: string;
  requestId?: string;
  [key: string]: any;
}

export class AppError extends Error {
  public readonly code: ErrorCode;
  public readonly level: ErrorLevel;
  public readonly statusCode: number;
  public readonly metadata: ErrorMetadata;
  public readonly isOperational: boolean;

  constructor(
    message: string,
    code: ErrorCode = ErrorCode.INTERNAL,
    statusCode: number = 500,
    level: ErrorLevel = ErrorLevel.ERROR,
    isOperational: boolean = true,
  ) {
    super(message);
    this.name = this.constructor.name;
    this.code = code;
    this.level = level;
    this.statusCode = statusCode;
    this.isOperational = isOperational;
    this.metadata = {
      timestamp: new Date().toISOString(),
    };

    Error.captureStackTrace(this, this.constructor);
  }

  withMetadata(metadata: Partial<ErrorMetadata>): AppError {
    Object.assign(this.metadata, metadata);
    return this;
  }
}

// ═══════════════════════════════════════════════════════════════
// Specific Error Types
// ═══════════════════════════════════════════════════════════════

export class ValidationError extends AppError {
  constructor(message: string, metadata?: Partial<ErrorMetadata>) {
    super(message, ErrorCode.VALIDATION, 400, ErrorLevel.WARNING);
    if (metadata) this.withMetadata(metadata);
  }
}

export class AuthenticationError extends AppError {
  constructor(message: string = "Authentication required", metadata?: Partial<ErrorMetadata>) {
    super(message, ErrorCode.AUTHENTICATION, 401, ErrorLevel.WARNING);
    if (metadata) this.withMetadata(metadata);
  }
}

export class AuthorizationError extends AppError {
  constructor(message: string = "Access denied", metadata?: Partial<ErrorMetadata>) {
    super(message, ErrorCode.AUTHORIZATION, 403, ErrorLevel.WARNING);
    if (metadata) this.withMetadata(metadata);
  }
}

export class NotFoundError extends AppError {
  constructor(resource: string = "Resource", metadata?: Partial<ErrorMetadata>) {
    super(`${resource} not found`, ErrorCode.NOT_FOUND, 404, ErrorLevel.INFO);
    if (metadata) this.withMetadata(metadata);
  }
}

export class InternalError extends AppError {
  constructor(message: string = "Internal server error", metadata?: Partial<ErrorMetadata>) {
    super(message, ErrorCode.INTERNAL, 500, ErrorLevel.ERROR);
    if (metadata) this.withMetadata(metadata);
  }
}

export class TimeoutError extends AppError {
  constructor(message: string = "Request timeout", metadata?: Partial<ErrorMetadata>) {
    super(message, ErrorCode.TIMEOUT, 408, ErrorLevel.WARNING);
    if (metadata) this.withMetadata(metadata);
  }
}

export class RateLimitError extends AppError {
  constructor(message: string = "Too many requests", metadata?: Partial<ErrorMetadata>) {
    super(message, ErrorCode.RATE_LIMIT, 429, ErrorLevel.WARNING);
    if (metadata) this.withMetadata(metadata);
  }
}

// ═══════════════════════════════════════════════════════════════
// Error Handler
// ═══════════════════════════════════════════════════════════════

export interface ErrorHandlerOptions {
  logErrors: boolean;
  includeStackTrace: boolean;
  includeErrorCodes: boolean;
}

export class ErrorHandler {
  private options: ErrorHandlerOptions;

  constructor(options: Partial<ErrorHandlerOptions> = {}) {
    this.options = {
      logErrors: true,
      includeStackTrace: true,
      includeErrorCodes: true,
      ...options,
    };
  }

  public handle(error: unknown): AppError {
    if (error instanceof AppError) {
      this.logError(error);
      return error;
    }

    if (error instanceof Error) {
      const appError = new InternalError(error.message);
      if (this.options.includeStackTrace && error.stack) {
        appError.stack = error.stack;
      }
      this.logError(appError);
      return appError;
    }

    const appError = new InternalError("An unknown error occurred");
    this.logError(appError);
    return appError;
  }

  public async handleAsync<T>(fn: () => Promise<T>): Promise<T | AppError> {
    try {
      return await fn();
    } catch (error) {
      return this.handle(error);
    }
  }

  private logError(error: AppError): void {
    if (!this.options.logErrors) return;

    const logEntry = {
      level: error.level,
      code: this.options.includeErrorCodes ? error.code : undefined,
      message: error.message,
      stack: this.options.includeStackTrace ? error.stack : undefined,
      metadata: error.metadata,
    };

    switch (error.level) {
      case ErrorLevel.DEBUG:
        console.debug(logEntry);
        break;
      case ErrorLevel.INFO:
        console.info(logEntry);
        break;
      case ErrorLevel.WARNING:
        console.warn(logEntry);
        break;
      case ErrorLevel.CRITICAL:
      case ErrorLevel.FATAL:
      case ErrorLevel.ERROR:
      default:
        console.error(logEntry);
        break;
    }
  }
}

// ═══════════════════════════════════════════════════════════════
// Error Boundary (React)
// ═══════════════════════════════════════════════════════════════

import { Component, ErrorInfo, ReactNode } from "react";

interface ErrorBoundaryProps {
  children: ReactNode;
  fallback?: ReactNode;
  onError?: (error: Error, errorInfo: ErrorInfo) => void;
}

interface ErrorBoundaryState {
  hasError: boolean;
  error: Error | null;
}

export class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, error };
  }

  componentDidCatch(error: Error, errorInfo: ErrorInfo): void {
    console.error("ErrorBoundary caught:", error, errorInfo);
    this.props.onError?.(error, errorInfo);
  }

  render(): ReactNode {
    if (this.state.hasError) {
      return this.props.fallback || (
        <div>
          <h1>Something went wrong</h1>
          <p>{this.state.error?.message}</p>
        </div>
      );
    }

    return this.props.children;
  }
}

// ═══════════════════════════════════════════════════════════════
// Export
// ═══════════════════════════════════════════════════════════════

export { ErrorCode, ErrorLevel, AppError, ErrorHandler };
export default ErrorHandler;
"""

        return ErrorHandler(
            code=code,
            language="typescript",
            error_types=list(ErrorType),
            includes_retry=config.retry_logic,
            includes_circuit_breaker=config.circuit_breaker,
        )

    def get_language(self) -> str:
        """Get language name."""
        return "typescript"


class PythonErrorHandlerStrategy(ErrorHandlerStrategy):
    """
    Python error handler strategy.
    """

    def generate(self, config: ErrorConfig) -> ErrorHandler:
        """Generate Python error handler."""
        code = '''"""
Error Handler
Generated by AI Orchestrator
"""

from enum import Enum
from typing import Optional, Dict, Any, Callable
from datetime import datetime
import logging
import traceback


# ═══════════════════════════════════════════════════════════════
# Error Enums
# ═══════════════════════════════════════════════════════════════

class ErrorCode(str, Enum):
    VALIDATION = "VALIDATION_ERROR"
    AUTHENTICATION = "AUTHENTICATION_ERROR"
    AUTHORIZATION = "AUTHORIZATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    INTERNAL = "INTERNAL_ERROR"
    TIMEOUT = "TIMEOUT_ERROR"
    RATE_LIMIT = "RATE_LIMIT_ERROR"
    NETWORK = "NETWORK_ERROR"
    DATABASE = "DATABASE_ERROR"


class ErrorLevel(str, Enum):
    DEBUG = "debug"
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"
    FATAL = "fatal"


# ═══════════════════════════════════════════════════════════════
# Custom Error Classes
# ═══════════════════════════════════════════════════════════════

class AppError(Exception):
    """Base application error."""

    def __init__(
        self,
        message: str,
        code: ErrorCode = ErrorCode.INTERNAL,
        status_code: int = 500,
        level: ErrorLevel = ErrorLevel.ERROR,
        is_operational: bool = True,
        metadata: Optional[Dict[str, Any]] = None,
    ):
        super().__init__(message)
        self.message = message
        self.code = code
        self.status_code = status_code
        self.level = level
        self.is_operational = is_operational
        self.metadata = metadata or {}
        self.metadata["timestamp"] = datetime.utcnow().isoformat()

    def with_metadata(self, **kwargs) -> "AppError":
        """Add metadata to error."""
        self.metadata.update(kwargs)
        return self


class ValidationError(AppError):
    """Validation error."""

    def __init__(self, message: str, **kwargs):
        super().__init__(message, ErrorCode.VALIDATION, 400, ErrorLevel.WARNING, **kwargs)


class AuthenticationError(AppError):
    """Authentication error."""

    def __init__(self, message: str = "Authentication required", **kwargs):
        super().__init__(message, ErrorCode.AUTHENTICATION, 401, ErrorLevel.WARNING, **kwargs)


class AuthorizationError(AppError):
    """Authorization error."""

    def __init__(self, message: str = "Access denied", **kwargs):
        super().__init__(message, ErrorCode.AUTHORIZATION, 403, ErrorLevel.WARNING, **kwargs)


class NotFoundError(AppError):
    """Resource not found error."""

    def __init__(self, resource: str = "Resource", **kwargs):
        super().__init__(f"{resource} not found", ErrorCode.NOT_FOUND, 404, ErrorLevel.INFO, **kwargs)


class InternalError(AppError):
    """Internal server error."""

    def __init__(self, message: str = "Internal server error", **kwargs):
        super().__init__(message, ErrorCode.INTERNAL, 500, ErrorLevel.ERROR, **kwargs)


class TimeoutError(AppError):
    """Timeout error."""

    def __init__(self, message: str = "Request timeout", **kwargs):
        super().__init__(message, ErrorCode.TIMEOUT, 408, ErrorLevel.WARNING, **kwargs)


class RateLimitError(AppError):
    """Rate limit error."""

    def __init__(self, message: str = "Too many requests", **kwargs):
        super().__init__(message, ErrorCode.RATE_LIMIT, 429, ErrorLevel.WARNING, **kwargs)


# ═══════════════════════════════════════════════════════════════
# Error Handler
# ═══════════════════════════════════════════════════════════════

class ErrorHandler:
    """Centralized error handler."""

    def __init__(
        self,
        log_errors: bool = True,
        include_stack_trace: bool = True,
        include_error_codes: bool = True,
        logger: Optional[logging.Logger] = None,
    ):
        self.log_errors = log_errors
        self.include_stack_trace = include_stack_trace
        self.include_error_codes = include_error_codes
        self.logger = logger or logging.getLogger(__name__)

    def handle(self, error: Exception) -> AppError:
        """Handle error."""
        if isinstance(error, AppError):
            self._log_error(error)
            return error

        # Wrap unknown errors
        app_error = InternalError(str(error))
        if self.include_stack_trace:
            app_error.with_metadata(stack_trace=traceback.format_exc())
        self._log_error(app_error)
        return app_error

    def handle_async(self, func: Callable):
        """Decorator for async error handling."""
        import functools
        import asyncio

        @functools.wraps(func)
        async def wrapper(*args, **kwargs):
            try:
                return await func(*args, **kwargs)
            except Exception as error:
                raise self.handle(error)

        return wrapper

    def _log_error(self, error: AppError) -> None:
        """Log error."""
        if not self.log_errors:
            return

        log_entry = {
            "level": error.level.value,
            "message": error.message,
            "code": error.code.value if self.include_error_codes else None,
            "metadata": error.metadata,
        }

        if self.include_stack_trace:
            log_entry["stack_trace"] = traceback.format_exc()

        log_func = {
            ErrorLevel.DEBUG: self.logger.debug,
            ErrorLevel.INFO: self.logger.info,
            ErrorLevel.WARNING: self.logger.warning,
            ErrorLevel.ERROR: self.logger.error,
            ErrorLevel.CRITICAL: self.logger.critical,
            ErrorLevel.FATAL: self.logger.critical,
        }.get(error.level, self.logger.error)

        log_func(log_entry)


# ═══════════════════════════════════════════════════════════════
# Error Boundary Context Manager
# ═══════════════════════════════════════════════════════════════

from contextlib import contextmanager


@contextmanager
def error_boundary(
    handler: Optional[ErrorHandler] = None,
    fallback: Optional[Callable[[Exception], Any]] = None,
):
    """Context manager for error boundary."""
    error_handler = handler or ErrorHandler()
    try:
        yield
    except Exception as error:
        handled_error = error_handler.handle(error)
        if fallback:
            fallback(handled_error)
        else:
            raise handled_error


# ═══════════════════════════════════════════════════════════════
# Export
# ═══════════════════════════════════════════════════════════════

__all__ = [
    "ErrorCode",
    "ErrorLevel",
    "AppError",
    "ValidationError",
    "AuthenticationError",
    "AuthorizationError",
    "NotFoundError",
    "InternalError",
    "TimeoutError",
    "RateLimitError",
    "ErrorHandler",
    "error_boundary",
]
'''

        return ErrorHandler(
            code=code,
            language="python",
            error_types=list(ErrorType),
            includes_retry=config.retry_logic,
            includes_circuit_breaker=config.circuit_breaker,
        )

    def get_language(self) -> str:
        """Get language name."""
        return "python"


# ═══════════════════════════════════════════════════════════════
# ERROR HANDLER GENERATOR (FACADE)
# ═══════════════════════════════════════════════════════════════


class ErrorHandlerGenerator:
    """
    Facade for error handler generation.

    Usage:
        generator = ErrorHandlerGenerator("typescript")
        handler = generator.generate()
    """

    def __init__(self, language: str = "typescript"):
        """Initialize generator."""
        self._strategies = {
            "typescript": TypeScriptErrorHandlerStrategy(),
            "python": PythonErrorHandlerStrategy(),
        }
        self._language = language

    def generate(self, config: ErrorConfig = None) -> ErrorHandler:
        """Generate error handler."""
        if config is None:
            config = ErrorConfig(language=self._language)

        strategy = self._strategies.get(self._language)

        if not strategy:
            raise ValueError(f"Unsupported language: {self._language}")

        return strategy.generate(config)

    def get_supported_languages(self) -> List[str]:
        """Get supported languages."""
        return list(self._strategies.keys())


# ═══════════════════════════════════════════════════════════════
# CONVENIENCE FUNCTIONS
# ═══════════════════════════════════════════════════════════════


def generate_typescript_error_handler() -> str:
    """Generate TypeScript error handler."""
    generator = ErrorHandlerGenerator("typescript")
    return generator.generate().code


def generate_python_error_handler() -> str:
    """Generate Python error handler."""
    generator = ErrorHandlerGenerator("python")
    return generator.generate().code
