"""
Architect — Architecture rule generation for projects
=======================================================
Author: Georgios-Chrysovalantis Chatzivantsidis

Extracted from engine.py Phase 4: Architecture Rules.
Orchestrator._generate_architecture_rules() delegates here.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from ..api_clients import UnifiedClient

logger = logging.getLogger("orchestrator.engine_core.architect")


class Architect:
    """Generates project-specific architecture rules and summaries.

    Wraps the ArchitectureRulesEngine call and file output logic
    that engine.py previously held inline.

    Args:
        client: UnifiedClient for LLM calls.
    """

    def __init__(self, client: UnifiedClient) -> None:
        self._client = client

    async def generate_rules(
        self,
        project_description: str,
        success_criteria: str,
        output_dir: Path | None = None,
    ) -> Any:
        """Generate architecture rules at project start.

        Creates .orchestrator-rules.yml with:
        - Architecture decisions
        - Technology stack
        - Constraints and patterns
        - Quality gates

        Args:
            project_description: What the project builds.
            success_criteria: How success is measured.
            output_dir: Optional output directory for rule files.

        Returns:
            ProjectRules object, or None on failure.
        """
        try:
            from ..architecture_rules import ArchitectureRulesEngine

            logger.info("Generating architecture rules...")

            engine = ArchitectureRulesEngine(client=self._client)
            rules = await engine.generate_rules(
                description=project_description,
                criteria=success_criteria,
            )

            # Print summary
            summary = engine.generate_summary(rules)
            print("\n" + summary)

            # Save to file if output_dir provided
            if output_dir:
                rules_file = engine.save_rules(rules, output_dir)
                logger.info(f"Architecture rules saved to: {rules_file}")

                # Also save a human-readable summary
                summary_file = output_dir / "ARCHITECTURE.md"
                summary_content = _build_architecture_md(rules)
                summary_file.write_text(summary_content, encoding="utf-8")
                logger.info(f"Architecture summary saved to: {summary_file}")

            return rules

        except Exception as e:
            logger.warning(f"Architecture rules generation failed: {e}")
            return None


def _build_architecture_md(rules: Any) -> str:
    """Build a human-readable ARCHITECTURE.md from ProjectRules.

    Args:
        rules: The ProjectRules object from ArchitectureRulesEngine.

    Returns:
        Markdown string for the architecture summary file.
    """
    test_hints = "Required" if rules.coding_standards.type_hints else "Optional"
    return f"""# Architecture Decision

## Project Overview
- **Type**: {rules.project_type}
- **Generated**: {rules.created_at}
- **Rules Version**: {rules.version}

## Decisions

### Architecture Style
**{rules.architecture.style.value.replace('_', ' ').title()}**

{rules.architecture.rationale}

### Programming Paradigm
{rules.architecture.paradigm.value.replace('_', ' ').title()}

### Technology Stack

**Primary Language**: {rules.architecture.stack.primary_language}

**Frameworks**:
{chr(10).join(['- ' + f for f in rules.architecture.stack.frameworks])}

**Libraries**:
{chr(10).join(['- ' + l for l in rules.architecture.stack.libraries[:5]])}

**Databases**:
{chr(10).join(['- ' + d for d in rules.architecture.stack.databases])}

## Constraints

{chr(10).join(['- ' + c for c in rules.architecture.constraints])}

## Recommended Patterns

{chr(10).join(['- ' + p for p in rules.architecture.patterns])}

## Quality Gates

- **Test Coverage**: Minimum {rules.coding_standards.test_coverage_min}%
- **Max Complexity**: {rules.coding_standards.max_complexity}
- **Max Line Length**: {rules.coding_standards.max_line_length} characters
- **Type Hints**: {test_hints}

## Tradeoffs

{chr(10).join(['- ' + t for t in rules.architecture.tradeoffs])}

---
*Generated by Multi-LLM Orchestrator Architecture Rules Engine*
"""
