"""Shared Command for LLM-proposed structural candidates (E-11).

The LLM call happens once, during ``propose()`` (already async) — never
inside ``apply()``. ``RefinementCommand.apply`` is a synchronous Protocol
method invoked from the ledger (plan §3.4.2's Command/Memento pair); doing
network I/O there would either block the event loop or require
``asyncio.run()`` inside an already-running loop, which raises. Precomputing
the full new source in ``propose()`` and having ``apply()`` do nothing but
a file write keeps every Command mechanically simple and keeps "thinking"
and "doing" separated, matching the mechanical operators' own shape.
"""

from __future__ import annotations

import ast
import re
from pathlib import Path
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class RefactorClientPort(Protocol):
    """Structural typing over the LLM client the structural operators need.

    Duck-typed against ``UnifiedClient.call`` so operators never import the
    concrete infrastructure client (Contract 2) — the composition root
    injects the real one.
    """

    async def call(
        self,
        model: Any,
        prompt: str,
        system: str | None = None,
        max_tokens: int = 4096,
        temperature: float = 0.7,
        **kwargs: Any,
    ) -> Any: ...


def strip_code_fences(text: str) -> str:
    """Remove leading/trailing markdown code fences from LLM output."""
    text = re.sub(r"^```[a-zA-Z]*\n?", "", text.strip())
    text = re.sub(r"\n?```\s*$", "", text)
    return text.strip()


def is_valid_python(source: str) -> bool:
    """Cheap pre-check before proposing a candidate: does it even parse?

    Catches truncated or explanation-prefixed LLM output before it costs a
    full apply/test/revert cycle — the acceptance chain is the real gate,
    this just avoids paying for an obviously broken candidate.
    """
    if not source.strip():
        return False
    try:
        ast.parse(source)
    except SyntaxError:
        return False
    return True


class LLMRefactorCommand:
    """Command: write a pre-generated full-file replacement.

    One instance per candidate. ``new_source`` is produced by the owning
    operator's ``propose()`` and is never regenerated by ``apply()`` —
    the same candidate always applies the same bytes, which is what makes
    revert-and-retry deterministic.
    """

    name = "structural.llm_refactor"

    def __init__(self, target_file: Path | str, new_source: str) -> None:
        """Initialize with the file to replace and its full new content.

        Args:
            target_file: Workspace-relative (or absolute) path to rewrite.
            new_source: Complete replacement source for that file.
        """
        self._target_file = Path(target_file)
        self._new_source = new_source

    def apply(self, workspace_root: Path) -> list[str]:
        """Write the pre-generated source; return the changed file path.

        Returns an empty list (no-op) when the target is missing or the
        proposed content is byte-identical to what is already on disk —
        the service treats a no-op as zero-cost, not a rejection.
        """
        path = (
            self._target_file
            if self._target_file.is_absolute()
            else workspace_root / self._target_file
        )
        if not path.exists():
            return []
        try:
            before = path.read_text(encoding="utf-8")
        except OSError:  # pragma: no cover - best-effort
            return []
        if before == self._new_source:
            return []
        path.write_text(self._new_source, encoding="utf-8")
        return [str(self._target_file)]


async def propose_llm_candidate(
    *,
    client: RefactorClientPort,
    model: Any,
    operator_name: str,
    tier: Any,
    target_file: str,
    source: str,
    predicted_metric: str,
    rationale: str,
    instruction: str,
    system: str,
) -> list[Any]:
    """Call the LLM once and package its output as a single candidate.

    Shared by the structural operators (composition, not a Template Method
    base class — plan §3.4.2 explicitly avoids operator inheritance). Every
    operator supplies its own targeted *instruction* citing the specific
    measured finding; this function only handles the call, validation, and
    candidate packaging that all three do identically.

    Returns an empty list — never raises — on any LLM failure, invalid
    output, or a no-op response, so one operator's failure never aborts
    the refinement pass (mirrors the service's own per-operator isolation).
    """
    from ....domain.refinement import RefinementCandidate

    prompt = (
        f"{instruction}\n\n"
        f"Current file content:\n```python\n{source}\n```\n\n"
        "Return the COMPLETE new file content, behavior-preserving, "
        "same public API. Output ONLY the Python code, no explanation."
    )
    try:
        response = await client.call(
            model=model,
            prompt=prompt,
            system=system,
            max_tokens=6000,
            temperature=0.2,
            timeout=120,
        )
    except Exception:  # never let one operator's LLM call kill the pass
        return []

    new_source = strip_code_fences(getattr(response, "text", "") or "")
    if new_source and not new_source.endswith("\n"):
        # strip_code_fences trims trailing whitespace along with the fence;
        # a "complete file" candidate must still end with a newline (PEP 8),
        # and a missing one would make every no-op comparison in
        # LLMRefactorCommand.apply() spuriously report a change.
        new_source += "\n"
    if not is_valid_python(new_source) or new_source == source:
        return []

    return [
        RefinementCandidate(
            operator=operator_name,
            tier=tier,
            target_file=target_file,
            rationale=rationale,
            diff=f"<llm-proposed rewrite, {len(new_source)} chars>",
            predicted_metric=predicted_metric,
            payload=new_source,
        )
    ]


__all__ = [
    "LLMRefactorCommand",
    "RefactorClientPort",
    "is_valid_python",
    "propose_llm_candidate",
    "strip_code_fences",
]
