"""
Mnemo Cortex CLI
================
The command-line interface for managing Mnemo Cortex.

  mnemo-cortex init     → Interactive setup wizard
  mnemo-cortex start    → Start the server
  mnemo-cortex stop     → Stop the server
  mnemo-cortex status   → Check health + session stats
  mnemo-cortex logs     → Tail the server logs
  mnemo-cortex test     → Quick connectivity test

https://github.com/GuyMannDude/mnemo-cortex
"""

import os
import sys
import json
import signal
import subprocess
import time
from pathlib import Path

import click
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.prompt import Prompt, Confirm
from rich import print as rprint

console = Console()

CONFIG_DIR = Path.home() / ".config" / "agentb"
CONFIG_FILE = CONFIG_DIR / "agentb.yaml"
DATA_DIR = Path.home() / ".agentb"
PID_FILE = DATA_DIR / "mnemo.pid"
LOG_FILE = DATA_DIR / "logs" / "mnemo.log"

BANNER = """[bold yellow]
  ⚡ Mnemo Cortex
[/bold yellow][dim]  "I remember everything so your agent doesn't have to."[/dim]
"""

# ─────────────────────────────────────────────
#  Main CLI Group
# ─────────────────────────────────────────────

@click.group(invoke_without_command=True)
@click.pass_context
@click.version_option(version="0.4.0", prog_name="mnemo-cortex")
def main(ctx):
    """⚡ Mnemo Cortex — Drop-in memory superhero for AI agents."""
    if ctx.invoked_subcommand is None:
        console.print(BANNER)
        console.print("  Commands: [bold]init[/] · [bold]start[/] · [bold]stop[/] · [bold]status[/] · [bold]watch[/] · [bold]logs[/] · [bold]test[/]")
        console.print()
        if not CONFIG_FILE.exists():
            console.print("  [yellow]→ Run [bold]mnemo-cortex init[/bold] to get started![/]")
        else:
            console.print(f"  Config: {CONFIG_FILE}")
            console.print(f"  Data:   {DATA_DIR}")
        console.print()


# ─────────────────────────────────────────────
#  Init — Interactive Setup Wizard
# ─────────────────────────────────────────────

@main.command()
def init():
    """Interactive setup wizard. Gets you running in 2 minutes."""
    console.print(BANNER)
    console.print(Panel(
        "[bold]Welcome to Mnemo Cortex setup![/]\n\n"
        "This wizard will configure your memory coprocessor.\n"
        "You'll pick a reasoning provider, embedding provider, and we'll test the connection.",
        title="⚡ Setup Wizard",
        border_style="yellow",
    ))
    console.print()

    # Step 1: Reasoning provider
    console.print("[bold cyan]Step 1/4: Reasoning Provider[/]")
    console.print("This model handles preflight checks (validating your agent's responses).\n")

    reasoning_choice = Prompt.ask(
        "Provider",
        choices=["ollama", "openai", "anthropic", "openrouter", "google"],
        default="ollama",
    )

    reasoning_config = _configure_provider(reasoning_choice, "reasoning")

    # Step 2: Embedding provider
    console.print()
    console.print("[bold cyan]Step 2/4: Embedding Provider[/]")
    console.print("This model powers semantic memory search.\n")

    embedding_choice = Prompt.ask(
        "Provider",
        choices=["ollama", "openai", "huggingface", "google", "openrouter"],
        default="ollama" if reasoning_choice == "ollama" else "openai",
    )

    embedding_config = _configure_provider(embedding_choice, "embedding")

    # Step 3: Server settings
    console.print()
    console.print("[bold cyan]Step 3/4: Server Settings[/]")
    port = Prompt.ask("Port", default="50001")
    auth = Prompt.ask("API auth token (leave blank for none)", default="")

    # Step 4: Agent setup
    console.print()
    console.print("[bold cyan]Step 4/4: Agent Setup[/]")
    console.print("Name your agents so their memories stay isolated.\n")

    agents = {}
    while True:
        agent_name = Prompt.ask("Agent name (or 'done' to finish)", default="done")
        if agent_name.lower() == "done":
            break
        persona = Prompt.ask(
            f"  Persona for {agent_name}",
            choices=["default", "strict", "creative"],
            default="default",
        )
        agents[agent_name] = {"persona": persona}

    # Build config YAML
    yaml_lines = [
        "# Mnemo Cortex Configuration",
        f"# Generated by mnemo-cortex init on {time.strftime('%Y-%m-%d %H:%M')}",
        "",
        f"data_dir: {DATA_DIR}",
        "log_level: info",
        "",
        "# Reasoning provider (preflight checks)",
        "reasoning:",
        f"  provider: {reasoning_config['provider']}",
        f"  model: {reasoning_config['model']}",
    ]
    if reasoning_config.get("api_key"):
        yaml_lines.append(f"  api_key: {reasoning_config['api_key']}")
    if reasoning_config.get("api_base"):
        yaml_lines.append(f"  api_base: {reasoning_config['api_base']}")
    yaml_lines.append(f"  timeout: {reasoning_config.get('timeout', 30)}")

    yaml_lines.extend([
        "",
        "# Embedding provider (semantic search)",
        "embedding:",
        f"  provider: {embedding_config['provider']}",
        f"  model: {embedding_config['model']}",
    ])
    if embedding_config.get("api_key"):
        yaml_lines.append(f"  api_key: {embedding_config['api_key']}")
    if embedding_config.get("api_base"):
        yaml_lines.append(f"  api_base: {embedding_config['api_base']}")

    yaml_lines.extend([
        "",
        "# Cache settings",
        "cache:",
        "  l1_max_bundles: 50",
        "  l1_ttl_seconds: 86400",
        "  l1_similarity_threshold: 0.75",
        "  l2_similarity_threshold: 0.5",
        "  l3_similarity_threshold: 0.4",
        "",
        "# Server",
        "server:",
        "  host: 0.0.0.0",
        f"  port: {port}",
        '  cors_origins: ["*"]',
    ])
    if auth:
        yaml_lines.append(f"  auth_token: {auth}")

    if agents:
        yaml_lines.extend(["", "# Agents"])
        yaml_lines.append("agents:")
        for name, cfg in agents.items():
            yaml_lines.append(f"  {name}:")
            yaml_lines.append(f"    persona: {cfg['persona']}")

    yaml_content = "\n".join(yaml_lines) + "\n"

    # Write config
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    (DATA_DIR / "logs").mkdir(parents=True, exist_ok=True)

    CONFIG_FILE.write_text(yaml_content)

    console.print()
    console.print(Panel(
        f"[green]Config saved to:[/] {CONFIG_FILE}\n"
        f"[green]Data directory:[/]  {DATA_DIR}\n\n"
        "[bold]Next steps:[/]\n"
        "  [yellow]mnemo-cortex start[/]   — Start the server\n"
        "  [yellow]mnemo-cortex status[/]  — Check everything is working\n"
        "  [yellow]mnemo-cortex test[/]    — Quick connectivity test",
        title="⚡ Setup Complete!",
        border_style="green",
    ))


def _configure_provider(provider: str, role: str) -> dict:
    """Interactive configuration for a specific provider."""
    config = {"provider": provider}

    if provider == "ollama":
        config["api_base"] = Prompt.ask("  Ollama URL", default="http://localhost:11434")
        if role == "reasoning":
            config["model"] = Prompt.ask("  Model", default="qwen2.5:32b-instruct")
        else:
            config["model"] = Prompt.ask("  Model", default="nomic-embed-text")
        config["timeout"] = 30

    elif provider == "openai":
        config["api_key"] = Prompt.ask("  API key (or env var like ${OPENAI_API_KEY})")
        if role == "reasoning":
            config["model"] = Prompt.ask("  Model", default="gpt-4o-mini")
        else:
            config["model"] = Prompt.ask("  Model", default="text-embedding-3-small")

    elif provider == "anthropic":
        config["api_key"] = Prompt.ask("  API key (or env var like ${ANTHROPIC_API_KEY})")
        config["model"] = Prompt.ask("  Model", default="claude-sonnet-4-5-20250929")

    elif provider == "openrouter":
        config["api_key"] = Prompt.ask("  API key (or env var like ${OPENROUTER_API_KEY})")
        if role == "reasoning":
            config["model"] = Prompt.ask("  Model", default="nousresearch/hermes-3-llama-3.1-405b:free")
        else:
            config["model"] = Prompt.ask("  Model", default="thenlper/gte-base")

    elif provider == "google":
        config["api_key"] = Prompt.ask("  API key (or env var like ${GEMINI_API_KEY})")
        if role == "reasoning":
            config["model"] = Prompt.ask("  Model", default="gemini-2.5-flash")
        else:
            config["model"] = Prompt.ask("  Model", default="text-embedding-004")

    elif provider == "huggingface":
        config["model"] = Prompt.ask("  Model", default="sentence-transformers/all-MiniLM-L6-v2")
        api_base = Prompt.ask("  Local server URL (blank for HF API)", default="")
        if api_base:
            config["api_base"] = api_base
        else:
            config["api_key"] = Prompt.ask("  HuggingFace API token")

    return config


# ─────────────────────────────────────────────
#  Start
# ─────────────────────────────────────────────

@main.command()
@click.option("--foreground", "-f", is_flag=True, help="Run in foreground (don't daemonize)")
@click.option("--port", "-p", type=int, default=None, help="Override port")
def start(foreground, port):
    """Start the Mnemo Cortex server."""
    console.print(BANNER)

    if not CONFIG_FILE.exists():
        console.print("[red]No config found. Run [bold]mnemo-cortex init[/bold] first![/]")
        sys.exit(1)

    if _is_running():
        console.print("[yellow]Mnemo Cortex is already running.[/]")
        console.print(f"  PID: {_get_pid()}")
        console.print("  Run [bold]mnemo-cortex stop[/] first, or [bold]mnemo-cortex status[/] to check.")
        return

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    (DATA_DIR / "logs").mkdir(parents=True, exist_ok=True)

    env = os.environ.copy()
    env["AGENTB_CONFIG"] = str(CONFIG_FILE)

    cmd = [sys.executable, "-m", "agentb.server"]

    if foreground:
        console.print("[yellow]Starting in foreground... (Ctrl+C to stop)[/]")
        console.print()
        try:
            subprocess.run(cmd, env=env)
        except KeyboardInterrupt:
            console.print("\n[yellow]Stopped.[/]")
    else:
        log_fh = open(LOG_FILE, "a")
        proc = subprocess.Popen(
            cmd, env=env,
            stdout=log_fh, stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        PID_FILE.write_text(str(proc.pid))

        # Wait a moment and check
        time.sleep(2)
        if proc.poll() is None:
            console.print(f"[green]⚡ Mnemo Cortex started![/]")
            console.print(f"  PID:  {proc.pid}")
            console.print(f"  Log:  {LOG_FILE}")
            console.print(f"  URL:  http://localhost:{port or 50001}")
            console.print()
            console.print("  [dim]mnemo-cortex status  — check health[/]")
            console.print("  [dim]mnemo-cortex logs    — watch logs[/]")
            console.print("  [dim]mnemo-cortex stop    — stop server[/]")
        else:
            console.print("[red]Failed to start. Check logs:[/]")
            console.print(f"  {LOG_FILE}")
            # Show last few lines
            try:
                lines = LOG_FILE.read_text().strip().split("\n")[-5:]
                for line in lines:
                    console.print(f"  [dim]{line}[/]")
            except Exception:
                pass


# ─────────────────────────────────────────────
#  Stop
# ─────────────────────────────────────────────

@main.command()
def stop():
    """Stop the Mnemo Cortex server."""
    if not _is_running():
        console.print("[yellow]Mnemo Cortex is not running.[/]")
        PID_FILE.unlink(missing_ok=True)
        return

    pid = _get_pid()
    try:
        os.kill(pid, signal.SIGTERM)
        console.print(f"[green]Stopped Mnemo Cortex (PID {pid})[/]")
    except ProcessLookupError:
        console.print("[yellow]Process already gone.[/]")
    PID_FILE.unlink(missing_ok=True)


# ─────────────────────────────────────────────
#  Status
# ─────────────────────────────────────────────

@main.command()
def status():
    """Check Mnemo Cortex health and stats."""
    console.print(BANNER)

    # Process status
    if _is_running():
        console.print(f"  Process: [green]running[/] (PID {_get_pid()})")
    else:
        console.print("  Process: [red]stopped[/]")
        console.print("  Run [bold]mnemo-cortex start[/] to launch.")
        return

    # Health check
    try:
        import httpx
        resp = httpx.get("http://localhost:50001/health", timeout=5.0)
        health = resp.json()

        status_color = {"ok": "green", "degraded": "yellow", "down": "red"}.get(health["status"], "red")
        console.print(f"  Status:  [{status_color}]{health['status']}[/{status_color}]")
        console.print(f"  Version: {health.get('version', 'unknown')}")
        console.print()

        # Reasoning
        r = health.get("reasoning", {})
        r_status = "[green]healthy[/]" if r.get("healthy") else "[red]down[/]"
        r_active = r.get("active", r.get("primary", "unknown"))
        console.print(f"  Reasoning:  {r_status} → {r_active}")
        if r.get("failed_over"):
            console.print(f"              [yellow]⚠ Failed over from {r.get('primary', '?')}[/]")
            if r.get("primary_retry_in"):
                console.print(f"              [dim]Primary retry in {r['primary_retry_in']}[/]")

        # Embedding
        e = health.get("embedding", {})
        e_status = "[green]healthy[/]" if e.get("healthy") else "[red]down[/]"
        e_active = e.get("active", e.get("primary", "unknown"))
        console.print(f"  Embedding:  {e_status} → {e_active}")

        # Sessions
        sessions = health.get("sessions", {})
        if sessions:
            console.print()
            console.print(f"  Sessions:   [cyan]{sessions.get('hot', 0)}[/] hot · "
                         f"[blue]{sessions.get('warm', 0)}[/] warm · "
                         f"[dim]{sessions.get('cold', 0)}[/] cold")

        # Agents
        agents = health.get("agents_configured", [])
        if agents:
            console.print(f"  Agents:     {', '.join(agents)}")

        # Watcher
        if _is_watcher_running():
            console.print(f"  Watcher:    [green]running[/] (PID {_get_watcher_pid()}) — auto-capturing sessions")
        else:
            console.print(f"  Watcher:    [yellow]stopped[/] — run [bold]mnemo-cortex watch[/] to auto-capture")

        console.print()

    except Exception as e:
        console.print(f"  [red]Cannot reach server: {e}[/]")
        console.print("  Is it running? Check [bold]mnemo-cortex logs[/]")


# ─────────────────────────────────────────────
#  Logs
# ─────────────────────────────────────────────

@main.command()
@click.option("--lines", "-n", default=50, help="Number of lines to show")
@click.option("--follow", "-f", is_flag=True, help="Follow log output")
def logs(lines, follow):
    """View Mnemo Cortex server logs."""
    if not LOG_FILE.exists():
        console.print("[yellow]No logs yet. Start the server first.[/]")
        return

    if follow:
        try:
            subprocess.run(["tail", "-f", "-n", str(lines), str(LOG_FILE)])
        except KeyboardInterrupt:
            pass
    else:
        try:
            output = subprocess.run(
                ["tail", "-n", str(lines), str(LOG_FILE)],
                capture_output=True, text=True,
            )
            console.print(output.stdout)
        except Exception as e:
            console.print(f"[red]Error reading logs: {e}[/]")


# ─────────────────────────────────────────────
#  Test
# ─────────────────────────────────────────────

@main.command()
@click.option("--agent", "-a", default=None, help="Agent ID to test with")
def test(agent):
    """Quick connectivity and functionality test."""
    console.print(BANNER)
    console.print("[bold]Running tests...[/]\n")

    base = "http://localhost:50001"
    passed = 0
    failed = 0

    def _test(name, fn):
        nonlocal passed, failed
        try:
            result = fn()
            console.print(f"  [green]✓[/] {name}: {result}")
            passed += 1
        except Exception as e:
            console.print(f"  [red]✗[/] {name}: {e}")
            failed += 1

    import httpx

    # Health
    _test("Health check", lambda: httpx.get(f"{base}/health", timeout=5).json()["status"])

    # Ingest
    _test("Ingest (live wire)", lambda: httpx.post(
        f"{base}/ingest",
        json={"prompt": "Test prompt from CLI", "response": "Test response", "agent_id": agent},
        timeout=5,
    ).json()["status"])

    # Context
    _test("Context search", lambda: f"{httpx.post(f'{base}/context', json={'prompt': 'test', 'agent_id': agent}, timeout=10).json()['total_found']} chunks found")

    # Sessions
    _test("Session listing", lambda: f"{len(httpx.get(f'{base}/sessions', params={'agent_id': agent} if agent else {}, timeout=5).json().get('hot', []))} hot sessions")

    console.print()
    if failed == 0:
        console.print(f"  [green bold]All {passed} tests passed! ⚡[/]")
    else:
        console.print(f"  [yellow]{passed} passed, {failed} failed[/]")


# ─────────────────────────────────────────────
#  Watch — Session Watcher
# ─────────────────────────────────────────────

WATCHER_PID_FILE = DATA_DIR / "watcher.pid"

@main.command()
@click.option("--backfill", "-b", is_flag=True, help="Backfill existing sessions first")
@click.option("--backfill-count", default=10, help="Number of recent sessions to backfill")
@click.option("--foreground", "-f", is_flag=True, help="Run in foreground")
def watch(backfill, backfill_count, foreground):
    """Start the session watcher (auto-captures OpenClaw conversations)."""
    console.print(BANNER)

    if _is_watcher_running():
        console.print("[yellow]Watcher is already running.[/]")
        return

    if backfill:
        console.print("[cyan]Backfilling existing sessions...[/]")
        from agentb.watcher import backfill_sessions
        backfill_sessions(backfill_count)
        console.print()

    env = os.environ.copy()
    env.setdefault("MNEMO_URL", "http://artforge:50001")
    env.setdefault("MNEMO_AGENT_ID", "rocky")

    watcher_script = Path(__file__).parent / "watcher.py"
    cmd = [sys.executable, str(watcher_script)]

    if foreground:
        console.print("[yellow]Watcher running in foreground... (Ctrl+C to stop)[/]")
        try:
            subprocess.run(cmd, env=env)
        except KeyboardInterrupt:
            console.print("\n[yellow]Watcher stopped.[/]")
    else:
        log_file = DATA_DIR / "logs" / "watcher.log"
        (DATA_DIR / "logs").mkdir(parents=True, exist_ok=True)
        log_fh = open(log_file, "a")
        proc = subprocess.Popen(
            cmd, env=env,
            stdout=log_fh, stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        WATCHER_PID_FILE.write_text(str(proc.pid))

        time.sleep(1)
        if proc.poll() is None:
            console.print(f"[green]⚡ Session watcher started![/]")
            console.print(f"  PID: {proc.pid}")
            console.print(f"  Log: {log_file}")
            console.print(f"  Watching: ~/.openclaw/agents/main/sessions/")
            console.print()
            console.print("  [dim]Every exchange Rocky has is now auto-captured.[/]")
            console.print("  [dim]mnemo-cortex unwatch — stop the watcher[/]")
        else:
            console.print("[red]Watcher failed to start. Check logs.[/]")


@main.command()
def unwatch():
    """Stop the session watcher."""
    if not _is_watcher_running():
        console.print("[yellow]Watcher is not running.[/]")
        WATCHER_PID_FILE.unlink(missing_ok=True)
        return

    pid = _get_watcher_pid()
    try:
        os.kill(pid, signal.SIGTERM)
        console.print(f"[green]Watcher stopped (PID {pid})[/]")
    except ProcessLookupError:
        console.print("[yellow]Watcher process already gone.[/]")
    WATCHER_PID_FILE.unlink(missing_ok=True)


def _get_watcher_pid() -> int:
    try:
        return int(WATCHER_PID_FILE.read_text().strip())
    except Exception:
        return 0


def _is_watcher_running() -> bool:
    pid = _get_watcher_pid()
    if pid == 0:
        return False
    try:
        os.kill(pid, 0)
        return True
    except ProcessLookupError:
        return False
    except PermissionError:
        return True


# ─────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────

def _get_pid() -> int:
    try:
        return int(PID_FILE.read_text().strip())
    except Exception:
        return 0


def _is_running() -> bool:
    pid = _get_pid()
    if pid == 0:
        return False
    try:
        os.kill(pid, 0)  # signal 0 = check if process exists
        return True
    except ProcessLookupError:
        return False
    except PermissionError:
        return True  # exists but we can't signal it


if __name__ == "__main__":
    main()
