"""
CI/CD Generator — Builder + Strategy Pattern
=============================================
Author: Georgios-Chrysovalantis Chatzivantsidis

CI/CD pipeline generation using Builder Pattern for pipeline construction
and Strategy Pattern for different CI/CD providers.

Paradigm: OOP with Functional utilities
Patterns: Builder, Strategy, Factory Method, Template Method

Usage:
    from orchestrator.cicd_generator import CICDPipelineBuilder

    pipeline = (CICDPipelineBuilder()
        .for_github_actions()
        .add_job("build", ["node", "python"])
        .add_job("test", ["node"])
        .add_job("deploy", ["node"], needs=["build", "test"])
        .build())
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from enum import Enum

# ═══════════════════════════════════════════════════════════════════
# IMMUTABLE DATA CLASSES
# ═══════════════════════════════════════════════════════════════════


class CICDProvider(str, Enum):
    """CI/CD provider enumeration."""

    GITHUB_ACTIONS = "github_actions"
    GITLAB_CI = "gitlab_ci"
    AZURE_DEVOPS = "azure_devops"
    JENKINS = "jenkins"
    CIRCLE_CI = "circle_ci"


class JobType(str, Enum):
    """Job type enumeration."""

    BUILD = "build"
    TEST = "test"
    LINT = "lint"
    DEPLOY = "deploy"
    SECURITY_SCAN = "security_scan"
    DEPENDENCY_AUDIT = "dependency_audit"
    VULNERABILITY_SCAN = "vulnerability_scan"
    RELEASE = "release"


@dataclass(frozen=True)
class JobConfig:
    """
    Immutable job configuration.

    Attributes:
        name: Job name
        job_type: Type of job
        runs_on: Runner/executor
        steps: Job steps
        needs: Dependencies (other jobs)
        if_condition: Conditional execution
        timeout: Timeout in minutes
        matrix: Strategy matrix axes, e.g. {"python-version": ["3.10", "3.11"]}
        permissions: Job-scoped permissions override (least privilege beyond
            the workflow-level default)
    """

    name: str
    job_type: JobType
    runs_on: str = "ubuntu-latest"
    steps: List[Dict[str, Any]] = field(default_factory=list)
    needs: List[str] = field(default_factory=list)
    if_condition: Optional[str] = None
    timeout: int = 60
    matrix: Dict[str, List[str]] = field(default_factory=dict)
    permissions: Dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class PipelineConfig:
    """
    Immutable pipeline configuration.

    Attributes:
        name: Pipeline name
        provider: CI/CD provider
        branches: Target branches
        jobs: Pipeline jobs
        environment_variables: Environment variables
        secrets: Required secrets
        concurrency_group: In-progress runs for the same group are cancelled
        action_pins: ``"owner/repo@ref"`` -> the ``uses:`` value to render
            (SHA-pinned when resolvable, tag-ref with an indeterminate
            marker comment otherwise). A ref absent from this map is
            rendered unchanged.
    """

    name: str
    provider: CICDProvider
    branches: List[str] = field(default_factory=lambda: ["main", "develop"])
    jobs: List[JobConfig] = field(default_factory=list)
    environment_variables: Dict[str, str] = field(default_factory=dict)
    secrets: List[str] = field(default_factory=list)
    concurrency_group: Optional[str] = None
    action_pins: Dict[str, str] = field(default_factory=dict)


# ═══════════════════════════════════════════════════════════════════
# STRATEGY PATTERN — CI/CD PROVIDER STRATEGIES
# ═══════════════════════════════════════════════════════════════════


class CICDStrategy(ABC):
    """
    Strategy Pattern for CI/CD providers.

    Subclasses implement different CI/CD provider configurations.
    """

    @abstractmethod
    def generate(self, config: PipelineConfig) -> str:
        """
        Generate CI/CD configuration.

        Args:
            config: Pipeline configuration

        Returns:
            Configuration file content
        """
        pass

    @abstractmethod
    def get_provider(self) -> CICDProvider:
        """
        Get provider name.

        Returns:
            CI/CD provider
        """
        pass


class GitHubActionsStrategy(CICDStrategy):
    """
    GitHub Actions strategy.
    """

    def generate(self, config: PipelineConfig) -> str:
        """Generate GitHub Actions workflow."""
        workflow = f"""# {config.name}
# Generated by AI Orchestrator

name: {config.name}

# Least-privilege default token. Grant additional scopes per-job only as needed.
permissions:
  contents: read

on:
  push:
    branches: [{', '.join(config.branches)}]
  pull_request:
    branches: [{', '.join(config.branches)}]

"""

        if config.concurrency_group:
            workflow += (
                f"concurrency:\n"
                f"  group: {config.concurrency_group}\n"
                f"  cancel-in-progress: true\n\n"
            )

        # Add environment variables
        if config.environment_variables:
            workflow += "\nenv:\n"
            for key, value in config.environment_variables.items():
                workflow += f"  {key}: {value}\n"

        # Add jobs
        workflow += "\njobs:\n"

        for job in config.jobs:
            workflow += self._generate_job(job, config.secrets, config.action_pins)

        return workflow

    def _pin(self, uses: str, action_pins: Dict[str, str]) -> str:
        return action_pins.get(uses, uses)

    def _generate_job(self, job: JobConfig, secrets: List[str], action_pins: Dict[str, str]) -> str:
        """Generate job configuration."""
        job_yaml = f"  {job.name}:\n"
        job_yaml += f"    runs-on: {job.runs_on}\n"

        if job.needs:
            job_yaml += f"    needs: [{', '.join(job.needs)}]\n"

        if job.if_condition:
            job_yaml += f"    if: {job.if_condition}\n"

        if job.permissions:
            job_yaml += "    permissions:\n"
            for scope, level in job.permissions.items():
                job_yaml += f"      {scope}: {level}\n"

        if job.matrix:
            job_yaml += "    strategy:\n      matrix:\n"
            for axis, values in job.matrix.items():
                rendered = ", ".join(f'"{v}"' for v in values)
                job_yaml += f"        {axis}: [{rendered}]\n"
            job_yaml += "      fail-fast: false\n"

        job_yaml += f"    timeout-minutes: {job.timeout}\n"

        # Add steps
        job_yaml += "    steps:\n"
        job_yaml += f"      - uses: {self._pin('actions/checkout@v4', action_pins)}\n"

        for step in job.steps:
            if "uses" in step:
                job_yaml += f"      - uses: {self._pin(step['uses'], action_pins)}\n"
                if "with" in step:
                    job_yaml += "        with:\n"
                    for key, value in step["with"].items():
                        job_yaml += f"          {key}: {value}\n"
            elif "run" in step:
                job_yaml += f"      - name: {step.get('name', 'Run command')}\n"
                job_yaml += f"        run: {step['run']}\n"

        return job_yaml

    def get_provider(self) -> CICDProvider:
        """Get provider name."""
        return CICDProvider.GITHUB_ACTIONS


class GitLabCIStrategy(CICDStrategy):
    """
    GitLab CI strategy.
    """

    def generate(self, config: PipelineConfig) -> str:
        """Generate GitLab CI configuration."""
        ci_yaml = f"# {config.name}\n"
        ci_yaml += "# Generated by AI Orchestrator\n\n"

        # Add variables
        if config.environment_variables:
            ci_yaml += "variables:\n"
            for key, value in config.environment_variables.items():
                ci_yaml += f"  {key}: {value}\n"
            ci_yaml += "\n"

        # Add stages
        stages = list(set(job.job_type.value for job in config.jobs))
        ci_yaml += f"stages:\n  - {'.stages'.join(stages)}\n\n"

        # Add jobs
        for job in config.jobs:
            ci_yaml += self._generate_job(job)

        return ci_yaml

    def _generate_job(self, job: JobConfig) -> str:
        """Generate job configuration."""
        job_yaml = f"{job.name}:\n"
        job_yaml += f"  stage: {job.job_type.value}\n"
        job_yaml += f"  image: {job.runs_on}\n"

        if job.needs:
            job_yaml += f"  needs: [{', '.join(job.needs)}]\n"

        if job.if_condition:
            job_yaml += f"  rules:\n    - if: {job.if_condition}\n"

        # Add scripts
        job_yaml += "  script:\n"
        for step in job.steps:
            if "run" in step:
                job_yaml += f"    - {step['run']}\n"

        job_yaml += "\n"
        return job_yaml

    def get_provider(self) -> CICDProvider:
        """Get provider name."""
        return CICDProvider.GITLAB_CI


class AzureDevOpsStrategy(CICDStrategy):
    """
    Azure DevOps strategy.
    """

    def generate(self, config: PipelineConfig) -> str:
        """Generate Azure DevOps pipeline."""
        pipeline = f"""# {config.name}
# Generated by AI Orchestrator

trigger:
  branches:
    include: [{', '.join(config.branches)}]

pool:
  vmImage: 'ubuntu-latest'

"""

        # Add jobs
        pipeline += "jobs:\n"

        for job in config.jobs:
            pipeline += self._generate_job(job)

        return pipeline

    def _generate_job(self, job: JobConfig) -> str:
        """Generate job configuration."""
        job_yaml = f"  - job: {job.name.replace('-', '_')}\n"
        job_yaml += f"    displayName: '{job.name}'\n"
        job_yaml += f"    timeoutInMinutes: {job.timeout}\n"

        if job.needs:
            job_yaml += f"    dependsOn: [{', '.join(job.needs)}]\n"

        job_yaml += "    steps:\n"
        job_yaml += "      - checkout: self\n"

        for step in job.steps:
            if "run" in step:
                job_yaml += f"      - script: {step['run']}\n"
                if "name" in step:
                    job_yaml += f"        displayName: {step['name']}\n"

        return job_yaml

    def get_provider(self) -> CICDProvider:
        """Get provider name."""
        return CICDProvider.AZURE_DEVOPS


# ═══════════════════════════════════════════════════════════════════
# BUILDER PATTERN — CI/CD PIPELINE BUILDER
# ═══════════════════════════════════════════════════════════════════


class CICDPipelineBuilder:
    """
    Builder Pattern for CI/CD pipelines.

    Fluent interface for constructing CI/CD configurations.

    Usage:
        pipeline = (CICDPipelineBuilder()
            .for_github_actions()
            .add_job("build", ["node"])
            .add_job("test", ["node"])
            .build())
    """

    def __init__(self):
        """Initialize builder."""
        self._name: str = "CI/CD Pipeline"
        self._provider: CICDProvider = CICDProvider.GITHUB_ACTIONS
        self._branches: List[str] = ["main", "develop"]
        self._jobs: List[JobConfig] = []
        self._env_vars: Dict[str, str] = {}
        self._secrets: List[str] = []
        self._strategy: CICDStrategy = GitHubActionsStrategy()
        self._concurrency_group: Optional[str] = None
        self._action_pins: Dict[str, str] = {}
        self._cov_fail_under: Optional[int] = None

    def for_github_actions(self) -> "CICDPipelineBuilder":
        """Configure for GitHub Actions."""
        self._provider = CICDProvider.GITHUB_ACTIONS
        self._strategy = GitHubActionsStrategy()
        return self

    def for_gitlab_ci(self) -> "CICDPipelineBuilder":
        """Configure for GitLab CI."""
        self._provider = CICDProvider.GITLAB_CI
        self._strategy = GitLabCIStrategy()
        return self

    def for_azure_devops(self) -> "CICDPipelineBuilder":
        """Configure for Azure DevOps."""
        self._provider = CICDProvider.AZURE_DEVOPS
        self._strategy = AzureDevOpsStrategy()
        return self

    def with_name(self, name: str) -> "CICDPipelineBuilder":
        """Set pipeline name."""
        self._name = name
        return self

    def with_branches(self, branches: List[str]) -> "CICDPipelineBuilder":
        """Set target branches."""
        self._branches = branches
        return self

    def add_env_var(self, key: str, value: str) -> "CICDPipelineBuilder":
        """Add environment variable."""
        self._env_vars[key] = value
        return self

    def add_secret(self, secret: str) -> "CICDPipelineBuilder":
        """Add required secret."""
        self._secrets.append(secret)
        return self

    def with_concurrency_group(self, group: str) -> "CICDPipelineBuilder":
        """Cancel superseded in-progress runs sharing this group."""
        self._concurrency_group = group
        return self

    def with_action_pins(self, pins: Dict[str, str]) -> "CICDPipelineBuilder":
        """``"owner/repo@ref"`` -> the ``uses:`` value to render for it."""
        self._action_pins = pins
        return self

    def with_coverage_floor(self, fail_under: int) -> "CICDPipelineBuilder":
        """Inherited from the target project's own ``pyproject.toml``."""
        self._cov_fail_under = fail_under
        return self

    def add_job(
        self,
        name: str,
        languages: List[str] = None,
        job_type: str = "build",
        runs_on: str = "ubuntu-latest",
        needs: List[str] = None,
        timeout: int = 60,
        matrix: Dict[str, List[str]] = None,
        permissions: Dict[str, str] = None,
        if_condition: str = None,
        custom_steps: List[Dict[str, Any]] = None,
    ) -> "CICDPipelineBuilder":
        """
        Add job to pipeline.

        Args:
            name: Job name
            languages: Programming languages
            job_type: Job type
            runs_on: Runner
            needs: Dependencies
            timeout: Timeout in minutes
            matrix: Strategy matrix axes, e.g. {"python-version": [...]}
            permissions: Job-scoped permissions override
            if_condition: Conditional execution
            custom_steps: Explicit steps, bypassing language/job-type
                inference — used for jobs (docker publish, PyPI release)
                too specific for the generic step generator.

        Returns:
            Self for fluent interface
        """
        steps = (
            custom_steps
            if custom_steps is not None
            else self._generate_steps(name, languages, job_type)
        )

        job = JobConfig(
            name=name,
            job_type=JobType(job_type),
            runs_on=runs_on,
            steps=steps,
            needs=needs or [],
            timeout=timeout,
            matrix=matrix or {},
            permissions=permissions or {},
            if_condition=if_condition,
        )

        self._jobs.append(job)
        return self

    def _generate_steps(
        self,
        name: str,
        languages: List[str],
        job_type: str,
    ) -> List[Dict[str, Any]]:
        """Generate job steps based on language and type."""
        languages = languages or []
        steps = []

        if job_type == "build":
            if "node" in languages:
                steps.extend(
                    [
                        {"name": "Setup Node.js", "run": "node --version"},
                        {"name": "Install dependencies", "run": "npm ci"},
                        {"name": "Build", "run": "npm run build"},
                    ]
                )
            if "python" in languages:
                steps.extend(
                    [
                        {"name": "Setup Python", "run": "python --version"},
                        {"name": "Install dependencies", "run": "pip install -r requirements.txt"},
                        {"name": "Build", "run": "python setup.py build"},
                    ]
                )

        elif job_type == "test":
            if "node" in languages:
                steps.extend(
                    [
                        {"name": "Setup Node.js", "run": "node --version"},
                        {"name": "Install dependencies", "run": "npm ci"},
                        {"name": "Run tests", "run": "npm test"},
                    ]
                )
            if "python" in languages:
                cov_suffix = (
                    f" --cov-fail-under={self._cov_fail_under}"
                    if self._cov_fail_under is not None
                    else ""
                )
                steps.extend(
                    [
                        {"name": "Setup Python", "run": "python --version"},
                        {"name": "Install dependencies", "run": 'pip install -e ".[dev]"'},
                        {
                            "name": "Run tests with coverage",
                            "run": (f"pytest --cov --cov-report=xml --cov-report=term{cov_suffix}"),
                        },
                        {
                            "uses": "codecov/codecov-action@v3",
                            "with": {"file": "./coverage.xml", "fail_ci_if_error": "false"},
                        },
                    ]
                )

        elif job_type == "lint":
            if "node" in languages:
                steps.extend(
                    [
                        {"name": "Setup Node.js", "run": "node --version"},
                        {"name": "Install dependencies", "run": "npm ci"},
                        {"name": "Run linter", "run": "npm run lint"},
                    ]
                )
            if "python" in languages:
                steps.extend(
                    [
                        {"name": "Setup Python", "run": "python --version"},
                        {"name": "Install dependencies", "run": 'pip install -e ".[dev]"'},
                        {"name": "Run ruff", "run": "ruff check src/ tests/"},
                        {"name": "Check formatting", "run": "black --check src/ tests/"},
                        {"name": "Type check", "run": "mypy src/"},
                    ]
                )

        elif job_type == "security_scan":
            if "python" in languages:
                steps.extend(
                    [
                        {"name": "Setup Python", "run": "python --version"},
                        {
                            "name": "Install Bandit",
                            "run": 'pip install "bandit[toml]>=1.7.0"',
                        },
                        # No `|| true`: a security scan that cannot fail the
                        # build is not a check (retires G-3).
                        {"name": "Run Bandit", "run": "bandit -r src/"},
                    ]
                )

        elif job_type == "dependency_audit":
            if "python" in languages:
                steps.extend(
                    [
                        {"name": "Setup Python", "run": "python --version"},
                        {"name": "Install pip-audit", "run": "pip install pip-audit"},
                        # pip-audit exits non-zero on any known vulnerability
                        # by default — no severity filter is applied, which
                        # is a strict superset of "fails on HIGH" (retires G-5).
                        {"name": "Run pip-audit", "run": "pip-audit"},
                    ]
                )

        elif job_type == "vulnerability_scan":
            steps.append(
                {
                    "uses": "aquasecurity/trivy-action@0.24.0",
                    "with": {
                        "scan-type": "fs",
                        "severity": "HIGH,CRITICAL",
                        "exit-code": "1",
                    },
                }
            )

        elif job_type == "deploy":
            steps.extend(
                [
                    {"name": "Deploy", "run": "echo 'Deploying...'"},
                ]
            )

        return steps

    def build(self) -> str:
        """
        Build CI/CD configuration.

        Returns:
            Configuration file content
        """
        config = PipelineConfig(
            name=self._name,
            provider=self._provider,
            branches=self._branches,
            jobs=self._jobs,
            environment_variables=self._env_vars,
            secrets=self._secrets,
            concurrency_group=self._concurrency_group,
            action_pins=self._action_pins,
        )

        return self._strategy.generate(config)

    def build_to_file(self, filepath: str) -> str:
        """
        Build and write to file.

        Args:
            filepath: Output file path

        Returns:
            File path
        """
        content = self.build()

        with open(filepath, "w") as f:
            f.write(content)

        return filepath


# ═══════════════════════════════════════════════════════════════════
# CONVENIENCE FUNCTIONS
# ═══════════════════════════════════════════════════════════════════


def create_github_actions_pipeline(
    name: str = "CI/CD Pipeline",
    languages: List[str] = None,
) -> str:
    """
    Create GitHub Actions pipeline.

    Args:
        name: Pipeline name
        languages: Programming languages

    Returns:
        Workflow file content
    """
    builder = CICDPipelineBuilder().for_github_actions().with_name(name)

    if languages:
        builder.add_job("build", languages, "build")
        builder.add_job("test", languages, "test", needs=["build"])
        builder.add_job("lint", languages, "lint", needs=["build"])

    return builder.build()


def create_gitlab_ci_pipeline(
    name: str = "CI/CD Pipeline",
    languages: List[str] = None,
) -> str:
    """
    Create GitLab CI pipeline.

    Args:
        name: Pipeline name
        languages: Programming languages

    Returns:
        CI file content
    """
    builder = CICDPipelineBuilder().for_gitlab_ci().with_name(name)

    if languages:
        builder.add_job("build", languages, "build")
        builder.add_job("test", languages, "test", needs=["build"])

    return builder.build()


def create_azure_devops_pipeline(
    name: str = "CI/CD Pipeline",
    languages: List[str] = None,
) -> str:
    """
    Create Azure DevOps pipeline.

    Args:
        name: Pipeline name
        languages: Programming languages

    Returns:
        Pipeline file content
    """
    builder = CICDPipelineBuilder().for_azure_devops().with_name(name)

    if languages:
        builder.add_job("build", languages, "build")
        builder.add_job("test", languages, "test", needs=["build"])

    return builder.build()
