"""
CI/CD Generator — Builder + Strategy Pattern
=============================================
Author: Georgios-Chrysovalantis Chatzivantsidis

CI/CD pipeline generation using Builder Pattern for pipeline construction
and Strategy Pattern for different CI/CD providers.

Paradigm: OOP with Functional utilities
Patterns: Builder, Strategy, Factory Method, Template Method

Usage:
    from orchestrator.cicd_generator import CICDPipelineBuilder

    pipeline = (CICDPipelineBuilder()
        .for_github_actions()
        .add_job("build", ["node", "python"])
        .add_job("test", ["node"])
        .add_job("deploy", ["node"], needs=["build", "test"])
        .build())
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from enum import Enum

# ═══════════════════════════════════════════════════════════════════
# IMMUTABLE DATA CLASSES
# ═══════════════════════════════════════════════════════════════════


class CICDProvider(str, Enum):
    """CI/CD provider enumeration."""

    GITHUB_ACTIONS = "github_actions"
    GITLAB_CI = "gitlab_ci"
    AZURE_DEVOPS = "azure_devops"
    JENKINS = "jenkins"
    CIRCLE_CI = "circle_ci"


class JobType(str, Enum):
    """Job type enumeration."""

    BUILD = "build"
    TEST = "test"
    LINT = "lint"
    DEPLOY = "deploy"
    SECURITY_SCAN = "security_scan"
    RELEASE = "release"


@dataclass(frozen=True)
class JobConfig:
    """
    Immutable job configuration.

    Attributes:
        name: Job name
        job_type: Type of job
        runs_on: Runner/executor
        steps: Job steps
        needs: Dependencies (other jobs)
        if_condition: Conditional execution
        timeout: Timeout in minutes
    """

    name: str
    job_type: JobType
    runs_on: str = "ubuntu-latest"
    steps: List[Dict[str, Any]] = field(default_factory=list)
    needs: List[str] = field(default_factory=list)
    if_condition: Optional[str] = None
    timeout: int = 60


@dataclass(frozen=True)
class PipelineConfig:
    """
    Immutable pipeline configuration.

    Attributes:
        name: Pipeline name
        provider: CI/CD provider
        branches: Target branches
        jobs: Pipeline jobs
        environment_variables: Environment variables
        secrets: Required secrets
    """

    name: str
    provider: CICDProvider
    branches: List[str] = field(default_factory=lambda: ["main", "develop"])
    jobs: List[JobConfig] = field(default_factory=list)
    environment_variables: Dict[str, str] = field(default_factory=dict)
    secrets: List[str] = field(default_factory=list)


# ═══════════════════════════════════════════════════════════════════
# STRATEGY PATTERN — CI/CD PROVIDER STRATEGIES
# ═══════════════════════════════════════════════════════════════════


class CICDStrategy(ABC):
    """
    Strategy Pattern for CI/CD providers.

    Subclasses implement different CI/CD provider configurations.
    """

    @abstractmethod
    def generate(self, config: PipelineConfig) -> str:
        """
        Generate CI/CD configuration.

        Args:
            config: Pipeline configuration

        Returns:
            Configuration file content
        """
        pass

    @abstractmethod
    def get_provider(self) -> CICDProvider:
        """
        Get provider name.

        Returns:
            CI/CD provider
        """
        pass


class GitHubActionsStrategy(CICDStrategy):
    """
    GitHub Actions strategy.
    """

    def generate(self, config: PipelineConfig) -> str:
        """Generate GitHub Actions workflow."""
        workflow = f"""# {config.name}
# Generated by AI Orchestrator

name: {config.name}

on:
  push:
    branches: [{', '.join(config.branches)}]
  pull_request:
    branches: [{', '.join(config.branches)}]

"""

        # Add environment variables
        if config.environment_variables:
            workflow += "\nenv:\n"
            for key, value in config.environment_variables.items():
                workflow += f"  {key}: {value}\n"

        # Add jobs
        workflow += "\njobs:\n"

        for job in config.jobs:
            workflow += self._generate_job(job, config.secrets)

        return workflow

    def _generate_job(self, job: JobConfig, secrets: List[str]) -> str:
        """Generate job configuration."""
        job_yaml = f"  {job.name}:\n"
        job_yaml += f"    runs-on: {job.runs_on}\n"

        if job.needs:
            job_yaml += f"    needs: [{', '.join(job.needs)}]\n"

        if job.if_condition:
            job_yaml += f"    if: {job.if_condition}\n"

        job_yaml += f"    timeout-minutes: {job.timeout}\n"

        # Add steps
        job_yaml += "    steps:\n"
        job_yaml += "      - uses: actions/checkout@v4\n"

        for step in job.steps:
            if "uses" in step:
                job_yaml += f"      - uses: {step['uses']}\n"
                if "with" in step:
                    job_yaml += "        with:\n"
                    for key, value in step["with"].items():
                        job_yaml += f"          {key}: {value}\n"
            elif "run" in step:
                job_yaml += f"      - name: {step.get('name', 'Run command')}\n"
                job_yaml += f"        run: {step['run']}\n"

        return job_yaml

    def get_provider(self) -> CICDProvider:
        """Get provider name."""
        return CICDProvider.GITHUB_ACTIONS


class GitLabCIStrategy(CICDStrategy):
    """
    GitLab CI strategy.
    """

    def generate(self, config: PipelineConfig) -> str:
        """Generate GitLab CI configuration."""
        ci_yaml = f"# {config.name}\n"
        ci_yaml += "# Generated by AI Orchestrator\n\n"

        # Add variables
        if config.environment_variables:
            ci_yaml += "variables:\n"
            for key, value in config.environment_variables.items():
                ci_yaml += f"  {key}: {value}\n"
            ci_yaml += "\n"

        # Add stages
        stages = list(set(job.job_type.value for job in config.jobs))
        ci_yaml += f"stages:\n  - {'.stages'.join(stages)}\n\n"

        # Add jobs
        for job in config.jobs:
            ci_yaml += self._generate_job(job)

        return ci_yaml

    def _generate_job(self, job: JobConfig) -> str:
        """Generate job configuration."""
        job_yaml = f"{job.name}:\n"
        job_yaml += f"  stage: {job.job_type.value}\n"
        job_yaml += f"  image: {job.runs_on}\n"

        if job.needs:
            job_yaml += f"  needs: [{', '.join(job.needs)}]\n"

        if job.if_condition:
            job_yaml += f"  rules:\n    - if: {job.if_condition}\n"

        # Add scripts
        job_yaml += "  script:\n"
        for step in job.steps:
            if "run" in step:
                job_yaml += f"    - {step['run']}\n"

        job_yaml += "\n"
        return job_yaml

    def get_provider(self) -> CICDProvider:
        """Get provider name."""
        return CICDProvider.GITLAB_CI


class AzureDevOpsStrategy(CICDStrategy):
    """
    Azure DevOps strategy.
    """

    def generate(self, config: PipelineConfig) -> str:
        """Generate Azure DevOps pipeline."""
        pipeline = f"""# {config.name}
# Generated by AI Orchestrator

trigger:
  branches:
    include: [{', '.join(config.branches)}]

pool:
  vmImage: 'ubuntu-latest'

"""

        # Add jobs
        pipeline += "jobs:\n"

        for job in config.jobs:
            pipeline += self._generate_job(job)

        return pipeline

    def _generate_job(self, job: JobConfig) -> str:
        """Generate job configuration."""
        job_yaml = f"  - job: {job.name.replace('-', '_')}\n"
        job_yaml += f"    displayName: '{job.name}'\n"
        job_yaml += f"    timeoutInMinutes: {job.timeout}\n"

        if job.needs:
            job_yaml += f"    dependsOn: [{', '.join(job.needs)}]\n"

        job_yaml += "    steps:\n"
        job_yaml += "      - checkout: self\n"

        for step in job.steps:
            if "run" in step:
                job_yaml += f"      - script: {step['run']}\n"
                if "name" in step:
                    job_yaml += f"        displayName: {step['name']}\n"

        return job_yaml

    def get_provider(self) -> CICDProvider:
        """Get provider name."""
        return CICDProvider.AZURE_DEVOPS


# ═══════════════════════════════════════════════════════════════════
# BUILDER PATTERN — CI/CD PIPELINE BUILDER
# ═══════════════════════════════════════════════════════════════════


class CICDPipelineBuilder:
    """
    Builder Pattern for CI/CD pipelines.

    Fluent interface for constructing CI/CD configurations.

    Usage:
        pipeline = (CICDPipelineBuilder()
            .for_github_actions()
            .add_job("build", ["node"])
            .add_job("test", ["node"])
            .build())
    """

    def __init__(self):
        """Initialize builder."""
        self._name: str = "CI/CD Pipeline"
        self._provider: CICDProvider = CICDProvider.GITHUB_ACTIONS
        self._branches: List[str] = ["main", "develop"]
        self._jobs: List[JobConfig] = []
        self._env_vars: Dict[str, str] = {}
        self._secrets: List[str] = []
        self._strategy: CICDStrategy = GitHubActionsStrategy()

    def for_github_actions(self) -> "CICDPipelineBuilder":
        """Configure for GitHub Actions."""
        self._provider = CICDProvider.GITHUB_ACTIONS
        self._strategy = GitHubActionsStrategy()
        return self

    def for_gitlab_ci(self) -> "CICDPipelineBuilder":
        """Configure for GitLab CI."""
        self._provider = CICDProvider.GITLAB_CI
        self._strategy = GitLabCIStrategy()
        return self

    def for_azure_devops(self) -> "CICDPipelineBuilder":
        """Configure for Azure DevOps."""
        self._provider = CICDProvider.AZURE_DEVOPS
        self._strategy = AzureDevOpsStrategy()
        return self

    def with_name(self, name: str) -> "CICDPipelineBuilder":
        """Set pipeline name."""
        self._name = name
        return self

    def with_branches(self, branches: List[str]) -> "CICDPipelineBuilder":
        """Set target branches."""
        self._branches = branches
        return self

    def add_env_var(self, key: str, value: str) -> "CICDPipelineBuilder":
        """Add environment variable."""
        self._env_vars[key] = value
        return self

    def add_secret(self, secret: str) -> "CICDPipelineBuilder":
        """Add required secret."""
        self._secrets.append(secret)
        return self

    def add_job(
        self,
        name: str,
        languages: List[str] = None,
        job_type: str = "build",
        runs_on: str = "ubuntu-latest",
        needs: List[str] = None,
        timeout: int = 60,
    ) -> "CICDPipelineBuilder":
        """
        Add job to pipeline.

        Args:
            name: Job name
            languages: Programming languages
            job_type: Job type
            runs_on: Runner
            needs: Dependencies
            timeout: Timeout in minutes

        Returns:
            Self for fluent interface
        """
        steps = self._generate_steps(name, languages, job_type)

        job = JobConfig(
            name=name,
            job_type=JobType(job_type),
            runs_on=runs_on,
            steps=steps,
            needs=needs or [],
            timeout=timeout,
        )

        self._jobs.append(job)
        return self

    def _generate_steps(
        self,
        name: str,
        languages: List[str],
        job_type: str,
    ) -> List[Dict[str, Any]]:
        """Generate job steps based on language and type."""
        steps = []

        if job_type == "build":
            if "node" in languages:
                steps.extend(
                    [
                        {"name": "Setup Node.js", "run": "node --version"},
                        {"name": "Install dependencies", "run": "npm ci"},
                        {"name": "Build", "run": "npm run build"},
                    ]
                )
            if "python" in languages:
                steps.extend(
                    [
                        {"name": "Setup Python", "run": "python --version"},
                        {"name": "Install dependencies", "run": "pip install -r requirements.txt"},
                        {"name": "Build", "run": "python setup.py build"},
                    ]
                )

        elif job_type == "test":
            if "node" in languages:
                steps.extend(
                    [
                        {"name": "Setup Node.js", "run": "node --version"},
                        {"name": "Install dependencies", "run": "npm ci"},
                        {"name": "Run tests", "run": "npm test"},
                    ]
                )
            if "python" in languages:
                steps.extend(
                    [
                        {"name": "Setup Python", "run": "python --version"},
                        {"name": "Install dependencies", "run": "pip install -r requirements.txt"},
                        {"name": "Run tests", "run": "pytest"},
                    ]
                )

        elif job_type == "lint":
            if "node" in languages:
                steps.extend(
                    [
                        {"name": "Setup Node.js", "run": "node --version"},
                        {"name": "Install dependencies", "run": "npm ci"},
                        {"name": "Run linter", "run": "npm run lint"},
                    ]
                )

        elif job_type == "deploy":
            steps.extend(
                [
                    {"name": "Deploy", "run": "echo 'Deploying...'"},
                ]
            )

        return steps

    def build(self) -> str:
        """
        Build CI/CD configuration.

        Returns:
            Configuration file content
        """
        config = PipelineConfig(
            name=self._name,
            provider=self._provider,
            branches=self._branches,
            jobs=self._jobs,
            environment_variables=self._env_vars,
            secrets=self._secrets,
        )

        return self._strategy.generate(config)

    def build_to_file(self, filepath: str) -> str:
        """
        Build and write to file.

        Args:
            filepath: Output file path

        Returns:
            File path
        """
        content = self.build()

        with open(filepath, "w") as f:
            f.write(content)

        return filepath


# ═══════════════════════════════════════════════════════════════════
# CONVENIENCE FUNCTIONS
# ═══════════════════════════════════════════════════════════════════


def create_github_actions_pipeline(
    name: str = "CI/CD Pipeline",
    languages: List[str] = None,
) -> str:
    """
    Create GitHub Actions pipeline.

    Args:
        name: Pipeline name
        languages: Programming languages

    Returns:
        Workflow file content
    """
    builder = CICDPipelineBuilder().for_github_actions().with_name(name)

    if languages:
        builder.add_job("build", languages, "build")
        builder.add_job("test", languages, "test", needs=["build"])
        builder.add_job("lint", languages, "lint", needs=["build"])

    return builder.build()


def create_gitlab_ci_pipeline(
    name: str = "CI/CD Pipeline",
    languages: List[str] = None,
) -> str:
    """
    Create GitLab CI pipeline.

    Args:
        name: Pipeline name
        languages: Programming languages

    Returns:
        CI file content
    """
    builder = CICDPipelineBuilder().for_gitlab_ci().with_name(name)

    if languages:
        builder.add_job("build", languages, "build")
        builder.add_job("test", languages, "test", needs=["build"])

    return builder.build()


def create_azure_devops_pipeline(
    name: str = "CI/CD Pipeline",
    languages: List[str] = None,
) -> str:
    """
    Create Azure DevOps pipeline.

    Args:
        name: Pipeline name
        languages: Programming languages

    Returns:
        Pipeline file content
    """
    builder = CICDPipelineBuilder().for_azure_devops().with_name(name)

    if languages:
        builder.add_job("build", languages, "build")
        builder.add_job("test", languages, "test", needs=["build"])

    return builder.build()
