"""
Logging Generator — Strategy + Builder Pattern
===============================================
Author: Georgios-Chrysovalantis Chatzivantsidis

Logging configuration generation using Strategy Pattern for different frameworks
and Builder Pattern for logger construction.

Paradigm: OOP with Functional utilities
Patterns: Strategy, Builder, Factory Method, Template Method

Usage:
    from orchestrator.generators.logging_generator import LoggingConfigBuilder

    config = (LoggingConfigBuilder()
        .for_node()
        .with_winston()
        .add_file_transport()
        .add_console_transport()
        .build())
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from enum import Enum

# ═══════════════════════════════════════════════════════════════
# IMMUTABLE DATA CLASSES
# ═══════════════════════════════════════════════════════════════


class LogLevel(str, Enum):
    """Log level enumeration."""

    DEBUG = "debug"
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class LogFormat(str, Enum):
    """Log format enumeration."""

    JSON = "json"
    TEXT = "text"
    SYSLOG = "syslog"


@dataclass(frozen=True)
class LoggingConfig:
    """
    Immutable logging configuration.

    Attributes:
        language: Programming language
        framework: Logging framework
        level: Minimum log level
        format: Log format
        include_timestamp: Include timestamp
        include_caller: Include caller info
        transports: Log transports
        rotation: Log rotation settings
        correlation_id: Thread a per-request correlation id (via contextvars)
            into every emitted log record (Phase 7, P-6)
    """

    language: str = "typescript"
    framework: str = "winston"
    level: LogLevel = LogLevel.INFO
    format: LogFormat = LogFormat.JSON
    include_timestamp: bool = True
    include_caller: bool = True
    transports: List[Dict[str, Any]] = field(default_factory=list)
    rotation: Optional[Dict[str, Any]] = None
    correlation_id: bool = False


# ═══════════════════════════════════════════════════════════════
# STRATEGY PATTERN — LOGGING STRATEGIES
# ═══════════════════════════════════════════════════════════════


class LoggingStrategy(ABC):
    """Strategy for logging framework generation."""

    @abstractmethod
    def generate(self, config: LoggingConfig) -> str:
        """Generate logging configuration."""
        pass

    @abstractmethod
    def get_framework(self) -> str:
        """Get framework name."""
        pass


class WinstonLoggingStrategy(LoggingStrategy):
    """Winston (Node.js) logging strategy."""

    def generate(self, config: LoggingConfig) -> str:
        """Generate Winston configuration."""
        format_type = "json()" if config.format == LogFormat.JSON else "simple()"

        # Build printf format line for TEXT format
        printf_line = ""
        if config.format == LogFormat.TEXT:
            printf_line = "  winston.format.printf((info) => `[${info.timestamp}] ${info.level}: ${info.message}`)"
            if config.include_caller:
                printf_line += " + ` (${info.file}:${info.line})`"
            printf_line += ",\n"

        code = f"""/**
 * Winston Logger Configuration
 * Generated by AI Orchestrator
 */

import winston from 'winston';
import path from 'path';

// ═══════════════════════════════════════════════════════════════
// Log Levels
// ═══════════════════════════════════════════════════════════════

const logLevels = {{
  debug: 0,
  info: 1,
  warning: 2,
  error: 3,
  critical: 4,
}};

// ═══════════════════════════════════════════════════════════════
// Custom Format
// ═══════════════════════════════════════════════════════════════

const customFormat = winston.format.combine(
  winston.format.timestamp({{ format: 'YYYY-MM-DD HH:mm:ss' }}),
  winston.format.errors({{ stack: true }}),
  winston.format.{format_type}
{printf_line}
);

// ═══════════════════════════════════════════════════════════════
// Transports
// ═══════════════════════════════════════════════════════════════

const transports = [
  // Console transport
  new winston.transports.Console({{
    level: '{config.level.value}',
    format: customFormat,
  }}),
"""

        if any(t.get("type") == "file" for t in config.transports):
            code += """
  // File transport
  new winston.transports.File({{
    filename: path.join('logs', 'error.log'),
    level: 'error',
    format: customFormat,
  }}),
  new winston.transports.File({{
    filename: path.join('logs', 'combined.log'),
    format: customFormat,
  }}),
"""

        code += """];

// ═══════════════════════════════════════════════════════════════
// Logger
// ═══════════════════════════════════════════════════════════════

const logger = winston.createLogger({{
  level: '{config.level.value}',
  levels: logLevels,
  transports,
  defaultMeta: {{ service: 'app' }},
}});

// ═══════════════════════════════════════════════════════════════
// Helper Functions
// ═══════════════════════════════════════════════════════════════

export function logWithMeta(
  level: string,
  message: string,
  meta?: Record<string, any>,
) {{
  logger.log({{ level, message, meta }});
}}

export function logError(
  error: Error,
  context?: Record<string, any>,
) {{
  logger.error({{
    message: error.message,
    stack: error.stack,
    ...context,
  }});
}}

// ═══════════════════════════════════════════════════════════════
// Export
// ═══════════════════════════════════════════════════════════════

export default logger;
export {{ logger, logWithMeta, logError }};
"""

        return code

    def get_framework(self) -> str:
        return "winston"


class PinoLoggingStrategy(LoggingStrategy):
    """Pino (Node.js) logging strategy."""

    def generate(self, config: LoggingConfig) -> str:
        """Generate Pino configuration."""
        return f"""/**
 * Pino Logger Configuration
 * Generated by AI Orchestrator
 */

import pino from 'pino';
import path from 'path';
import {{ createWriteStream }} from 'fs';

const logger = pino({{
  level: '{config.level.value}',
  timestamp: pino.stdTimeFunctions.isoTime,
  formatters: {{
    level: (label) => ({{ level: label.toUpperCase() }}),
  }},
  transport: {{
    targets: [
      {{
        target: 'pino-pretty',
        options: {{ destination: 1 }},
        level: '{config.level.value}',
      }},
      {{
        target: 'pino/file',
        options: {{
          destination: path.join('logs', 'app.log'),
          rotate: true,
        }},
        level: 'info',
      }},
    ],
  }},
}});

export default logger;
"""

    def get_framework(self) -> str:
        return "pino"


class LoguruLoggingStrategy(LoggingStrategy):
    """Loguru (Python) logging strategy."""

    def generate(self, config: LoggingConfig) -> str:
        """Generate Loguru configuration."""
        return f'''"""
Loguru Logger Configuration
Generated by AI Orchestrator
"""

import sys
from loguru import logger
from datetime import datetime
import os

# ═══════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════

# Remove default handler
logger.remove()

# Add console handler
logger.add(
    sys.stderr,
    level="{config.level.value.upper()}",
    format="<green>{{time:YYYY-MM-DD HH:mm:ss}}</green> | <level>{{level: <8}}</level> | <cyan>{{name}}</cyan>:<cyan>{{function}}</cyan>:<cyan>{{line}}</cyan> - <level>{{message}}</level>",
    colorize=True,
    backtrace=True,
    diagnose=True,
)

# Add file handler with rotation
log_dir = os.path.join(os.path.dirname(__file__), 'logs')
os.makedirs(log_dir, exist_ok=True)

logger.add(
    os.path.join(log_dir, "app_{{time:YYYY-MM-DD}}.log"),
    level="INFO",
    rotation="00:00",
    retention="7 days",
    compression="zip",
    format="{{time:YYYY-MM-DD HH:mm:ss}} | {{level: <8}} | {{name}}:{{function}}:{{line}} - {{message}}",
    backtrace=True,
    diagnose=True,
)

# Add error file handler
logger.add(
    os.path.join(log_dir, "errors.log"),
    level="ERROR",
    rotation="10 MB",
    retention="30 days",
    compression="zip",
    format="{{time:YYYY-MM-DD HH:mm:ss}} | {{level: <8}} | {{name}}:{{function}}:{{line}} - {{message}}\n{{exception}}",
    backtrace=True,
    diagnose=True,
)

# ═══════════════════════════════════════════════════════════════
# Helper Functions
# ═══════════════════════════════════════════════════════════════

def log_with_context(level: str, message: str, **context):
    """Log with additional context."""
    logger.bind(**context).log(level, message)

def log_error(error: Exception, **context):
    """Log error with context."""
    logger.bind(**context).exception(error)

# ═══════════════════════════════════════════════════════════════
# Export
# ═══════════════════════════════════════════════════════════════

__all__ = ["logger", "log_with_context", "log_error"]
'''

    def get_framework(self) -> str:
        return "loguru"


class PythonLoggingStrategy(LoggingStrategy):
    """Standard Python logging strategy."""

    def generate(self, config: LoggingConfig) -> str:
        """Generate Python logging configuration."""
        if config.format == LogFormat.JSON:
            return self._generate_json(config)
        return self._generate_text(config)

    def _generate_text(self, config: LoggingConfig) -> str:
        return f'''"""
Python Logging Configuration
Generated by AI Orchestrator
"""

import logging
import sys
import os
from logging.handlers import RotatingFileHandler, TimedRotatingFileHandler
from datetime import datetime

# ═══════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════

LOG_LEVEL = logging.{config.level.value.upper()}
LOG_FORMAT = "%(asctime)s | %(levelname)-8s | %(name)s:%(funcName)s:%(lineno)d - %(message)s"
LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"

# ═══════════════════════════════════════════════════════════════
# Logger Setup
# ═══════════════════════════════════════════════════════════════

def setup_logger(name: str = "app") -> logging.Logger:
    """Set up logger with console and file handlers."""
    logger = logging.getLogger(name)
    logger.setLevel(LOG_LEVEL)

    # Create formatter
    formatter = logging.Formatter(LOG_FORMAT, datefmt=LOG_DATE_FORMAT)

    # Console handler
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setLevel(LOG_LEVEL)
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)

    # File handler with rotation
    log_dir = os.path.join(os.path.dirname(__file__), "logs")
    os.makedirs(log_dir, exist_ok=True)

    file_handler = RotatingFileHandler(
        os.path.join(log_dir, f"{{name}}.log"),
        maxBytes=10*1024*1024,  # 10 MB
        backupCount=5,
    )
    file_handler.setLevel(LOG_LEVEL)
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)

    return logger

# ═══════════════════════════════════════════════════════════════
# Helper Functions
# ═══════════════════════════════════════════════════════════════

def get_logger(name: str = "app") -> logging.Logger:
    """Get logger instance."""
    return setup_logger(name)

def log_with_context(
    logger: logging.Logger,
    level: str,
    message: str,
    **context,
):
    """Log with additional context."""
    extra = {{k: v for k, v in context.items()}}
    logger.log(getattr(logging, level.upper()), message, extra=extra)

# ═══════════════════════════════════════════════════════════════
# Export
# ═══════════════════════════════════════════════════════════════

__all__ = ["setup_logger", "get_logger", "log_with_context"]
'''

    def _generate_json(self, config: LoggingConfig) -> str:
        correlation_var = ""
        correlation_field = ""
        correlation_export = ""
        if config.correlation_id:
            correlation_var = (
                "\nfrom contextvars import ContextVar\n\n"
                'correlation_id_var: ContextVar[str] = ContextVar("correlation_id", default="")\n'
            )
            correlation_field = (
                '        payload["correlation_id"] = getattr('
                'record, "correlation_id", None) or correlation_id_var.get("")\n'
            )
            correlation_export = ', "correlation_id_var"'

        return f'''"""
Structured JSON Logging Configuration
Generated by AI Orchestrator
"""

import json
import logging
import sys
import os
from logging.handlers import RotatingFileHandler
{correlation_var}
# ═══════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════

LOG_LEVEL = logging.{config.level.value.upper()}

# ═══════════════════════════════════════════════════════════════
# JSON Formatter
# ═══════════════════════════════════════════════════════════════

class JsonFormatter(logging.Formatter):
    """Renders one JSON object per log record — never a %-formatted line."""

    def format(self, record: logging.LogRecord) -> str:
        payload = {{
            "timestamp": self.formatTime(record, "%Y-%m-%dT%H:%M:%S%z"),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
        }}
{correlation_field}        if record.exc_info:
            payload["exception"] = self.formatException(record.exc_info)
        return json.dumps(payload)

# ═══════════════════════════════════════════════════════════════
# Logger Setup
# ═══════════════════════════════════════════════════════════════

def setup_logger(name: str = "app") -> logging.Logger:
    """Set up logger with JSON console and file handlers."""
    logger = logging.getLogger(name)
    logger.setLevel(LOG_LEVEL)

    formatter = JsonFormatter()

    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setLevel(LOG_LEVEL)
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)

    log_dir = os.path.join(os.path.dirname(__file__), "logs")
    os.makedirs(log_dir, exist_ok=True)

    file_handler = RotatingFileHandler(
        os.path.join(log_dir, f"{{name}}.log"),
        maxBytes=10*1024*1024,  # 10 MB
        backupCount=5,
    )
    file_handler.setLevel(LOG_LEVEL)
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)

    return logger

# ═══════════════════════════════════════════════════════════════
# Helper Functions
# ═══════════════════════════════════════════════════════════════

def get_logger(name: str = "app") -> logging.Logger:
    """Get logger instance."""
    return setup_logger(name)

def log_with_context(
    logger: logging.Logger,
    level: str,
    message: str,
    **context,
):
    """Log with additional context."""
    extra = {{k: v for k, v in context.items()}}
    logger.log(getattr(logging, level.upper()), message, extra=extra)

# ═══════════════════════════════════════════════════════════════
# Export
# ═══════════════════════════════════════════════════════════════

__all__ = ["setup_logger", "get_logger", "log_with_context", "JsonFormatter"{correlation_export}]
'''

    def get_framework(self) -> str:
        return "logging"


# ═══════════════════════════════════════════════════════════════
# BUILDER PATTERN — LOGGING CONFIG BUILDER
# ═══════════════════════════════════════════════════════════════


class LoggingConfigBuilder:
    """
    Builder for logging configuration.

    Fluent interface for constructing logging configs.
    """

    def __init__(self):
        """Initialize builder."""
        self._language: str = "typescript"
        self._framework: str = "winston"
        self._level: LogLevel = LogLevel.INFO
        self._format: LogFormat = LogFormat.JSON
        self._transports: List[Dict[str, Any]] = []
        self._rotation: Optional[Dict[str, Any]] = None
        self._correlation_id: bool = False

    def for_node(self) -> "LoggingConfigBuilder":
        """Configure for Node.js."""
        self._language = "typescript"
        return self

    def for_python(self) -> "LoggingConfigBuilder":
        """Configure for Python."""
        self._language = "python"
        return self

    def with_winston(self) -> "LoggingConfigBuilder":
        """Use Winston framework."""
        self._framework = "winston"
        return self

    def with_pino(self) -> "LoggingConfigBuilder":
        """Use Pino framework."""
        self._framework = "pino"
        return self

    def with_loguru(self) -> "LoggingConfigBuilder":
        """Use Loguru framework."""
        self._framework = "loguru"
        return self

    def with_standard_logging(self) -> "LoggingConfigBuilder":
        """Use standard Python logging."""
        self._framework = "logging"
        return self

    def with_level(self, level: LogLevel) -> "LoggingConfigBuilder":
        """Set log level."""
        self._level = level
        return self

    def with_format(self, format: LogFormat) -> "LoggingConfigBuilder":
        """Set log format."""
        self._format = format
        return self

    def add_console_transport(self) -> "LoggingConfigBuilder":
        """Add console transport."""
        self._transports.append({"type": "console"})
        return self

    def add_file_transport(
        self,
        filename: str = "app.log",
        rotation: str = "daily",
    ) -> "LoggingConfigBuilder":
        """Add file transport."""
        self._transports.append(
            {
                "type": "file",
                "filename": filename,
                "rotation": rotation,
            }
        )
        return self

    def with_correlation_id(self) -> "LoggingConfigBuilder":
        """Thread a per-request correlation id into every JSON log record."""
        self._correlation_id = True
        return self

    def add_rotation(
        self,
        max_size: str = "10MB",
        backup_count: int = 5,
    ) -> "LoggingConfigBuilder":
        """Add log rotation."""
        self._rotation = {
            "max_size": max_size,
            "backup_count": backup_count,
        }
        return self

    def build(self) -> str:
        """Build logging configuration."""
        config = LoggingConfig(
            language=self._language,
            framework=self._framework,
            level=self._level,
            format=self._format,
            transports=self._transports,
            rotation=self._rotation,
            correlation_id=self._correlation_id,
        )

        strategy = self._get_strategy()
        return strategy.generate(config)

    def _get_strategy(self) -> LoggingStrategy:
        """
        Get logging strategy.

        Returns:
            LoggingStrategy for configured framework

        Note: Falls back to Winston with warning for unknown frameworks.
        This is intentional for backwards compatibility, but logs a warning
        so users are aware of the misconfiguration.
        """
        strategies = {
            "winston": WinstonLoggingStrategy(),
            "pino": PinoLoggingStrategy(),
            "loguru": LoguruLoggingStrategy(),
            "logging": PythonLoggingStrategy(),
        }

        # Handle None or missing framework
        if self._framework is None:
            import logging

            logger = logging.getLogger(__name__)
            logger.warning(
                "Logging framework is None. Falling back to Winston. "
                f"Supported frameworks: {list(strategies.keys())}"
            )
            return WinstonLoggingStrategy()

        # Get strategy with validation
        strategy = strategies.get(self._framework)

        if strategy is None:
            import logging

            logger = logging.getLogger(__name__)
            logger.warning(
                f"Unknown logging framework '{self._framework}'. "
                f"Falling back to Winston. Supported frameworks: {list(strategies.keys())}"
            )
            return WinstonLoggingStrategy()

        return strategy


# ═══════════════════════════════════════════════════════════════
# CONVENIENCE FUNCTIONS
# ═══════════════════════════════════════════════════════════════


def create_winston_config() -> str:
    """Create Winston logging configuration."""
    return (
        LoggingConfigBuilder()
        .for_node()
        .with_winston()
        .add_console_transport()
        .add_file_transport()
        .build()
    )


def create_pino_config() -> str:
    """Create Pino logging configuration."""
    return LoggingConfigBuilder().for_node().with_pino().add_console_transport().build()


def create_loguru_config() -> str:
    """Create Loguru logging configuration."""
    return (
        LoggingConfigBuilder()
        .for_python()
        .with_loguru()
        .add_console_transport()
        .add_file_transport()
        .build()
    )


def create_python_logging_config() -> str:
    """Create Python logging configuration."""
    return (
        LoggingConfigBuilder()
        .for_python()
        .with_standard_logging()
        .add_console_transport()
        .add_file_transport()
        .build()
    )
