import { useState, useEffect, useRef, useCallback } from "react";
import { Camera, Send, Paperclip, Play, Eye, Code2, Terminal, FolderTree, Settings, ChevronDown, ChevronRight, X, Maximize2, Minimize2, RotateCcw, ExternalLink, Zap, Shield, Brain, GitBranch, Upload, Mic, Sparkles, Search, LayoutGrid, PanelLeftClose, PanelLeft, Moon, MoreVertical, Check, Loader2, AlertTriangle, Copy, Download, Globe, Cpu, DollarSign, Clock, FileCode, FileText, Folder, ChevronUp, Bot, User, ArrowRight, RefreshCw, Pause, MessageSquare, Layers, Workflow } from "lucide-react";

/* ════════════════════════════════════════
   DESIGN SYSTEM — Obsidian Theme
   Dark, precise, monospace-heavy for dev tools
   ════════════════════════════════════════ */
const DS = {
  bg: "#09090b",
  bgElevated: "#0c0c0f",
  surface: "#111113",
  surfaceHover: "#18181b",
  surfaceActive: "#1f1f23",
  card: "#131316",
  border: "#1c1c21",
  borderHover: "#27272a",
  borderActive: "#3f3f46",
  text: "#fafafa",
  textSecondary: "#a1a1aa",
  textMuted: "#52525b",
  textDim: "#3f3f46",
  accent: "#818cf8",     // Indigo-400
  accentHover: "#6366f1",
  accentMuted: "#818cf815",
  success: "#34d399",
  successMuted: "#34d39915",
  warning: "#fbbf24",
  warningMuted: "#fbbf2415",
  error: "#f87171",
  errorMuted: "#f8717115",
  info: "#38bdf8",
  infoMuted: "#38bdf815",
  mono: "'Berkeley Mono', 'JetBrains Mono', 'SF Mono', 'Cascadia Code', monospace",
  sans: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
  radius: { sm: 6, md: 8, lg: 12 },
};

/* ════════════════════════════════════════
   MOCK DATA
   ════════════════════════════════════════ */
const MODELS = [
  { id: "auto", name: "Auto (Tiered)", desc: "Smart routing", icon: "⚡" },
  { id: "opus", name: "Claude Opus 4.6", desc: "Reasoning", icon: "◆" },
  { id: "sonnet", name: "Claude Sonnet 4.6", desc: "Balanced", icon: "◇" },
  { id: "deepseek", name: "DeepSeek V3.2", desc: "Budget", icon: "●" },
  { id: "gpt54", name: "GPT-5.4", desc: "Tools", icon: "○" },
  { id: "gemini", name: "Gemini 3.1 Pro", desc: "Long context", icon: "◈" },
];

const MODES = [
  { id: "build", name: "Build", icon: Zap, desc: "Generate & execute code" },
  { id: "plan", name: "Plan", icon: Layers, desc: "Plan without executing" },
  { id: "chat", name: "Chat", icon: MessageSquare, desc: "Discuss & brainstorm" },
  { id: "debug", name: "Debug", icon: Search, desc: "Find & fix issues" },
];

const AUTONOMY = [
  { id: "lite", name: "Lite", desc: "Quick, no repair", color: DS.info },
  { id: "standard", name: "Standard", desc: "1 repair, unit tests", color: DS.success },
  { id: "autonomous", name: "Autonomous", desc: "3 repairs, integration", color: DS.warning },
  { id: "max", name: "Max", desc: "5 repairs, 200min", color: DS.error },
];

const INITIAL_FILES = [
  { name: "src", type: "folder", children: [
    { name: "main.py", type: "file", lang: "python" },
    { name: "auth.py", type: "file", lang: "python" },
    { name: "models.py", type: "file", lang: "python" },
    { name: "routes.py", type: "file", lang: "python" },
    { name: "middleware.py", type: "file", lang: "python" },
  ]},
  { name: "tests", type: "folder", children: [
    { name: "test_auth.py", type: "file", lang: "python" },
    { name: "test_routes.py", type: "file", lang: "python" },
  ]},
  { name: "requirements.txt", type: "file", lang: "text" },
  { name: "README.md", type: "file", lang: "markdown" },
  { name: "pyproject.toml", type: "file", lang: "toml" },
];

const MOCK_CODE = `"""FastAPI Authentication Service — Generated by AI Orchestrator v6.2"""
from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel, EmailStr
from datetime import datetime, timedelta
from typing import Optional
import jwt
import bcrypt

app = FastAPI(
    title="Auth Service",
    version="1.0.0",
    docs_url="/docs",
)

# ─── Configuration ───
SECRET_KEY = "your-secret-key-change-in-production"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

security = HTTPBearer()

# ─── Models ───
class UserCreate(BaseModel):
    email: EmailStr
    password: str
    full_name: str

class UserResponse(BaseModel):
    id: int
    email: str
    full_name: str
    created_at: datetime

class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    expires_in: int

# ─── Auth Logic ───
def hash_password(password: str) -> str:
    """Hash password with bcrypt."""
    return bcrypt.hashpw(
        password.encode("utf-8"),
        bcrypt.gensalt(),
    ).decode("utf-8")

def verify_password(plain: str, hashed: str) -> bool:
    """Verify password against hash."""
    return bcrypt.checkpw(
        plain.encode("utf-8"),
        hashed.encode("utf-8"),
    )

def create_access_token(
    data: dict,
    expires_delta: Optional[timedelta] = None,
) -> str:
    """Create JWT access token."""
    to_encode = data.copy()
    expire = datetime.utcnow() + (
        expires_delta or timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    )
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)

# ─── Endpoints ───
@app.post("/auth/register", response_model=UserResponse)
async def register(user: UserCreate):
    """Register a new user."""
    hashed = hash_password(user.password)
    # TODO: Store in database
    return UserResponse(
        id=1,
        email=user.email,
        full_name=user.full_name,
        created_at=datetime.utcnow(),
    )

@app.post("/auth/login", response_model=TokenResponse)
async def login(email: str, password: str):
    """Authenticate and return JWT token."""
    # TODO: Lookup user in database
    token = create_access_token(data={"sub": email})
    return TokenResponse(
        access_token=token,
        expires_in=ACCESS_TOKEN_EXPIRE_MINUTES * 60,
    )
`;

const MOCK_MESSAGES = [
  { role: "user", content: "Build a FastAPI REST API with JWT authentication, user registration, and protected endpoints.", ts: "14:28" },
  { role: "assistant", content: null, ts: "14:28", thinking: true, steps: [
    { label: "Analyzing requirements", done: true },
    { label: "Architecture: Hexagonal + FastAPI + JWT + bcrypt", done: true },
    { label: "Decomposing into 8 tasks", done: true },
    { label: "Routing: DeepSeek V3.2 (code), Claude Sonnet (review)", done: true },
  ]},
  { role: "assistant", content: "I've set up your FastAPI auth service with the following structure:\n\n• **auth.py** — JWT token creation, password hashing with bcrypt\n• **models.py** — Pydantic schemas for User, Token\n• **routes.py** — Register, Login, Protected endpoints\n• **middleware.py** — Auth dependency injection\n• **tests/** — 17 test cases covering all endpoints\n\nAll 8 tasks completed. Quality score: **0.94**. Budget used: **$0.33** of $5.00.\n\nThe API is running in preview. Try the `/docs` endpoint to explore.", ts: "14:31", files: ["src/auth.py", "src/models.py", "src/routes.py"], cost: 0.33, quality: 0.94 },
];

const TERMINAL_LINES = [
  { type: "cmd", text: "$ python -m pytest tests/ -v --tb=short" },
  { type: "out", text: "tests/test_auth.py::test_register_user PASSED" },
  { type: "out", text: "tests/test_auth.py::test_register_duplicate PASSED" },
  { type: "out", text: "tests/test_auth.py::test_login_valid PASSED" },
  { type: "out", text: "tests/test_auth.py::test_login_invalid PASSED" },
  { type: "out", text: "tests/test_auth.py::test_token_creation PASSED" },
  { type: "out", text: "tests/test_routes.py::test_protected_endpoint PASSED" },
  { type: "out", text: "tests/test_routes.py::test_protected_no_token PASSED" },
  { type: "success", text: "17 passed in 1.24s" },
  { type: "cmd", text: "$ ruff check src/" },
  { type: "success", text: "All checks passed!" },
  { type: "cmd", text: "$ uvicorn src.main:app --reload --port 8000" },
  { type: "info", text: "INFO:     Uvicorn running on http://127.0.0.1:8000" },
  { type: "info", text: "INFO:     Started reloader process [12847]" },
];

/* ════════════════════════════════════════
   MICRO COMPONENTS
   ════════════════════════════════════════ */

const Btn = ({ children, variant = "ghost", size = "sm", active, style, ...props }) => {
  const variants = {
    ghost: { bg: "transparent", hover: DS.surfaceHover, border: "transparent", color: DS.textSecondary },
    outline: { bg: "transparent", hover: DS.surfaceHover, border: DS.border, color: DS.textSecondary },
    filled: { bg: DS.accent, hover: DS.accentHover, border: DS.accent, color: "#fff" },
    surface: { bg: DS.surface, hover: DS.surfaceHover, border: DS.border, color: DS.text },
  };
  const v = variants[variant];
  const sizes = { xs: { px: 6, py: 3, fs: 11 }, sm: { px: 10, py: 5, fs: 12 }, md: { px: 14, py: 7, fs: 13 } };
  const s = sizes[size];
  return (
    <button {...props} style={{
      display: "inline-flex", alignItems: "center", gap: 5,
      padding: `${s.py}px ${s.px}px`, borderRadius: DS.radius.sm,
      background: active ? DS.surfaceActive : v.bg,
      border: `1px solid ${active ? DS.borderActive : v.border}`,
      color: active ? DS.text : v.color, fontSize: s.fs,
      fontFamily: DS.sans, fontWeight: 500, cursor: "pointer",
      transition: "all 0.15s ease", lineHeight: 1, whiteSpace: "nowrap",
      ...style,
    }}
      onMouseEnter={e => { if (!active) e.currentTarget.style.background = v.hover; }}
      onMouseLeave={e => { if (!active) e.currentTarget.style.background = active ? DS.surfaceActive : v.bg; }}
    >{children}</button>
  );
};

const Divider = ({ vertical }) => (
  <div style={vertical
    ? { width: 1, background: DS.border, alignSelf: "stretch", margin: "0 2px" }
    : { height: 1, background: DS.border, width: "100%" }
  } />
);

const Badge = ({ children, color = DS.textMuted }) => (
  <span style={{
    padding: "1px 6px", borderRadius: 4, fontSize: 10,
    fontFamily: DS.mono, fontWeight: 500, color,
    background: `${color}12`, border: `1px solid ${color}20`,
    letterSpacing: "0.02em",
  }}>{children}</span>
);

const Dot = ({ color = DS.success, pulse }) => (
  <span style={{ position: "relative", display: "inline-flex", width: 8, height: 8 }}>
    <span style={{ width: 8, height: 8, borderRadius: "50%", background: color }} />
    {pulse && <span style={{
      position: "absolute", inset: -2, borderRadius: "50%",
      border: `1.5px solid ${color}`, opacity: 0.5,
      animation: "ping 2s ease-in-out infinite",
    }} />}
  </span>
);

const Kbd = ({ children }) => (
  <kbd style={{
    padding: "1px 5px", borderRadius: 3, fontSize: 10,
    fontFamily: DS.mono, color: DS.textMuted,
    background: DS.surfaceHover, border: `1px solid ${DS.border}`,
  }}>{children}</kbd>
);

/* ════════════════════════════════════════
   FILE TREE
   ════════════════════════════════════════ */
const FileTreeItem = ({ item, depth = 0, selected, onSelect }) => {
  const [open, setOpen] = useState(true);
  const isFolder = item.type === "folder";
  const Icon = isFolder ? (open ? ChevronDown : ChevronRight) : FileCode;

  return (
    <>
      <div onClick={() => isFolder ? setOpen(!open) : onSelect(item.name)}
        style={{
          display: "flex", alignItems: "center", gap: 5,
          padding: `3px 8px 3px ${12 + depth * 14}px`,
          cursor: "pointer", fontSize: 12, fontFamily: DS.mono,
          color: selected === item.name ? DS.text : DS.textSecondary,
          background: selected === item.name ? DS.surfaceActive : "transparent",
          borderRadius: 4, margin: "1px 4px",
          transition: "background 0.1s",
        }}
        onMouseEnter={e => { if (selected !== item.name) e.currentTarget.style.background = DS.surfaceHover; }}
        onMouseLeave={e => { if (selected !== item.name) e.currentTarget.style.background = "transparent"; }}
      >
        <Icon size={13} style={{ color: isFolder ? DS.warning : DS.textMuted, flexShrink: 0 }} />
        <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{item.name}</span>
      </div>
      {isFolder && open && item.children?.map((child, i) => (
        <FileTreeItem key={i} item={child} depth={depth + 1} selected={selected} onSelect={onSelect} />
      ))}
    </>
  );
};

/* ════════════════════════════════════════
   CHAT MESSAGE
   ════════════════════════════════════════ */
const ChatMessage = ({ msg }) => {
  const isUser = msg.role === "user";

  if (msg.thinking) {
    return (
      <div style={{ padding: "12px 16px", display: "flex", gap: 10 }}>
        <div style={{
          width: 24, height: 24, borderRadius: DS.radius.sm, flexShrink: 0,
          background: `linear-gradient(135deg, ${DS.accent}, ${DS.info})`,
          display: "flex", alignItems: "center", justifyContent: "center",
        }}><Bot size={13} color="#fff" /></div>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 11, color: DS.textMuted, marginBottom: 8, fontFamily: DS.mono }}>Thinking...</div>
          {msg.steps?.map((step, i) => (
            <div key={i} style={{
              display: "flex", alignItems: "center", gap: 6,
              padding: "4px 0", fontSize: 12, fontFamily: DS.mono,
              color: step.done ? DS.textSecondary : DS.textMuted,
            }}>
              {step.done ? <Check size={12} color={DS.success} /> : <Loader2 size={12} color={DS.accent} style={{ animation: "spin 1s linear infinite" }} />}
              {step.label}
            </div>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div style={{
      padding: "12px 16px", display: "flex", gap: 10,
      background: isUser ? "transparent" : `${DS.accent}04`,
    }}>
      <div style={{
        width: 24, height: 24, borderRadius: DS.radius.sm, flexShrink: 0,
        background: isUser ? DS.surfaceActive : `linear-gradient(135deg, ${DS.accent}, ${DS.info})`,
        display: "flex", alignItems: "center", justifyContent: "center",
      }}>
        {isUser ? <User size={13} color={DS.textSecondary} /> : <Bot size={13} color="#fff" />}
      </div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 4 }}>
          <span style={{ fontSize: 12, fontWeight: 600, color: DS.text }}>{isUser ? "You" : "Orchestrator"}</span>
          <span style={{ fontSize: 10, fontFamily: DS.mono, color: DS.textDim }}>{msg.ts}</span>
          {msg.cost != null && <Badge color={DS.success}>${msg.cost.toFixed(2)}</Badge>}
          {msg.quality != null && <Badge color={DS.accent}>Q: {msg.quality}</Badge>}
        </div>
        <div style={{
          fontSize: 13, lineHeight: 1.65, color: DS.textSecondary,
          fontFamily: DS.sans, whiteSpace: "pre-wrap",
        }}>
          {msg.content?.split(/(\*\*[^*]+\*\*)/g).map((part, i) =>
            part.startsWith("**") && part.endsWith("**")
              ? <strong key={i} style={{ color: DS.text, fontWeight: 600 }}>{part.slice(2, -2)}</strong>
              : <span key={i}>{part}</span>
          )}
        </div>
        {msg.files && (
          <div style={{ display: "flex", gap: 6, marginTop: 8, flexWrap: "wrap" }}>
            {msg.files.map((f, i) => (
              <span key={i} style={{
                display: "inline-flex", alignItems: "center", gap: 4,
                padding: "3px 8px", borderRadius: 4, fontSize: 11,
                fontFamily: DS.mono, color: DS.accent,
                background: DS.accentMuted, border: `1px solid ${DS.accent}20`,
                cursor: "pointer",
              }}><FileCode size={11} />{f}</span>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

/* ════════════════════════════════════════
   MAIN APP
   ════════════════════════════════════════ */
export default function OrchestratorIDE() {
  const [messages, setMessages] = useState(MOCK_MESSAGES);
  const [input, setInput] = useState("");
  const [mode, setMode] = useState("build");
  const [model, setModel] = useState("auto");
  const [autonomy, setAutonomy] = useState("standard");
  const [rightPanel, setRightPanel] = useState("preview"); // preview | code
  const [showFiles, setShowFiles] = useState(true);
  const [showTerminal, setShowTerminal] = useState(true);
  const [selectedFile, setSelectedFile] = useState("src/auth.py");
  const [showModelPicker, setShowModelPicker] = useState(false);
  const [showAutonomy, setShowAutonomy] = useState(false);
  const chatEndRef = useRef(null);
  const inputRef = useRef(null);

  useEffect(() => { chatEndRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages]);

  const handleSend = () => {
    if (!input.trim()) return;
    setMessages(prev => [...prev, { role: "user", content: input.trim(), ts: new Date().toLocaleTimeString("en", { hour: "2-digit", minute: "2-digit", hour12: false }) }]);
    setInput("");
    // Simulate response
    setTimeout(() => {
      setMessages(prev => [...prev, {
        role: "assistant", content: null, ts: new Date().toLocaleTimeString("en", { hour: "2-digit", minute: "2-digit", hour12: false }),
        thinking: true, steps: [
          { label: "Analyzing request...", done: false },
        ],
      }]);
    }, 400);
  };

  const currentModel = MODELS.find(m => m.id === model);
  const currentAutonomy = AUTONOMY.find(a => a.id === autonomy);

  return (
    <div style={{
      width: "100vw", height: "100vh", display: "flex", flexDirection: "column",
      background: DS.bg, color: DS.text, fontFamily: DS.sans,
      overflow: "hidden",
    }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
        @keyframes ping { 0% { transform:scale(1); opacity:.7; } 100% { transform:scale(2.5); opacity:0; } }
        @keyframes spin { to { transform:rotate(360deg); } }
        @keyframes fadeIn { from { opacity:0; transform:translateY(4px); } to { opacity:1; transform:translateY(0); } }
        ::-webkit-scrollbar { width:5px; height:5px; }
        ::-webkit-scrollbar-track { background:transparent; }
        ::-webkit-scrollbar-thumb { background:${DS.border}; border-radius:3px; }
        ::-webkit-scrollbar-thumb:hover { background:${DS.borderHover}; }
        textarea:focus, input:focus { outline:none; }
        ::placeholder { color: ${DS.textDim}; }
      `}</style>

      {/* ═══════════ TOP BAR ═══════════ */}
      <div style={{
        height: 44, flexShrink: 0, display: "flex", alignItems: "center",
        padding: "0 12px", gap: 8,
        background: DS.bgElevated, borderBottom: `1px solid ${DS.border}`,
      }}>
        {/* Logo */}
        <div style={{
          width: 26, height: 26, borderRadius: 6,
          background: `linear-gradient(135deg, ${DS.accent}, #a78bfa)`,
          display: "flex", alignItems: "center", justifyContent: "center",
          fontSize: 13, fontWeight: 800, color: "#fff",
        }}>◆</div>
        <span style={{ fontSize: 13, fontWeight: 700, letterSpacing: "-0.02em", marginRight: 4 }}>AI Orchestrator</span>
        <Badge color={DS.textMuted}>v6.2</Badge>

        <Divider vertical />

        {/* Project Name */}
        <div style={{ display: "flex", alignItems: "center", gap: 5, padding: "4px 8px", borderRadius: DS.radius.sm, background: DS.surface }}>
          <Folder size={12} color={DS.warning} />
          <span style={{ fontSize: 12, fontFamily: DS.mono, color: DS.text }}>fastapi-auth-service</span>
          <ChevronDown size={12} color={DS.textMuted} />
        </div>

        <Divider vertical />

        {/* Mode Selector */}
        <div style={{ display: "flex", gap: 2 }}>
          {MODES.map(m => (
            <Btn key={m.id} size="xs" active={mode === m.id} onClick={() => setMode(m.id)}>
              <m.icon size={12} />
              {m.name}
            </Btn>
          ))}
        </div>

        <div style={{ flex: 1 }} />

        {/* Model Picker */}
        <div style={{ position: "relative" }}>
          <Btn size="xs" variant="outline" onClick={() => setShowModelPicker(!showModelPicker)}>
            <Cpu size={11} />
            <span style={{ fontFamily: DS.mono }}>{currentModel?.name}</span>
            <ChevronDown size={11} />
          </Btn>
          {showModelPicker && (
            <div style={{
              position: "absolute", top: "100%", right: 0, marginTop: 4,
              background: DS.surface, border: `1px solid ${DS.border}`,
              borderRadius: DS.radius.md, padding: 4, width: 220, zIndex: 100,
              boxShadow: "0 12px 40px rgba(0,0,0,0.5)",
              animation: "fadeIn 0.15s ease-out",
            }}>
              {MODELS.map(m => (
                <div key={m.id} onClick={() => { setModel(m.id); setShowModelPicker(false); }}
                  style={{
                    display: "flex", alignItems: "center", gap: 8,
                    padding: "7px 10px", borderRadius: DS.radius.sm,
                    cursor: "pointer", background: model === m.id ? DS.surfaceActive : "transparent",
                    transition: "background 0.1s",
                  }}
                  onMouseEnter={e => { if (model !== m.id) e.currentTarget.style.background = DS.surfaceHover; }}
                  onMouseLeave={e => { if (model !== m.id) e.currentTarget.style.background = "transparent"; }}
                >
                  <span style={{ fontSize: 14, width: 20, textAlign: "center" }}>{m.icon}</span>
                  <div>
                    <div style={{ fontSize: 12, fontWeight: 500, color: DS.text }}>{m.name}</div>
                    <div style={{ fontSize: 10, color: DS.textMuted, fontFamily: DS.mono }}>{m.desc}</div>
                  </div>
                  {model === m.id && <Check size={13} color={DS.accent} style={{ marginLeft: "auto" }} />}
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Autonomy */}
        <div style={{ position: "relative" }}>
          <Btn size="xs" variant="outline" onClick={() => setShowAutonomy(!showAutonomy)}>
            <Shield size={11} color={currentAutonomy?.color} />
            <span style={{ fontFamily: DS.mono }}>{currentAutonomy?.name}</span>
          </Btn>
          {showAutonomy && (
            <div style={{
              position: "absolute", top: "100%", right: 0, marginTop: 4,
              background: DS.surface, border: `1px solid ${DS.border}`,
              borderRadius: DS.radius.md, padding: 4, width: 240, zIndex: 100,
              boxShadow: "0 12px 40px rgba(0,0,0,0.5)",
              animation: "fadeIn 0.15s ease-out",
            }}>
              {AUTONOMY.map(a => (
                <div key={a.id} onClick={() => { setAutonomy(a.id); setShowAutonomy(false); }}
                  style={{
                    display: "flex", alignItems: "center", gap: 8,
                    padding: "7px 10px", borderRadius: DS.radius.sm,
                    cursor: "pointer", background: autonomy === a.id ? DS.surfaceActive : "transparent",
                  }}
                  onMouseEnter={e => { if (autonomy !== a.id) e.currentTarget.style.background = DS.surfaceHover; }}
                  onMouseLeave={e => { if (autonomy !== a.id) e.currentTarget.style.background = "transparent"; }}
                >
                  <Dot color={a.color} />
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 12, fontWeight: 500, color: DS.text }}>{a.name}</div>
                    <div style={{ fontSize: 10, color: DS.textMuted, fontFamily: DS.mono }}>{a.desc}</div>
                  </div>
                  {autonomy === a.id && <Check size={13} color={DS.accent} />}
                </div>
              ))}
            </div>
          )}
        </div>

        <Divider vertical />

        {/* Actions */}
        <Btn size="xs" variant="outline"><GitBranch size={12} /> main</Btn>
        <Btn size="sm" variant="filled" style={{ gap: 6 }}><Play size={12} /> Deploy</Btn>
      </div>

      {/* ═══════════ MAIN CONTENT ═══════════ */}
      <div style={{ flex: 1, display: "flex", overflow: "hidden" }}>

        {/* ──── LEFT: Chat Panel ──── */}
        <div style={{
          width: 420, flexShrink: 0, display: "flex", flexDirection: "column",
          borderRight: `1px solid ${DS.border}`,
          background: DS.bgElevated,
        }}>
          {/* Chat Header */}
          <div style={{
            padding: "8px 12px", display: "flex", alignItems: "center", justifyContent: "space-between",
            borderBottom: `1px solid ${DS.border}`,
          }}>
            <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
              <Dot color={DS.success} pulse />
              <span style={{ fontSize: 12, fontWeight: 600 }}>Chat</span>
              <Badge color={DS.textMuted}>{messages.length} messages</Badge>
            </div>
            <div style={{ display: "flex", gap: 2 }}>
              <Btn size="xs"><RotateCcw size={11} /> New</Btn>
            </div>
          </div>

          {/* Messages */}
          <div style={{ flex: 1, overflow: "auto", padding: "4px 0" }}>
            {messages.map((msg, i) => <ChatMessage key={i} msg={msg} />)}
            <div ref={chatEndRef} />
          </div>

          {/* Input Area */}
          <div style={{
            padding: 10, borderTop: `1px solid ${DS.border}`,
            background: DS.bg,
          }}>
            {/* Context Pills */}
            <div style={{ display: "flex", gap: 4, marginBottom: 8, flexWrap: "wrap" }}>
              <Btn size="xs" variant="outline"><Paperclip size={10} /> Attach</Btn>
              <Btn size="xs" variant="outline"><Globe size={10} /> URL</Btn>
              <Btn size="xs" variant="outline"><GitBranch size={10} /> Commit</Btn>
              <Btn size="xs" variant="outline"><Camera size={10} /> Screenshot</Btn>
              <Btn size="xs" variant="outline"><Sparkles size={10} /> Enhance</Btn>
            </div>

            {/* Text Input */}
            <div style={{
              display: "flex", alignItems: "flex-end", gap: 6,
              background: DS.surface, border: `1px solid ${DS.border}`,
              borderRadius: DS.radius.md, padding: "8px 10px",
              transition: "border-color 0.15s",
            }}
              onFocus={() => {}}
            >
              <textarea
                ref={inputRef}
                value={input}
                onChange={e => setInput(e.target.value)}
                onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); handleSend(); } }}
                placeholder={mode === "plan" ? "Describe what you want to plan..." : mode === "chat" ? "Ask a question..." : "Describe what to build..."}
                rows={2}
                style={{
                  flex: 1, background: "transparent", border: "none",
                  color: DS.text, fontSize: 13, fontFamily: DS.sans,
                  resize: "none", lineHeight: 1.5,
                }}
              />
              <div style={{ display: "flex", gap: 2, flexShrink: 0 }}>
                <Btn size="xs" style={{ color: DS.textMuted }}><Mic size={13} /></Btn>
                <Btn size="xs" variant="filled" onClick={handleSend}
                  style={{ opacity: input.trim() ? 1 : 0.4 }}
                ><Send size={12} /></Btn>
              </div>
            </div>

            {/* Footer hints */}
            <div style={{
              display: "flex", justifyContent: "space-between", marginTop: 6,
              fontSize: 10, color: DS.textDim, fontFamily: DS.mono,
            }}>
              <span><Kbd>Enter</Kbd> send · <Kbd>Shift+Enter</Kbd> newline · <Kbd>@</Kbd> mention file</span>
              <span>$0.33 / $5.00</span>
            </div>
          </div>
        </div>

        {/* ──── MIDDLE: File Tree (collapsible) ──── */}
        {showFiles && (
          <div style={{
            width: 200, flexShrink: 0, display: "flex", flexDirection: "column",
            borderRight: `1px solid ${DS.border}`,
            background: DS.bg,
          }}>
            <div style={{
              padding: "8px 10px", display: "flex", alignItems: "center", justifyContent: "space-between",
              borderBottom: `1px solid ${DS.border}`,
            }}>
              <span style={{ fontSize: 11, fontWeight: 600, color: DS.textSecondary, letterSpacing: "0.04em", textTransform: "uppercase" }}>Files</span>
              <Btn size="xs" onClick={() => setShowFiles(false)}><PanelLeftClose size={12} /></Btn>
            </div>
            <div style={{ flex: 1, overflow: "auto", padding: "4px 0" }}>
              {INITIAL_FILES.map((item, i) => (
                <FileTreeItem key={i} item={item} selected={selectedFile} onSelect={setSelectedFile} />
              ))}
            </div>
          </div>
        )}

        {/* ──── RIGHT: Preview / Code ──── */}
        <div style={{ flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" }}>
          {/* Right Panel Header */}
          <div style={{
            height: 38, display: "flex", alignItems: "center", gap: 4,
            padding: "0 10px", borderBottom: `1px solid ${DS.border}`,
            background: DS.bgElevated,
          }}>
            {!showFiles && (
              <Btn size="xs" onClick={() => setShowFiles(true)}><PanelLeft size={12} /></Btn>
            )}
            <Btn size="xs" active={rightPanel === "preview"} onClick={() => setRightPanel("preview")}>
              <Eye size={12} /> Preview
            </Btn>
            <Btn size="xs" active={rightPanel === "code"} onClick={() => setRightPanel("code")}>
              <Code2 size={12} /> Code
            </Btn>

            {rightPanel === "preview" && (
              <>
                <Divider vertical />
                <div style={{
                  flex: 1, display: "flex", alignItems: "center", gap: 6,
                  background: DS.surface, borderRadius: 5, padding: "3px 10px",
                  marginLeft: 4, marginRight: 4,
                }}>
                  <Globe size={11} color={DS.textMuted} />
                  <span style={{ fontSize: 11, fontFamily: DS.mono, color: DS.textSecondary }}>
                    localhost:8000/docs
                  </span>
                  <Dot color={DS.success} />
                </div>
              </>
            )}

            {rightPanel === "code" && (
              <>
                <Divider vertical />
                <div style={{ display: "flex", alignItems: "center", gap: 4, flex: 1 }}>
                  <FileCode size={12} color={DS.accent} />
                  <span style={{ fontSize: 12, fontFamily: DS.mono, color: DS.text }}>{selectedFile}</span>
                </div>
              </>
            )}

            <div style={{ display: "flex", gap: 2 }}>
              <Btn size="xs"><RefreshCw size={11} /></Btn>
              <Btn size="xs"><ExternalLink size={11} /></Btn>
              <Btn size="xs"><Copy size={11} /></Btn>
            </div>
          </div>

          {/* Content Area */}
          <div style={{ flex: 1, overflow: "hidden", display: "flex", flexDirection: "column" }}>
            {rightPanel === "preview" ? (
              /* ── Preview Panel ── */
              <div style={{
                flex: 1, display: "flex", alignItems: "center", justifyContent: "center",
                background: "#fafafa", position: "relative",
              }}>
                {/* Simulated Swagger UI */}
                <div style={{
                  width: "90%", maxWidth: 700, background: "#fff",
                  borderRadius: 12, boxShadow: "0 4px 24px rgba(0,0,0,0.08)",
                  padding: 32, color: "#1a1a2e",
                  fontFamily: "'Inter', sans-serif",
                }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 20 }}>
                    <div style={{ width: 36, height: 36, borderRadius: 8, background: "#10b981", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontWeight: 700, fontSize: 16 }}>A</div>
                    <div>
                      <div style={{ fontSize: 20, fontWeight: 700 }}>Auth Service</div>
                      <div style={{ fontSize: 12, color: "#6b7280" }}>v1.0.0 · FastAPI · OpenAPI 3.1</div>
                    </div>
                  </div>

                  {[
                    { method: "POST", path: "/auth/register", desc: "Register a new user", color: "#10b981" },
                    { method: "POST", path: "/auth/login", desc: "Authenticate and return JWT", color: "#10b981" },
                    { method: "GET", path: "/auth/me", desc: "Get current user profile", color: "#3b82f6" },
                    { method: "PUT", path: "/auth/password", desc: "Change password", color: "#f59e0b" },
                    { method: "DELETE", path: "/auth/account", desc: "Delete account", color: "#ef4444" },
                  ].map((ep, i) => (
                    <div key={i} style={{
                      display: "flex", alignItems: "center", gap: 12,
                      padding: "10px 14px", marginBottom: 6, borderRadius: 8,
                      border: "1px solid #e5e7eb", cursor: "pointer",
                      transition: "background 0.1s",
                    }}
                      onMouseEnter={e => e.currentTarget.style.background = "#f9fafb"}
                      onMouseLeave={e => e.currentTarget.style.background = "transparent"}
                    >
                      <span style={{
                        padding: "2px 8px", borderRadius: 4, fontSize: 11, fontWeight: 700,
                        fontFamily: "'JetBrains Mono', monospace",
                        color: "#fff", background: ep.color,
                      }}>{ep.method}</span>
                      <span style={{ fontSize: 13, fontFamily: "'JetBrains Mono', monospace", fontWeight: 600, color: "#1f2937" }}>{ep.path}</span>
                      <span style={{ fontSize: 12, color: "#9ca3af", flex: 1 }}>{ep.desc}</span>
                      <ChevronDown size={14} color="#d1d5db" />
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              /* ── Code Editor ── */
              <div style={{
                flex: 1, overflow: "auto", padding: "12px 0",
                background: DS.bg, fontFamily: DS.mono, fontSize: 12.5,
                lineHeight: 1.7, counterReset: "line",
              }}>
                {MOCK_CODE.split("\n").map((line, i) => (
                  <div key={i} style={{
                    display: "flex", padding: "0 16px",
                    background: i === 42 ? `${DS.accent}08` : "transparent",
                  }}>
                    <span style={{
                      width: 40, flexShrink: 0, textAlign: "right",
                      color: DS.textDim, paddingRight: 16,
                      userSelect: "none", fontSize: 11,
                    }}>{i + 1}</span>
                    <span style={{
                      color: line.startsWith("#") || line.startsWith('"""') ? DS.textMuted
                        : line.includes("def ") || line.includes("class ") ? DS.accent
                        : line.includes("return ") || line.includes("import ") || line.includes("from ") ? DS.error
                        : line.includes("async ") ? DS.warning
                        : line.includes('"') || line.includes("'") ? DS.success
                        : line.includes("@") ? DS.info
                        : DS.textSecondary,
                      whiteSpace: "pre",
                    }}>{line || " "}</span>
                  </div>
                ))}
              </div>
            )}

            {/* ── Terminal (collapsible) ── */}
            {showTerminal && (
              <div style={{
                height: 180, flexShrink: 0,
                borderTop: `1px solid ${DS.border}`,
                display: "flex", flexDirection: "column",
                background: DS.bg,
              }}>
                <div style={{
                  height: 30, display: "flex", alignItems: "center", gap: 6,
                  padding: "0 10px", borderBottom: `1px solid ${DS.border}`,
                  background: DS.bgElevated,
                }}>
                  <Terminal size={12} color={DS.textMuted} />
                  <span style={{ fontSize: 11, fontWeight: 600, color: DS.textSecondary }}>Terminal</span>
                  <Badge color={DS.success}>17/17 passed</Badge>
                  <div style={{ flex: 1 }} />
                  <Btn size="xs" onClick={() => setShowTerminal(false)}><ChevronDown size={11} /></Btn>
                </div>
                <div style={{ flex: 1, overflow: "auto", padding: "6px 12px", fontFamily: DS.mono, fontSize: 11.5, lineHeight: 1.7 }}>
                  {TERMINAL_LINES.map((line, i) => (
                    <div key={i} style={{
                      color: line.type === "cmd" ? DS.text
                        : line.type === "success" ? DS.success
                        : line.type === "error" ? DS.error
                        : line.type === "info" ? DS.info
                        : DS.textSecondary,
                      fontWeight: line.type === "cmd" || line.type === "success" ? 500 : 400,
                    }}>{line.text}</div>
                  ))}
                </div>
              </div>
            )}

            {!showTerminal && (
              <div style={{
                height: 30, display: "flex", alignItems: "center", gap: 6,
                padding: "0 10px", borderTop: `1px solid ${DS.border}`,
                background: DS.bgElevated, cursor: "pointer",
              }} onClick={() => setShowTerminal(true)}>
                <Terminal size={12} color={DS.textMuted} />
                <span style={{ fontSize: 11, color: DS.textSecondary }}>Terminal</span>
                <Badge color={DS.success}>17/17</Badge>
                <div style={{ flex: 1 }} />
                <ChevronUp size={11} color={DS.textMuted} />
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ═══════════ BOTTOM STATUS BAR ═══════════ */}
      <div style={{
        height: 24, flexShrink: 0, display: "flex", alignItems: "center",
        padding: "0 10px", gap: 12,
        background: DS.bgElevated, borderTop: `1px solid ${DS.border}`,
        fontSize: 10, fontFamily: DS.mono, color: DS.textMuted,
      }}>
        <span style={{ display: "flex", alignItems: "center", gap: 4 }}>
          <Dot color={DS.success} /> Connected
        </span>
        <span>Mode: {mode}</span>
        <span>Model: {currentModel?.name}</span>
        <span>Autonomy: {currentAutonomy?.name}</span>
        <Divider vertical />
        <span style={{ display: "flex", alignItems: "center", gap: 4 }}>
          <DollarSign size={10} /> $0.33 / $5.00
        </span>
        <span style={{ display: "flex", alignItems: "center", gap: 4 }}>
          <Clock size={10} /> 3m 12s
        </span>
        <span>Tasks: 5/8</span>
        <span>Quality: 0.94</span>
        <div style={{ flex: 1 }} />
        <span>Cache: 73% hit</span>
        <span>Python 3.12</span>
        <span>UTF-8</span>
      </div>

      {/* Click-away for dropdowns */}
      {(showModelPicker || showAutonomy) && (
        <div style={{ position: "fixed", inset: 0, zIndex: 50 }}
          onClick={() => { setShowModelPicker(false); setShowAutonomy(false); }} />
      )}
    </div>
  );
}
